### Historical experiment notebook

Saved outputs reflect earlier execution sessions and dataset availability.
Paths and label-length handling were updated during repository cleanup.
The notebook has not been rerun after these changes.

In [ ]:
# =====
from pathlib import Path

for candidate in (Path.cwd(), *Path.cwd().parents):
    if (candidate / "requirements-asr.txt").is_file():
        requirements_file = candidate / "requirements-asr.txt"
        break
else:
    raise FileNotFoundError("Could not find requirements-asr.txt")

%pip install -r "{requirements_file}"
# =====

In [ ]:
# =====
from pathlib import Path

for candidate in (Path.cwd(), *Path.cwd().parents):
    if (
        (candidate / "1_ASR").is_dir()
        and (candidate / "2_QA_GENERATION").is_dir()
    ):
        PROJECT_ROOT = candidate
        break
else:
    raise FileNotFoundError(
        "Open the notebook from inside the project folder."
    )

ASR_DIR = PROJECT_ROOT / "1_ASR"
DATASET_DIR = PROJECT_ROOT / "NileTTS-dataset"
DATA_ROOT = str(DATASET_DIR)
# =====

In [ ]:

from huggingface_hub import snapshot_download
import pandas as pd
from pathlib import Path
import os
import re

repo_id = "KickItLikeShika/NileTTS-dataset"

snapshot_download(
    repo_id=repo_id,
    repo_type="dataset",
    # =====
    # local_dir="NileTTS-dataset",
    local_dir=str(DATASET_DIR),
    # =====
    allow_patterns=[
        "metadata_train.csv",
        "metadata_eval.csv",
        "wavs/*.wav"
    ]
)

# =====
# root = Path("NileTTS-dataset")
root = DATASET_DIR
# =====

train_df = pd.read_csv(root / "metadata_train.csv", sep="|")
eval_df  = pd.read_csv(root / "metadata_eval.csv",  sep="|")

train_df["audio_file"] = train_df["audio_file"].str.replace("wav/", "wavs/", regex=False)
eval_df["audio_file"]  = eval_df["audio_file"].str.replace("wav/",  "wavs/", regex=False)

train_df["audio_path"] = train_df["audio_file"].apply(lambda x: str(root / x))
eval_df["audio_path"]  = eval_df["audio_file"].apply(lambda x: str(root / x))

print("Train shape:", train_df.shape)
print("Eval shape:",  eval_df.shape)
print("First audio exists:", os.path.exists(train_df.loc[0, "audio_path"]))

# =====
# train_df.to_csv("niletts_train_clean.csv", index=False)
# eval_df.to_csv("niletts_eval_clean.csv",   index=False)

# The dataframes are used directly by the following cells.
# =====

train_df.head()

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.11.0)
Collecting huggingface_hub
  Downloading huggingface_hub-1.14.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.7 MB/s eta 0:00:00
Requirement already satisfied: soundfile in /usr/local/lib/python3.12/dist-packages (0.13.1)
Requirement already satisfied: librosa in /usr/local/lib/python3.12/dist-packages (0.11.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.12/dist-packages (1.9.6)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile) (2.0.0)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.12/dist-packages (from librosa) (3.1.0)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.60.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.16.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.5.3)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.0.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.5)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.1.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from wordcloud) (11.3.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from wordcloud) (3.10.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile) (3.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.0->librosa) (0.43.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa) (4.9.6)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa) (2.32.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub) (0.0.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.20.0->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.20.0->huggingface_hub) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.20.0->huggingface_hub) (0.1.2)
Downloading huggingface_hub-1.14.0-py3-none-any.whl (661 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.5/661.5 kB 27.5 MB/s eta 0:00:00
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 64.8 MB/s eta 0:00:00
Installing collected packages: pandas, huggingface_hub
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface_hub 1.11.0
    Uninstalling huggingface_hub-1.11.0:
      Successfully uninstalled huggingface_hub-1.11.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.3 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.3 which is incompatible.
Successfully installed huggingface_hub-1.14.0 pandas-3.0.3

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Fetching ... files: 0it [00:00, ?it/s]

HTTP Error 504 thrown while requesting HEAD https://huggingface.co/datasets/KickItLikeShika/NileTTS-dataset/resolve/6905cb892bda2a315377178729ab2e718c0e63d4/wavs/general_22_00037.wav
WARNING:huggingface_hub.utils._http:HTTP Error 504 thrown while requesting HEAD https://huggingface.co/datasets/KickItLikeShika/NileTTS-dataset/resolve/6905cb892bda2a315377178729ab2e718c0e63d4/wavs/general_22_00037.wav
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
HTTP Error 504 thrown while requesting HEAD https://huggingface.co/datasets/KickItLikeShika/NileTTS-dataset/resolve/6905cb892bda2a315377178729ab2e718c0e63d4/wavs/general_22_00037.wav
WARNING:huggingface_hub.utils._http:HTTP Error 504 thrown while requesting HEAD https://huggingface.co/datasets/KickItLikeShika/NileTTS-dataset/resolve/6905cb892bda2a315377178729ab2e718c0e63d4/wavs/general_22_00037.wav
Retrying in 2s [Retry 2/5].
WARNING:huggingface_hub.utils._http:Retrying in 2s [Retry 2/5].

Train shape: (8571, 4)
Eval shape: (950, 4)
First audio exists: True

,audio_file,text,speaker_name,audio_path
0,wavs/general_1_00041.wav,تماما وبجانب درجة الجودة العامة بيسألهم أسئلة ...,SPEAKER_02,NileTTS-dataset/wavs/general_1_00041.wav
1,wavs/medical_8_00009.wav,لأن العواقب أسوأ بكتير من اللي بنتخيله بص، الل...,SPEAKER_02,NileTTS-dataset/wavs/medical_8_00009.wav
2,wavs/sales_15_00036.wav,بنبص بره على العميل و القيمة اللي بيحصل عليها....,SPEAKER_01,NileTTS-dataset/wavs/sales_15_00036.wav
3,wavs/sales_3_00038.wav,تاني حاجة خططك كلها بتتدمر. حلم إنك تستقر في ب...,SPEAKER_02,NileTTS-dataset/wavs/sales_3_00038.wav
4,wavs/sales_26_00088.wav,هنا الأمور بدأت تتغير بشكل ملموس قوي، الإنترنت...,SPEAKER_02,NileTTS-dataset/wavs/sales_26_00088.wav

In [3]:
from transformers import (
    WhisperProcessor,
    WhisperForConditionalGeneration,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)

print("Whisper imports are working.")

Whisper imports are working.

In [ ]:
# =====
# import shutil
# import os

# DATA_ROOT = "/content/NileTTS-dataset"  # change if needed
# BACKUP_PATH = "/content/drive/MyDrive/NileTTS-dataset"

# if os.path.exists(DATA_ROOT):
#     if not os.path.exists(BACKUP_PATH):
#         shutil.copytree(DATA_ROOT, BACKUP_PATH)
#         print("Copied dataset to Drive.")
#     else:
#         print("Backup already exists.")
# else:
#     print("Dataset folder not found. Check DATA_ROOT.")
# =====

Copied dataset to Drive.

In [ ]:
# =====
# from google.colab import drive
# drive.mount("/content/drive")
# =====

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import numpy as np
import pandas as pd
import pyarrow as pa
import datasets
import transformers
import sklearn
import scipy
import accelerate

print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("pyarrow:", pa.__version__)
print("datasets:", datasets.__version__)
print("transformers:", transformers.__version__)
print("sklearn:", sklearn.__version__)
print("scipy:", scipy.__version__)
print("accelerate:", accelerate.__version__)

numpy: 1.26.4
pandas: 2.2.2
pyarrow: 15.0.2
datasets: 2.19.2
transformers: 4.41.2
sklearn: 1.4.2
scipy: 1.13.1
accelerate: 1.2.1

In [12]:
from datasets import Dataset, DatasetDict, Audio

from transformers import (
    WhisperProcessor,
    WhisperForConditionalGeneration,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)

print("All imports are working.")

All imports are working.

In [ ]:
# =====
# import os

# DATA_ROOT_DRIVE = "/content/drive/MyDrive/Datasets/NileTTS-dataset"

# print(os.path.exists(DATA_ROOT_DRIVE))
# print(os.listdir(DATA_ROOT_DRIVE)[:20])
# =====

True
['wavs', 'metadata_train.csv', 'metadata_eval.csv', '.cache']

In [ ]:
# =====
# import os

# print("DATA_ROOT_DRIVE =", DATA_ROOT_DRIVE)
# print("Exists:", os.path.exists(DATA_ROOT_DRIVE))

# if os.path.exists(DATA_ROOT_DRIVE):
#     print("Contents:")
#     print(os.listdir(DATA_ROOT_DRIVE)[:50])
# =====

DATA_ROOT_DRIVE = /content/drive/MyDrive/Datasets/NileTTS-dataset
Exists: True
Contents:
['wavs', 'metadata_train.csv', 'metadata_eval.csv', '.cache']

In [ ]:
# =====
# import os
# import pandas as pd

# DATA_ROOT_DRIVE = "/content/drive/MyDrive/Datasets/NileTTS-dataset"

# train_csv = os.path.join(DATA_ROOT_DRIVE, "metadata_train.csv")
# eval_csv = os.path.join(DATA_ROOT_DRIVE, "metadata_eval.csv")

# print("Train CSV exists:", os.path.exists(train_csv))
# print("Eval CSV exists:", os.path.exists(eval_csv))
# print("Dataset contents:", os.listdir(DATA_ROOT_DRIVE)[:20])

# train_df = pd.read_csv(train_csv, sep="|")
# eval_df = pd.read_csv(eval_csv, sep="|")

# print("Train rows:", len(train_df))
# print("Eval rows:", len(eval_df))
# print("Columns:", train_df.columns.tolist())

# train_df.head()
# =====

Train CSV exists: True
Eval CSV exists: True
Dataset contents: ['wavs', 'metadata_train.csv', 'metadata_eval.csv', '.cache']
Train rows: 8571
Eval rows: 950
Columns: ['audio_file', 'text', 'speaker_name']

,audio_file,text,speaker_name
0,wavs/general_1_00041.wav,تماما وبجانب درجة الجودة العامة بيسألهم أسئلة ...,SPEAKER_02
1,wavs/medical_8_00009.wav,لأن العواقب أسوأ بكتير من اللي بنتخيله بص، الل...,SPEAKER_02
2,wavs/sales_15_00036.wav,بنبص بره على العميل و القيمة اللي بيحصل عليها....,SPEAKER_01
3,wavs/sales_3_00038.wav,تاني حاجة خططك كلها بتتدمر. حلم إنك تستقر في ب...,SPEAKER_02
4,wavs/sales_26_00088.wav,هنا الأمور بدأت تتغير بشكل ملموس قوي، الإنترنت...,SPEAKER_02

In [ ]:
# =====
# import shutil
# import os

# DATA_ROOT_DRIVE = "/content/drive/MyDrive/Datasets/NileTTS-dataset"
# DATA_ROOT = "/content/NileTTS-dataset"

# if os.path.exists(DATA_ROOT):
#     shutil.rmtree(DATA_ROOT)

# shutil.copytree(DATA_ROOT_DRIVE, DATA_ROOT)

# print("Copied to /content")
# print(os.listdir(DATA_ROOT)[:20])
# =====

KeyboardInterrupt:

In [ ]:
# =====
# import os

# DATA_ROOT_DRIVE = "/content/drive/MyDrive/Datasets/NileTTS-dataset"
# DATA_ROOT = "/content/NileTTS-dataset"

# if os.path.exists(DATA_ROOT):
#     print("Using existing /content copy:", DATA_ROOT)
# else:
#     print("No /content copy found. Use Drive path directly for now.")

# print("Drive path exists:", os.path.exists(DATA_ROOT_DRIVE))
# print("Content path exists:", os.path.exists(DATA_ROOT))

print("Dataset directory:", DATASET_DIR)
print("Dataset directory exists:", DATASET_DIR.is_dir())
# =====

Using existing /content copy: /content/NileTTS-dataset
Drive path exists: True
Content path exists: True

In [ ]:
import os

# =====
# DATA_ROOT = "/content/drive/MyDrive/Datasets/NileTTS-dataset"
DATA_ROOT = str(DATASET_DIR)
# =====

def fix_audio_path(path):
    path = str(path).strip().replace("\\", "/")

    # Your metadata already has paths like wavs/general_1_00041.wav
    if path.startswith("wav/"):
        path = path.replace("wav/", "wavs/", 1)

    if "/" not in path:
        path = f"wavs/{path}"

    return os.path.join(DATA_ROOT, path)


train_df["audio"] = train_df["audio_file"].apply(fix_audio_path)
eval_df["audio"] = eval_df["audio_file"].apply(fix_audio_path)

train_df["exists"] = train_df["audio"].apply(os.path.exists)
eval_df["exists"] = eval_df["audio"].apply(os.path.exists)

print("Train existing audio:", train_df["exists"].sum(), "/", len(train_df))
print("Eval existing audio:", eval_df["exists"].sum(), "/", len(eval_df))
print("Total existing:", train_df["exists"].sum() + eval_df["exists"].sum())

print(train_df[["audio_file", "audio", "exists"]].head())

Train existing audio: 5383 / 8571
Eval existing audio: 565 / 950
Total existing: 5948
                 audio_file  \
0  wavs/general_1_00041.wav
1  wavs/medical_8_00009.wav
2   wavs/sales_15_00036.wav
3    wavs/sales_3_00038.wav
4   wavs/sales_26_00088.wav

                                               audio  exists
0  /content/drive/MyDrive/Datasets/NileTTS-datase...   False
1  /content/drive/MyDrive/Datasets/NileTTS-datase...   False
2  /content/drive/MyDrive/Datasets/NileTTS-datase...   False
3  /content/drive/MyDrive/Datasets/NileTTS-datase...   False
4  /content/drive/MyDrive/Datasets/NileTTS-datase...    True

In [ ]:
# =====
missing_train = int((~train_df["exists"]).sum())
missing_eval = int((~eval_df["exists"]).sum())

if missing_train or missing_eval:
    raise FileNotFoundError(
        f"Dataset audio is incomplete: "
        f"{missing_train} missing train files and "
        f"{missing_eval} missing eval files. "
        f"Check DATA_ROOT and complete the dataset download."
    )
# =====

train_df = train_df[train_df["exists"]].drop(columns=["exists"]).reset_index(drop=True)
eval_df = eval_df[eval_df["exists"]].drop(columns=["exists"]).reset_index(drop=True)

print("Final train size:", len(train_df))
print("Final eval size:", len(eval_df))
print("Columns:", train_df.columns.tolist())

Final train size: 5383
Final eval size: 565
Columns: ['audio_file', 'text', 'speaker_name', 'audio']

In [8]:
from datasets import Dataset, DatasetDict, Audio

print("Dataset imports are working.")

Dataset imports are working.

In [9]:
import re
def clean_text(text):
    text = str(text)
    text = text.replace("\n", " ").replace("\t", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text


train_df["text"] = train_df["text"].apply(clean_text)
eval_df["text"] = eval_df["text"].apply(clean_text)

train_df = train_df[train_df["text"].str.len() > 0].reset_index(drop=True)
eval_df = eval_df[eval_df["text"].str.len() > 0].reset_index(drop=True)

train_df[["audio_file", "text", "speaker_name"]].head()

,audio_file,text,speaker_name
0,wavs/sales_26_00088.wav,هنا الأمور بدأت تتغير بشكل ملموس قوي، الإنترنت...,SPEAKER_02
1,wavs/sales_5_00170.wav,بالزبط الأساس: التلاجة، الغسالة، البوتاجاز، ال...,SPEAKER_02
2,wavs/medical_5_00068.wav,سؤال يستحق أننا نفكر فيه,SPEAKER_01
3,wavs/sales_33_00043.wav,طيب فيه فكرة كمان لفتت نظري في المصادر. و ممكن...,SPEAKER_02
4,wavs/general_44_00031.wav,آه الجملة دي الوحدها تخلي الواحد يعترف بجرائم ...,SPEAKER_02

In [10]:
from datasets import Dataset, DatasetDict, Audio

train_dataset = Dataset.from_pandas(
    train_df[["audio", "text", "audio_file", "speaker_name"]],
    preserve_index=False
)

eval_dataset = Dataset.from_pandas(
    eval_df[["audio", "text", "audio_file", "speaker_name"]],
    preserve_index=False
)

dataset = DatasetDict({
    "train": train_dataset,
    "eval": eval_dataset
})

dataset = dataset.cast_column("audio", Audio(sampling_rate=16000))

dataset

DatasetDict({
    train: Dataset({
        features: ['audio', 'text', 'audio_file', 'speaker_name'],
        num_rows: 5383
    })
    eval: Dataset({
        features: ['audio', 'text', 'audio_file', 'speaker_name'],
        num_rows: 565
    })
})

In [13]:
MODEL_NAME = "openai/whisper-small"

processor = WhisperProcessor.from_pretrained(
    MODEL_NAME,
    language="Arabic",
    task="transcribe"
)

model = WhisperForConditionalGeneration.from_pretrained(MODEL_NAME)

model.generation_config.language = "arabic"
model.generation_config.task = "transcribe"

model.config.use_cache = False

print("Model loaded:", MODEL_NAME)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Model loaded: openai/whisper-small

In [ ]:
def prepare_dataset(batch):
    audio = batch["audio"]

    batch["input_features"] = processor.feature_extractor(
        audio["array"],
        sampling_rate=audio["sampling_rate"]
    ).input_features[0]

    # =====
    # batch["labels"] = processor.tokenizeoutput_dir="./whisper-small-niletts-egyptian-arabic",r(batch["text"]).input_ids
    batch["labels"] = processor.tokenizer(
        batch["text"],
        truncation=True,
        max_length=448
    ).input_ids
    # =====

    return batch

In [20]:
small_dataset = DatasetDict({
    "train": dataset["train"].select(range(min(1000, len(dataset["train"])))),
    "eval": dataset["eval"].select(range(min(200, len(dataset["eval"]))))
})
processed_train = small_dataset["train"].map(
    prepare_dataset,
    remove_columns=small_dataset["train"].column_names,
    num_proc=1,
    writer_batch_size=8,
    keep_in_memory=False,
    load_from_cache_file=False,
    desc="Processing small train set"
)

processed_eval = small_dataset["eval"].map(
    prepare_dataset,
    remove_columns=small_dataset["eval"].column_names,
    num_proc=1,
    writer_batch_size=8,
    keep_in_memory=False,
    load_from_cache_file=False,
    desc="Processing small eval set"
)

processed_dataset = DatasetDict({
    "train": processed_train,
    "eval": processed_eval
})

Processing small train set:   0%|          | 0/1000 [00:00<?, ? examples/s]

Processing small eval set:   0%|          | 0/200 [00:00<?, ? examples/s]

In [ ]:
processed_train = dataset["train"].map(
    prepare_dataset,
    remove_columns=dataset["train"].column_names,
    num_proc=1,
    writer_batch_size=16,
    keep_in_memory=False,
    load_from_cache_file=False,
    desc="Processing train set"
)

processed_eval = dataset["eval"].map(
    prepare_dataset,
    remove_columns=dataset["eval"].column_names,
    num_proc=1,
    writer_batch_size=16,
    keep_in_memory=False,
    load_from_cache_file=False,
    desc="Processing eval set"
)

processed_dataset = DatasetDict({
    "train": processed_train,
    "eval": processed_eval
})

processed_dataset

Processing train set:   0%|          | 0/5383 [00:00<?, ? examples/s]

In [1]:
import gc
import torch

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()

In [ ]:
from dataclasses import dataclass
from typing import Any, Dict, List, Union

@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any
    decoder_start_token_id: int

    def __call__(
        self,
        features: List[Dict[str, Union[List[int], torch.Tensor]]]
    ) -> Dict[str, torch.Tensor]:

        input_features = [
            {"input_features": feature["input_features"]}
            for feature in features
        ]

        batch = self.processor.feature_extractor.pad(
            input_features,
            return_tensors="pt"
        )

        label_features = [
            {"input_ids": feature["labels"]}
            for feature in features
        ]

        labels_batch = self.processor.tokenizer.pad(
            label_features,
            return_tensors="pt"
        )

        labels = labels_batch["input_ids"].masked_fill(
            labels_batch.attention_mask.ne(1),
            -100
        )

        if (labels[:, 0] == self.decoder_start_token_id).all().cpu().item():
            labels = labels[:, 1:]

        batch["labels"] = labels

        return batch


data_collator = DataCollatorSpeechSeq2SeqWithPadding(
    processor=processor,
    decoder_start_token_id=model.config.decoder_start_token_id
)

In [ ]:
import evaluate
wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")

In [ ]:
def normalize_arabic_for_eval(text):
    text = str(text)

    # Remove tashkeel
    text = re.sub(r"[\u064B-\u065F\u0670]", "", text)

    # Normalize Arabic letters
    text = re.sub(r"[إأآا]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ة", "ه", text)

    # Remove punctuation but keep Arabic/English letters and numbers
    text = re.sub(r"[^\w\s\u0600-\u06FF]", " ", text)

    # Normalize spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


def compute_metrics(pred):
    pred_ids = pred.predictions
    label_ids = pred.label_ids

    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.tokenizer.batch_decode(
        pred_ids,
        skip_special_tokens=True
    )

    label_str = processor.tokenizer.batch_decode(
        label_ids,
        skip_special_tokens=True
    )

    pred_str = [normalize_arabic_for_eval(x) for x in pred_str]
    label_str = [normalize_arabic_for_eval(x) for x in label_str]

    wer = wer_metric.compute(
        predictions=pred_str,
        references=label_str
    )

    cer = cer_metric.compute(
        predictions=pred_str,
        references=label_str
    )

    return {
        "wer": wer,
        "cer": cer
    }

In [ ]:
training_args = Seq2SeqTrainingArguments(
    # =====
    # output_dir="./whisper-small-niletts-egyptian-arabic",
    output_dir=str(ASR_DIR / "whisper-small-niletts-egyptian-arabic"),
    # =====

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,

    learning_rate=1e-5,
    warmup_steps=100,
    num_train_epochs=3,

    gradient_checkpointing=True,
    fp16=torch.cuda.is_available(),

    eval_strategy="steps",
    eval_steps=250,
    save_strategy="steps",
    save_steps=250,
    logging_steps=25,

    predict_with_generate=True,
    generation_max_length=225,

    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="wer",
    greater_is_better=False,

    report_to="none",
    remove_unused_columns=False
)

In [ ]:
trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=processed_dataset["train"],
    eval_dataset=processed_dataset["eval"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    # =====
    # processing_class=processor
    tokenizer=processor.tokenizer
    # =====
)

In [ ]:
trainer.train()

In [ ]:
eval_results = trainer.evaluate()

eval_results

In [ ]:
# =====
# FINAL_MODEL_DIR = "./whisper-small-niletts-egyptian-arabic-final"
FINAL_MODEL_DIR = str(ASR_DIR / "whisper-small-niletts-egyptian-arabic-final")
# =====

trainer.save_model(FINAL_MODEL_DIR)
processor.save_pretrained(FINAL_MODEL_DIR)

print("Saved to:", FINAL_MODEL_DIR)

In [ ]:
from transformers import pipeline

device = 0 if torch.cuda.is_available() else -1

asr_pipe = pipeline(
    "automatic-speech-recognition",
    model=FINAL_MODEL_DIR,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    device=device
)

sample_audio = eval_df.loc[0, "audio"]
reference_text = eval_df.loc[0, "text"]

prediction = asr_pipe(sample_audio)

print("Reference:")
print(reference_text)

print("\nPrediction:")
print(prediction["text"])

In [ ]:
predictions = []

for i, row in eval_df.iterrows():
    result = asr_pipe(row["audio"])
    pred_text = result["text"]

    predictions.append({
        "audio_file": row["audio_file"],
        "speaker_name": row["speaker_name"],
        "text": row["text"],
        "asr_transcription_our_finetuned_whisper": pred_text
    })

    if (i + 1) % 50 == 0:
        print(f"Done {i + 1}/{len(eval_df)}")

asr_output_df = pd.DataFrame(predictions)

asr_output_df.head()

In [ ]:
def row_wer(ref, hyp):
    ref = normalize_arabic_for_eval(ref)
    hyp = normalize_arabic_for_eval(hyp)
    return wer_metric.compute(predictions=[hyp], references=[ref])


def row_cer(ref, hyp):
    ref = normalize_arabic_for_eval(ref)
    hyp = normalize_arabic_for_eval(hyp)
    return cer_metric.compute(predictions=[hyp], references=[ref])


asr_output_df["wer_our_finetuned_whisper"] = asr_output_df.apply(
    lambda row: row_wer(
        row["text"],
        row["asr_transcription_our_finetuned_whisper"]
    ),
    axis=1
)

asr_output_df["cer_our_finetuned_whisper"] = asr_output_df.apply(
    lambda row: row_cer(
        row["text"],
        row["asr_transcription_our_finetuned_whisper"]
    ),
    axis=1
)

print("Average WER:", asr_output_df["wer_our_finetuned_whisper"].mean())
print("Average CER:", asr_output_df["cer_our_finetuned_whisper"].mean())

asr_output_df.head()

In [ ]:
# =====
# OUTPUT_CSV = "asr_eval_our_finetuned_whisper_small.csv"
OUTPUT_CSV = (ASR_DIR / "asr_eval_our_finetuned_whisper_small.csv")
# =====

asr_output_df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")

print("Saved:", OUTPUT_CSV)

In [ ]:
missing_files = eval_df[~eval_df["audio_path"].apply(os.path.exists)]
print(f"Missing files: {len(missing_files)}")
print(missing_files[['audio_path']].head())  # Show the first few missing file paths

Missing files: 0
Empty DataFrame
Columns: [audio_path]
Index: []

In [ ]:
import whisper

def transcribe_audio(model_name, audio_path):
    model = whisper.load_model(model_name)
    result = model.transcribe(audio_path)
    return result['text']

In [ ]:
from tqdm import tqdm

# Ensure tqdm is enabled for pandas
tqdm.pandas()
base_model = "base"
# Apply transcription to eval set with progress bar
eval_df['asr_transcription_base'] = eval_df['audio_path'].progress_apply(
    lambda x: transcribe_audio(base_model, x)
)

# Save the transcriptions
# =====
output_file = ASR_DIR / "asr_eval_transcriptions_with_progress.csv"

# eval_df.to_csv("/content/asr_eval_transcriptions_with_progress.csv", index=False)
eval_df.to_csv(output_file, index=False)

# print("Transcriptions saved to /content/asr_eval_transcriptions_with_progress.csv")
print("Saved:", output_file)
# =====

  0%|          | 0/950 [00:00<?, ?it/s]
  0%|                                               | 0.00/139M [00:00<?, ?iB/s]
 17%|██████▋                                | 23.6M/139M [00:00<00:00, 248MiB/s]
 38%|██████████████▉                        | 52.9M/139M [00:00<00:00, 283MiB/s]
 58%|██████████████████████▋                | 80.5M/139M [00:00<00:00, 286MiB/s]
 78%|███████████████████████████████▏        | 108M/139M [00:00<00:00, 266MiB/s]
100%|████████████████████████████████████████| 139M/139M [00:00<00:00, 227MiB/s]
100%|██████████| 950/950 [41:27<00:00,  2.62s/it]

Transcriptions saved to /content/asr_eval_transcriptions_with_progress.csv

In [ ]:
def normalize_arabic(text):
    text = str(text)
    text = re.sub(r"[\u064B-\u065F\u0670]", "", text)  # remove tashkeel
    text = re.sub(r"ـ", "", text)
    text = re.sub(r"[إأآا]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ؤ", "ء", text)
    text = re.sub(r"ئ", "ء", text)
    text = re.sub(r"ة", "ه", text)
    text = re.sub(r"گ", "ك", text)
    text = re.sub(r"[^\w\s\u0600-\u06FF]", " ", text)
    text = re.sub(r"[0-9٠-٩]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Normalize both reference and ASR transcription
eval_df['ref_norm'] = eval_df['text'].apply(normalize_arabic)
eval_df['asr_norm_base'] = eval_df['asr_transcription_base'].apply(normalize_arabic)

In [ ]:
from jiwer import wer, cer

# Compute WER and CER
eval_df['wer_base'] = eval_df.apply(lambda row: wer(row['ref_norm'], row['asr_norm_base']), axis=1)
eval_df['cer_base'] = eval_df.apply(lambda row: cer(row['ref_norm'], row['asr_norm_base']), axis=1)

# Print average WER and CER for Base model
print(f"Base Model - WER: {eval_df['wer_base'].mean()}")
print(f"Base Model - CER: {eval_df['cer_base'].mean()}")

Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.3.3)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 102.0 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, jiwer
Successfully installed jiwer-4.0.0 rapidfuzz-3.14.5
Base Model - WER: 0.5363087785012708
Base Model - CER: 0.17257424279652153

In [ ]:
# Initialize Whisper model (Small)
tqdm.pandas()
small_model = "small"  # Whisper's small model

# Apply transcription to eval set with Small model
eval_df['asr_transcription_small'] = eval_df['audio_path'].progress_apply(lambda x: transcribe_audio(small_model, x))

In [ ]:
# Normalize both reference and ASR transcription for Small model
eval_df['asr_norm_small'] = eval_df['asr_transcription_small'].apply(normalize_arabic)

In [ ]:
# Compute WER and CER for Small model
eval_df['wer_small'] = eval_df.apply(lambda row: wer(row['ref_norm'], row['asr_norm_small']), axis=1)
eval_df['cer_small'] = eval_df.apply(lambda row: cer(row['ref_norm'], row['asr_norm_small']), axis=1)

# Print average WER and CER for Small model
print(f"Small Model - WER: {eval_df['wer_small'].mean()}")
print(f"Small Model - CER: {eval_df['cer_small'].mean()}")

In [ ]:
import torchaudio

# Load a single audio file from your eval dataset
audio_path = eval_df['audio_path'].iloc[0]  # Take the first file
waveform, sample_rate = torchaudio.load(audio_path)

# Check the waveform shape and sample rate
print(f"Waveform Shape: {waveform.shape}")
print(f"Sample Rate: {sample_rate}")

Waveform Shape: torch.Size([2, 440118])
Sample Rate: 44100

In [ ]:
# Resample if necessary (check if sample rate is not 16kHz)
if sample_rate != 16000:
    print(f"Resampling from {sample_rate} Hz to 16kHz")
    waveform = torchaudio.transforms.Resample(sample_rate, 16000)(waveform)
    sample_rate = 16000

# Ensure the waveform is 2D [batch_size, num_frames]
if len(waveform.shape) == 1:
    waveform = waveform.unsqueeze(0)  # Add batch dimension

# Now, waveform is ready for processing by Whisper
print(f"Waveform Shape after resampling: {waveform.shape}")

Resampling from 44100 Hz to 16kHz
Waveform Shape after resampling: torch.Size([2, 159680])

In [ ]:
import torch

# Check if CUDA (GPU) is available
print("CUDA available:", torch.cuda.is_available())
print("Using device:", "GPU" if torch.cuda.is_available() else "CPU")

CUDA available: True
Using device: GPU

In [ ]:
import torchaudio
from transformers import WhisperProcessor, WhisperForConditionalGeneration
import torch
import os
from tqdm import tqdm

# Initialize the fine-tuned Whisper model and processor
fine_tuned_model_name = "MAdel121/whisper-small-egyptian-arabic"  # Fine-tuned model
processor = WhisperProcessor.from_pretrained(fine_tuned_model_name)
model = WhisperForConditionalGeneration.from_pretrained(fine_tuned_model_name)

# Ensure using GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

# Function to load, resample, and transcribe audio using fine-tuned model
def transcribe_finetuned_audio(audio_path):
    # Load audio with torchaudio
    waveform, sample_rate = torchaudio.load(audio_path)

    # Print the shape of the waveform before any processing
    print(f"Original waveform shape: {waveform.shape}")

    # If the sample rate is not 16kHz, resample to 16kHz
    if sample_rate != 16000:
        print(f"Resampling from {sample_rate} Hz to 16kHz")
        waveform = torchaudio.transforms.Resample(sample_rate, 16000)(waveform)
        sample_rate = 16000

    # Convert multi-channel audio to mono if necessary
    # Whisper models expect single-channel audio.
    if waveform.shape[0] > 1: # Check if it's multi-channel (e.g., [2, N])
        print(f"Converting multi-channel audio to mono by averaging channels. Original shape: {waveform.shape}")
        waveform = waveform.mean(dim=0) # Average across channels to get a 1D tensor (N,)

    # Ensure the waveform is a 1D tensor (mono audio samples).
    # The processor expects a 1D tensor for a single audio input.
    if len(waveform.shape) > 1: # If it's (1, N) (e.g., mono with a channel dim), squeeze to (N,)
        waveform = waveform.squeeze()

    print(f"Final waveform shape before processor: {waveform.shape}")

    # Process the audio input with Whisper processor
    # The processor will handle adding a batch dimension if needed.
    audio_input = processor(waveform, return_tensors="pt", sampling_rate=16000).input_features.to(device)

    # Generate transcription
    predicted_ids = model.generate(audio_input)
    transcription = processor.decode(predicted_ids[0], skip_special_tokens=True)

    return transcription

# Test on a single audio file to verify the transcription works

# =====
# test_audio_path = "/content/NileTTS-dataset/wavs/sales_34_00019.wav"  # Replace with your test file
test_audio_path = str(DATASET_DIR / "wavs" / "sales_34_00019.wav")
# =====

print("Transcribing:", test_audio_path)

# Transcribe and print the result
transcription = transcribe_finetuned_audio(test_audio_path)
print("Transcription:", transcription)

preprocessor_config.json:   0%|          | 0.00/371 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

normalizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/967M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

generation_config.json: 0.00B [00:00, ?B/s]

Using custom `forced_decoder_ids` from the (generation) config. This is deprecated in favor of the `task` and `language` flags/config options.
Transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English. This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`. See https://github.com/huggingface/transformers/pull/28687 for more details.

Transcribing: /content/NileTTS-dataset/wavs/sales_34_00019.wav
Original waveform shape: torch.Size([2, 440118])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 159680])
Final waveform shape before processor: torch.Size([159680])

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.

Transcription:  فالشخص الذي هو يعني حفظ مش فاهم ده اللي قافل على نفسه وبعمل حاجة واحدة بس ده ممكن يبقى مشكلة بعدين. الأهم دلوقتي الشخص اللي عنده فضول.

In [ ]:
# Apply transcription to eval dataset with fine-tuned model
tqdm.pandas()
eval_df['asr_transcription_finetuned'] = eval_df['audio_path'].progress_apply(lambda x: transcribe_finetuned_audio(x))

# Save the results

# =====
output_file = ASR_DIR / "asr_eval_finetuned_transcriptions.csv"

# eval_df.to_csv("/content/asr_eval_finetuned_transcriptions.csv", index=False)
eval_df.to_csv(output_file, index=False)

# print("Transcriptions saved to /content/asr_eval_finetuned_transcriptions.csv")
print("Saved:", output_file)
# =====

  0%|          | 0/950 [00:00<?, ?it/s]

Original waveform shape: torch.Size([2, 440118])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 159680])
Final waveform shape before processor: torch.Size([159680])

  0%|          | 2/950 [00:01<10:36,  1.49it/s]

Original waveform shape: torch.Size([2, 667673])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 242240])
Final waveform shape before processor: torch.Size([242240])

  0%|          | 3/950 [00:03<18:03,  1.14s/it]

Original waveform shape: torch.Size([2, 484219])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175681])
Final waveform shape before processor: torch.Size([175681])

  0%|          | 4/950 [00:04<20:57,  1.33s/it]

Original waveform shape: torch.Size([2, 596232])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216320])
Final waveform shape before processor: torch.Size([216320])

  1%|          | 5/950 [00:06<22:06,  1.40s/it]

Original waveform shape: torch.Size([2, 641213])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

  1%|          | 6/950 [00:08<23:37,  1.50s/it]

Original waveform shape: torch.Size([2, 623574])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226240])
Final waveform shape before processor: torch.Size([226240])

  1%|          | 7/950 [00:09<24:21,  1.55s/it]

Original waveform shape: torch.Size([2, 605934])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219840])
Final waveform shape before processor: torch.Size([219840])

  1%|          | 8/950 [00:11<24:24,  1.56s/it]

Original waveform shape: torch.Size([2, 653562])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237120])
Final waveform shape before processor: torch.Size([237120])

  1%|          | 9/950 [00:12<24:57,  1.59s/it]

Original waveform shape: torch.Size([2, 635040])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 230400])
Final waveform shape before processor: torch.Size([230400])

  1%|          | 10/950 [00:14<25:28,  1.63s/it]

Original waveform shape: torch.Size([2, 586531])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212801])
Final waveform shape before processor: torch.Size([212801])

  1%|          | 11/950 [00:15<23:50,  1.52s/it]

Original waveform shape: torch.Size([2, 422478])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 153280])
Final waveform shape before processor: torch.Size([153280])

  1%|▏         | 12/950 [00:17<23:16,  1.49s/it]

Original waveform shape: torch.Size([2, 500976])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 181760])
Final waveform shape before processor: torch.Size([181760])

  1%|▏         | 13/950 [00:19<24:24,  1.56s/it]

Original waveform shape: torch.Size([2, 620046])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224960])
Final waveform shape before processor: torch.Size([224960])

  1%|▏         | 14/950 [00:20<23:57,  1.54s/it]

Original waveform shape: torch.Size([2, 572418])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 207680])
Final waveform shape before processor: torch.Size([207680])

  2%|▏         | 15/950 [00:21<23:22,  1.50s/it]

Original waveform shape: torch.Size([2, 575505])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208800])
Final waveform shape before processor: torch.Size([208800])

  2%|▏         | 16/950 [00:23<22:31,  1.45s/it]

Original waveform shape: torch.Size([2, 566244])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 205440])
Final waveform shape before processor: torch.Size([205440])

  2%|▏         | 17/950 [00:24<19:09,  1.23s/it]

Original waveform shape: torch.Size([2, 276066])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 100160])
Final waveform shape before processor: torch.Size([100160])

  2%|▏         | 18/950 [00:24<17:49,  1.15s/it]

Original waveform shape: torch.Size([2, 733824])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 266240])
Final waveform shape before processor: torch.Size([266240])

  2%|▏         | 19/950 [00:27<22:06,  1.42s/it]

Original waveform shape: torch.Size([2, 724122])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 262720])
Final waveform shape before processor: torch.Size([262720])

  2%|▏         | 20/950 [00:29<25:03,  1.62s/it]

Original waveform shape: torch.Size([2, 660618])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239680])
Final waveform shape before processor: torch.Size([239680])

  2%|▏         | 21/950 [00:31<26:50,  1.73s/it]

Original waveform shape: torch.Size([2, 631071])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 228960])
Final waveform shape before processor: torch.Size([228960])

  2%|▏         | 22/950 [00:32<27:15,  1.76s/it]

Original waveform shape: torch.Size([2, 291872])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 105895])
Final waveform shape before processor: torch.Size([105895])

  2%|▏         | 23/950 [00:33<23:31,  1.52s/it]

Original waveform shape: torch.Size([2, 595350])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216000])
Final waveform shape before processor: torch.Size([216000])

  3%|▎         | 24/950 [00:35<22:41,  1.47s/it]

Original waveform shape: torch.Size([2, 154791])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 56160])
Final waveform shape before processor: torch.Size([56160])

  3%|▎         | 25/950 [00:35<18:42,  1.21s/it]

Original waveform shape: torch.Size([2, 483336])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175360])
Final waveform shape before processor: torch.Size([175360])

  3%|▎         | 26/950 [00:37<18:44,  1.22s/it]

Original waveform shape: torch.Size([2, 484218])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175680])
Final waveform shape before processor: torch.Size([175680])

  3%|▎         | 27/950 [00:38<19:50,  1.29s/it]

Original waveform shape: torch.Size([2, 642978])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233280])
Final waveform shape before processor: torch.Size([233280])

  3%|▎         | 28/950 [00:39<16:03,  1.04s/it]

Original waveform shape: torch.Size([2, 664146])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240960])
Final waveform shape before processor: torch.Size([240960])

  3%|▎         | 29/950 [00:40<18:44,  1.22s/it]

Original waveform shape: torch.Size([2, 575158])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208675])
Final waveform shape before processor: torch.Size([208675])

  3%|▎         | 30/950 [00:41<19:00,  1.24s/it]

Original waveform shape: torch.Size([2, 620047])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224961])
Final waveform shape before processor: torch.Size([224961])

  3%|▎         | 31/950 [00:43<21:23,  1.40s/it]

Original waveform shape: torch.Size([2, 603289])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218881])
Final waveform shape before processor: torch.Size([218881])

  3%|▎         | 32/950 [00:45<23:11,  1.52s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

  3%|▎         | 33/950 [00:46<23:04,  1.51s/it]

Original waveform shape: torch.Size([2, 620046])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224960])
Final waveform shape before processor: torch.Size([224960])

  4%|▎         | 34/950 [00:48<23:35,  1.55s/it]

Original waveform shape: torch.Size([2, 651798])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236480])
Final waveform shape before processor: torch.Size([236480])

  4%|▎         | 35/950 [00:50<24:17,  1.59s/it]

Original waveform shape: torch.Size([2, 474516])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 172160])
Final waveform shape before processor: torch.Size([172160])

  4%|▍         | 36/950 [00:50<19:59,  1.31s/it]

Original waveform shape: torch.Size([2, 631512])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229120])
Final waveform shape before processor: torch.Size([229120])

  4%|▍         | 37/950 [00:52<21:30,  1.41s/it]

Original waveform shape: torch.Size([2, 600642])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 217920])
Final waveform shape before processor: torch.Size([217920])

  4%|▍         | 38/950 [00:54<23:34,  1.55s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

  4%|▍         | 39/950 [00:56<24:53,  1.64s/it]

Original waveform shape: torch.Size([2, 646506])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234560])
Final waveform shape before processor: torch.Size([234560])

  4%|▍         | 40/950 [00:58<25:43,  1.70s/it]

Original waveform shape: torch.Size([2, 591822])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 214720])
Final waveform shape before processor: torch.Size([214720])

  4%|▍         | 41/950 [00:59<24:34,  1.62s/it]

Original waveform shape: torch.Size([2, 1246266])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 452160])
Final waveform shape before processor: torch.Size([452160])

  4%|▍         | 42/950 [01:02<29:53,  1.98s/it]

Original waveform shape: torch.Size([2, 634158])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 230080])
Final waveform shape before processor: torch.Size([230080])

  5%|▍         | 43/950 [01:04<28:27,  1.88s/it]

Original waveform shape: torch.Size([2, 663705])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240800])
Final waveform shape before processor: torch.Size([240800])

  5%|▍         | 44/950 [01:05<28:01,  1.86s/it]

Original waveform shape: torch.Size([2, 618282])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224320])
Final waveform shape before processor: torch.Size([224320])

  5%|▍         | 45/950 [01:07<29:05,  1.93s/it]

Original waveform shape: torch.Size([2, 577710])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209600])
Final waveform shape before processor: torch.Size([209600])

  5%|▍         | 46/950 [01:08<22:04,  1.47s/it]

Original waveform shape: torch.Size([2, 639450])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232000])
Final waveform shape before processor: torch.Size([232000])

  5%|▍         | 47/950 [01:09<22:27,  1.49s/it]

Original waveform shape: torch.Size([2, 926982])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 336320])
Final waveform shape before processor: torch.Size([336320])

  5%|▌         | 48/950 [01:12<25:29,  1.70s/it]

Original waveform shape: torch.Size([2, 582120])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211200])
Final waveform shape before processor: torch.Size([211200])

  5%|▌         | 49/950 [01:13<24:01,  1.60s/it]

Original waveform shape: torch.Size([2, 832608])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 302080])
Final waveform shape before processor: torch.Size([302080])

  5%|▌         | 50/950 [01:15<25:53,  1.73s/it]

Original waveform shape: torch.Size([2, 631513])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229121])
Final waveform shape before processor: torch.Size([229121])

  5%|▌         | 51/950 [01:16<24:43,  1.65s/it]

Original waveform shape: torch.Size([2, 665910])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241600])
Final waveform shape before processor: torch.Size([241600])

  5%|▌         | 52/950 [01:18<26:05,  1.74s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

  6%|▌         | 53/950 [01:20<26:46,  1.79s/it]

Original waveform shape: torch.Size([2, 602406])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218560])
Final waveform shape before processor: torch.Size([218560])

  6%|▌         | 54/950 [01:22<25:30,  1.71s/it]

Original waveform shape: torch.Size([2, 841428])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 305280])
Final waveform shape before processor: torch.Size([305280])

  6%|▌         | 55/950 [01:24<26:35,  1.78s/it]

Original waveform shape: torch.Size([2, 925218])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 335680])
Final waveform shape before processor: torch.Size([335680])

  6%|▌         | 56/950 [01:26<29:39,  1.99s/it]

Original waveform shape: torch.Size([2, 514207])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 186561])
Final waveform shape before processor: torch.Size([186561])

  6%|▌         | 57/950 [01:27<23:02,  1.55s/it]

Original waveform shape: torch.Size([2, 610344])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 221440])
Final waveform shape before processor: torch.Size([221440])

  6%|▌         | 58/950 [01:28<22:57,  1.54s/it]

Original waveform shape: torch.Size([2, 653562])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237120])
Final waveform shape before processor: torch.Size([237120])

  6%|▌         | 59/950 [01:30<22:35,  1.52s/it]

Original waveform shape: torch.Size([2, 510237])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 185120])
Final waveform shape before processor: torch.Size([185120])

  6%|▋         | 60/950 [01:32<23:44,  1.60s/it]

Original waveform shape: torch.Size([2, 642096])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232960])
Final waveform shape before processor: torch.Size([232960])

  6%|▋         | 61/950 [01:33<23:42,  1.60s/it]

Original waveform shape: torch.Size([2, 642096])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232960])
Final waveform shape before processor: torch.Size([232960])

  7%|▋         | 62/950 [01:35<24:17,  1.64s/it]

Original waveform shape: torch.Size([2, 489510])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 177600])
Final waveform shape before processor: torch.Size([177600])

  7%|▋         | 63/950 [01:36<23:45,  1.61s/it]

Original waveform shape: torch.Size([2, 388521])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 140960])
Final waveform shape before processor: torch.Size([140960])

  7%|▋         | 64/950 [01:37<21:08,  1.43s/it]

Original waveform shape: torch.Size([2, 568008])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206080])
Final waveform shape before processor: torch.Size([206080])

  7%|▋         | 65/950 [01:39<20:27,  1.39s/it]

Original waveform shape: torch.Size([2, 516852])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 187520])
Final waveform shape before processor: torch.Size([187520])

  7%|▋         | 66/950 [01:40<20:59,  1.42s/it]

Original waveform shape: torch.Size([2, 1062368])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 385440])
Final waveform shape before processor: torch.Size([385440])

  7%|▋         | 67/950 [01:43<28:16,  1.92s/it]

Original waveform shape: torch.Size([2, 480690])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 174400])
Final waveform shape before processor: torch.Size([174400])

  7%|▋         | 68/950 [01:45<26:58,  1.84s/it]

Original waveform shape: torch.Size([2, 842751])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 305760])
Final waveform shape before processor: torch.Size([305760])

  7%|▋         | 69/950 [01:47<29:48,  2.03s/it]

Original waveform shape: torch.Size([2, 643860])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233600])
Final waveform shape before processor: torch.Size([233600])

  7%|▋         | 70/950 [01:49<27:21,  1.87s/it]

Original waveform shape: torch.Size([2, 649152])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235520])
Final waveform shape before processor: torch.Size([235520])

  7%|▋         | 71/950 [01:51<26:53,  1.84s/it]

Original waveform shape: torch.Size([2, 369558])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 134080])
Final waveform shape before processor: torch.Size([134080])

  8%|▊         | 72/950 [01:52<23:49,  1.63s/it]

Original waveform shape: torch.Size([2, 920808])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 334080])
Final waveform shape before processor: torch.Size([334080])

  8%|▊         | 73/950 [01:54<26:41,  1.83s/it]

Original waveform shape: torch.Size([2, 494802])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 179520])
Final waveform shape before processor: torch.Size([179520])

  8%|▊         | 74/950 [01:56<26:44,  1.83s/it]

Original waveform shape: torch.Size([2, 1181439])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 428640])
Final waveform shape before processor: torch.Size([428640])

  8%|▊         | 75/950 [01:59<30:13,  2.07s/it]

Original waveform shape: torch.Size([2, 569771])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206720])
Final waveform shape before processor: torch.Size([206720])

  8%|▊         | 76/950 [02:00<27:11,  1.87s/it]

Original waveform shape: torch.Size([2, 518175])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 188000])
Final waveform shape before processor: torch.Size([188000])

  8%|▊         | 77/950 [02:01<25:30,  1.75s/it]

Original waveform shape: torch.Size([2, 662381])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240320])
Final waveform shape before processor: torch.Size([240320])

  8%|▊         | 78/950 [02:03<24:31,  1.69s/it]

Original waveform shape: torch.Size([2, 582120])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211200])
Final waveform shape before processor: torch.Size([211200])

  8%|▊         | 79/950 [02:04<23:27,  1.62s/it]

Original waveform shape: torch.Size([2, 614754])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223040])
Final waveform shape before processor: torch.Size([223040])

  8%|▊         | 80/950 [02:06<24:10,  1.67s/it]

Original waveform shape: torch.Size([2, 424242])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 153920])
Final waveform shape before processor: torch.Size([153920])

  9%|▊         | 81/950 [02:07<20:23,  1.41s/it]

Original waveform shape: torch.Size([2, 952560])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 345600])
Final waveform shape before processor: torch.Size([345600])

  9%|▊         | 82/950 [02:10<25:03,  1.73s/it]

Original waveform shape: torch.Size([2, 532728])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 193280])
Final waveform shape before processor: torch.Size([193280])

  9%|▊         | 83/950 [02:11<23:49,  1.65s/it]

Original waveform shape: torch.Size([2, 352800])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 128000])
Final waveform shape before processor: torch.Size([128000])

  9%|▉         | 84/950 [02:11<18:19,  1.27s/it]

Original waveform shape: torch.Size([2, 659736])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239360])
Final waveform shape before processor: torch.Size([239360])

  9%|▉         | 85/950 [02:13<20:00,  1.39s/it]

Original waveform shape: torch.Size([2, 637686])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231360])
Final waveform shape before processor: torch.Size([231360])

  9%|▉         | 86/950 [02:15<20:36,  1.43s/it]

Original waveform shape: torch.Size([2, 477162])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 173120])
Final waveform shape before processor: torch.Size([173120])

  9%|▉         | 87/950 [02:15<17:13,  1.20s/it]

Original waveform shape: torch.Size([2, 417186])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 151360])
Final waveform shape before processor: torch.Size([151360])

  9%|▉         | 88/950 [02:16<17:09,  1.19s/it]

Original waveform shape: torch.Size([2, 1050462])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 381120])
Final waveform shape before processor: torch.Size([381120])

  9%|▉         | 89/950 [02:19<24:36,  1.71s/it]

Original waveform shape: torch.Size([2, 484219])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175681])
Final waveform shape before processor: torch.Size([175681])

  9%|▉         | 90/950 [02:21<23:20,  1.63s/it]

Original waveform shape: torch.Size([2, 650033])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235840])
Final waveform shape before processor: torch.Size([235840])

 10%|▉         | 91/950 [02:22<23:36,  1.65s/it]

Original waveform shape: torch.Size([2, 627102])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227520])
Final waveform shape before processor: torch.Size([227520])

 10%|▉         | 92/950 [02:24<23:14,  1.63s/it]

Original waveform shape: torch.Size([2, 644742])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233920])
Final waveform shape before processor: torch.Size([233920])

 10%|▉         | 93/950 [02:26<24:12,  1.69s/it]

Original waveform shape: torch.Size([2, 454230])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 164800])
Final waveform shape before processor: torch.Size([164800])

 10%|▉         | 94/950 [02:27<22:37,  1.59s/it]

Original waveform shape: torch.Size([2, 582120])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211200])
Final waveform shape before processor: torch.Size([211200])

 10%|█         | 95/950 [02:29<22:13,  1.56s/it]

Original waveform shape: torch.Size([2, 503622])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 182720])
Final waveform shape before processor: torch.Size([182720])

 10%|█         | 96/950 [02:30<20:50,  1.46s/it]

Original waveform shape: torch.Size([2, 656208])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 238080])
Final waveform shape before processor: torch.Size([238080])

 10%|█         | 97/950 [02:32<22:45,  1.60s/it]

Original waveform shape: torch.Size([2, 445409])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 161600])
Final waveform shape before processor: torch.Size([161600])

 10%|█         | 98/950 [02:33<21:35,  1.52s/it]

Original waveform shape: torch.Size([2, 532728])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 193280])
Final waveform shape before processor: torch.Size([193280])

 10%|█         | 99/950 [02:34<20:10,  1.42s/it]

Original waveform shape: torch.Size([2, 521262])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 189120])
Final waveform shape before processor: torch.Size([189120])

 11%|█         | 100/950 [02:36<19:57,  1.41s/it]

Original waveform shape: torch.Size([2, 449820])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 163200])
Final waveform shape before processor: torch.Size([163200])

 11%|█         | 101/950 [02:37<19:40,  1.39s/it]

Original waveform shape: torch.Size([2, 547722])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 198720])
Final waveform shape before processor: torch.Size([198720])

 11%|█         | 102/950 [02:39<20:28,  1.45s/it]

Original waveform shape: torch.Size([2, 618283])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224321])
Final waveform shape before processor: torch.Size([224321])

 11%|█         | 103/950 [02:40<20:46,  1.47s/it]

Original waveform shape: torch.Size([2, 532728])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 193280])
Final waveform shape before processor: torch.Size([193280])

 11%|█         | 104/950 [02:42<20:37,  1.46s/it]

Original waveform shape: torch.Size([2, 618282])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224320])
Final waveform shape before processor: torch.Size([224320])

 11%|█         | 105/950 [02:43<20:24,  1.45s/it]

Original waveform shape: torch.Size([2, 454230])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 164800])
Final waveform shape before processor: torch.Size([164800])

 11%|█         | 106/950 [02:45<21:35,  1.53s/it]

Original waveform shape: torch.Size([2, 623574])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226240])
Final waveform shape before processor: torch.Size([226240])

 11%|█▏        | 107/950 [02:46<18:00,  1.28s/it]

Original waveform shape: torch.Size([2, 648270])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235200])
Final waveform shape before processor: torch.Size([235200])

 11%|█▏        | 108/950 [02:47<18:52,  1.34s/it]

Original waveform shape: torch.Size([2, 531846])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 192960])
Final waveform shape before processor: torch.Size([192960])

 11%|█▏        | 109/950 [02:49<19:40,  1.40s/it]

Original waveform shape: torch.Size([2, 488628])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 177280])
Final waveform shape before processor: torch.Size([177280])

 12%|█▏        | 110/950 [02:50<19:24,  1.39s/it]

Original waveform shape: torch.Size([2, 534492])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 193920])
Final waveform shape before processor: torch.Size([193920])

 12%|█▏        | 111/950 [02:51<19:30,  1.40s/it]

Original waveform shape: torch.Size([2, 655326])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237760])
Final waveform shape before processor: torch.Size([237760])

 12%|█▏        | 112/950 [02:53<20:31,  1.47s/it]

Original waveform shape: torch.Size([2, 579474])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 210240])
Final waveform shape before processor: torch.Size([210240])

 12%|█▏        | 113/950 [02:54<19:45,  1.42s/it]

Original waveform shape: torch.Size([2, 645624])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234240])
Final waveform shape before processor: torch.Size([234240])

 12%|█▏        | 114/950 [02:56<22:57,  1.65s/it]

Original waveform shape: torch.Size([2, 648270])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235200])
Final waveform shape before processor: torch.Size([235200])

 12%|█▏        | 115/950 [02:58<24:04,  1.73s/it]

Original waveform shape: torch.Size([2, 578591])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209920])
Final waveform shape before processor: torch.Size([209920])

 12%|█▏        | 116/950 [03:00<23:12,  1.67s/it]

Original waveform shape: torch.Size([2, 663705])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240800])
Final waveform shape before processor: torch.Size([240800])

 12%|█▏        | 117/950 [03:02<23:58,  1.73s/it]

Original waveform shape: torch.Size([2, 592704])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215040])
Final waveform shape before processor: torch.Size([215040])

 12%|█▏        | 118/950 [03:03<22:31,  1.62s/it]

Original waveform shape: torch.Size([2, 563598])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 204480])
Final waveform shape before processor: torch.Size([204480])

 13%|█▎        | 119/950 [03:05<22:50,  1.65s/it]

Original waveform shape: torch.Size([2, 759843])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 275680])
Final waveform shape before processor: torch.Size([275680])

 13%|█▎        | 120/950 [03:07<23:18,  1.68s/it]

Original waveform shape: torch.Size([2, 643860])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233600])
Final waveform shape before processor: torch.Size([233600])

 13%|█▎        | 121/950 [03:09<25:01,  1.81s/it]

Original waveform shape: torch.Size([2, 611226])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 221760])
Final waveform shape before processor: torch.Size([221760])

 13%|█▎        | 122/950 [03:10<22:40,  1.64s/it]

Original waveform shape: torch.Size([2, 637686])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231360])
Final waveform shape before processor: torch.Size([231360])

 13%|█▎        | 123/950 [03:11<18:12,  1.32s/it]

Original waveform shape: torch.Size([2, 553014])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 200640])
Final waveform shape before processor: torch.Size([200640])

 13%|█▎        | 124/950 [03:12<18:20,  1.33s/it]

Original waveform shape: torch.Size([2, 560070])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 203200])
Final waveform shape before processor: torch.Size([203200])

 13%|█▎        | 125/950 [03:13<18:38,  1.36s/it]

Original waveform shape: torch.Size([2, 632394])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229440])
Final waveform shape before processor: torch.Size([229440])

 13%|█▎        | 126/950 [03:15<19:46,  1.44s/it]

Original waveform shape: torch.Size([2, 470988])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 170880])
Final waveform shape before processor: torch.Size([170880])

 13%|█▎        | 127/950 [03:16<19:05,  1.39s/it]

Original waveform shape: torch.Size([2, 665028])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241280])
Final waveform shape before processor: torch.Size([241280])

 13%|█▎        | 128/950 [03:18<19:37,  1.43s/it]

Original waveform shape: torch.Size([2, 604170])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219200])
Final waveform shape before processor: torch.Size([219200])

 14%|█▎        | 129/950 [03:19<18:33,  1.36s/it]

Original waveform shape: torch.Size([2, 672966])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 244160])
Final waveform shape before processor: torch.Size([244160])

 14%|█▎        | 130/950 [03:21<22:03,  1.61s/it]

Original waveform shape: torch.Size([2, 683550])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 248000])
Final waveform shape before processor: torch.Size([248000])

 14%|█▍        | 131/950 [03:23<22:21,  1.64s/it]

Original waveform shape: torch.Size([2, 1339316])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 485920])
Final waveform shape before processor: torch.Size([485920])

 14%|█▍        | 132/950 [03:26<28:05,  2.06s/it]

Original waveform shape: torch.Size([2, 663264])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240640])
Final waveform shape before processor: torch.Size([240640])

 14%|█▍        | 133/950 [03:28<26:21,  1.94s/it]

Original waveform shape: torch.Size([2, 638569])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231681])
Final waveform shape before processor: torch.Size([231681])

 14%|█▍        | 134/950 [03:29<24:10,  1.78s/it]

Original waveform shape: torch.Size([2, 897876])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 325760])
Final waveform shape before processor: torch.Size([325760])

 14%|█▍        | 135/950 [03:31<25:11,  1.85s/it]

Original waveform shape: torch.Size([2, 756756])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 274560])
Final waveform shape before processor: torch.Size([274560])

 14%|█▍        | 136/950 [03:33<27:08,  2.00s/it]

Original waveform shape: torch.Size([2, 596233])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216321])
Final waveform shape before processor: torch.Size([216321])

 14%|█▍        | 137/950 [03:35<25:30,  1.88s/it]

Original waveform shape: torch.Size([2, 663264])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240640])
Final waveform shape before processor: torch.Size([240640])

 15%|█▍        | 138/950 [03:37<25:05,  1.85s/it]

Original waveform shape: torch.Size([2, 515088])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 186880])
Final waveform shape before processor: torch.Size([186880])

 15%|█▍        | 139/950 [03:38<23:49,  1.76s/it]

Original waveform shape: torch.Size([2, 641214])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

 15%|█▍        | 140/950 [03:40<22:51,  1.69s/it]

Original waveform shape: torch.Size([2, 665469])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241440])
Final waveform shape before processor: torch.Size([241440])

 15%|█▍        | 141/950 [03:41<22:40,  1.68s/it]

Original waveform shape: torch.Size([2, 706923])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 256480])
Final waveform shape before processor: torch.Size([256480])

 15%|█▍        | 142/950 [03:42<18:10,  1.35s/it]

Original waveform shape: torch.Size([2, 523026])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 189760])
Final waveform shape before processor: torch.Size([189760])

 15%|█▌        | 143/950 [03:44<18:46,  1.40s/it]

Original waveform shape: torch.Size([2, 611226])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 221760])
Final waveform shape before processor: torch.Size([221760])

 15%|█▌        | 144/950 [03:45<20:32,  1.53s/it]

Original waveform shape: torch.Size([2, 855540])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 310400])
Final waveform shape before processor: torch.Size([310400])

 15%|█▌        | 145/950 [03:47<20:10,  1.50s/it]

Original waveform shape: torch.Size([2, 578592])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209920])
Final waveform shape before processor: torch.Size([209920])

 15%|█▌        | 146/950 [03:48<20:01,  1.49s/it]

Original waveform shape: torch.Size([2, 616518])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223680])
Final waveform shape before processor: torch.Size([223680])

 15%|█▌        | 147/950 [03:50<20:22,  1.52s/it]

Original waveform shape: torch.Size([2, 597114])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216640])
Final waveform shape before processor: torch.Size([216640])

 16%|█▌        | 148/950 [03:52<21:04,  1.58s/it]

Original waveform shape: torch.Size([2, 645624])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234240])
Final waveform shape before processor: torch.Size([234240])

 16%|█▌        | 149/950 [03:53<21:06,  1.58s/it]

Original waveform shape: torch.Size([2, 447174])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 162240])
Final waveform shape before processor: torch.Size([162240])

 16%|█▌        | 150/950 [03:55<20:05,  1.51s/it]

Original waveform shape: torch.Size([2, 443205])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 160800])
Final waveform shape before processor: torch.Size([160800])

 16%|█▌        | 151/950 [03:56<18:54,  1.42s/it]

Original waveform shape: torch.Size([2, 500093])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 181440])
Final waveform shape before processor: torch.Size([181440])

 16%|█▌        | 152/950 [03:57<17:27,  1.31s/it]

Original waveform shape: torch.Size([2, 591822])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 214720])
Final waveform shape before processor: torch.Size([214720])

 16%|█▌        | 153/950 [03:58<18:36,  1.40s/it]

Original waveform shape: torch.Size([2, 375732])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 136320])
Final waveform shape before processor: torch.Size([136320])

 16%|█▌        | 154/950 [04:00<17:34,  1.32s/it]

Original waveform shape: torch.Size([2, 603288])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218880])
Final waveform shape before processor: torch.Size([218880])

 16%|█▋        | 155/950 [04:01<19:09,  1.45s/it]

Original waveform shape: torch.Size([2, 806589])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 292640])
Final waveform shape before processor: torch.Size([292640])

 16%|█▋        | 156/950 [04:02<15:50,  1.20s/it]

Original waveform shape: torch.Size([2, 595350])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216000])
Final waveform shape before processor: torch.Size([216000])

 17%|█▋        | 157/950 [04:04<18:35,  1.41s/it]

Original waveform shape: torch.Size([2, 533169])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 193440])
Final waveform shape before processor: torch.Size([193440])

 17%|█▋        | 158/950 [04:05<18:07,  1.37s/it]

Original waveform shape: torch.Size([2, 664146])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240960])
Final waveform shape before processor: torch.Size([240960])

 17%|█▋        | 159/950 [04:07<19:33,  1.48s/it]

Original waveform shape: torch.Size([2, 584766])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212160])
Final waveform shape before processor: torch.Size([212160])

 17%|█▋        | 160/950 [04:08<20:12,  1.53s/it]

Original waveform shape: torch.Size([2, 632394])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229440])
Final waveform shape before processor: torch.Size([229440])

 17%|█▋        | 161/950 [04:10<22:08,  1.68s/it]

Original waveform shape: torch.Size([2, 589176])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 213760])
Final waveform shape before processor: torch.Size([213760])

 17%|█▋        | 162/950 [04:12<22:12,  1.69s/it]

Original waveform shape: torch.Size([2, 414540])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 150400])
Final waveform shape before processor: torch.Size([150400])

 17%|█▋        | 163/950 [04:14<20:54,  1.59s/it]

Original waveform shape: torch.Size([2, 601524])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218240])
Final waveform shape before processor: torch.Size([218240])

 17%|█▋        | 164/950 [04:15<21:28,  1.64s/it]

Original waveform shape: torch.Size([2, 523909])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 190081])
Final waveform shape before processor: torch.Size([190081])

 17%|█▋        | 165/950 [04:17<21:39,  1.66s/it]

Original waveform shape: torch.Size([2, 695897])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 252480])
Final waveform shape before processor: torch.Size([252480])

 17%|█▋        | 166/950 [04:18<20:28,  1.57s/it]

Original waveform shape: torch.Size([2, 680022])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 246720])
Final waveform shape before processor: torch.Size([246720])

 18%|█▊        | 167/950 [04:20<21:39,  1.66s/it]

Original waveform shape: torch.Size([2, 364266])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 132160])
Final waveform shape before processor: torch.Size([132160])

 18%|█▊        | 168/950 [04:22<21:27,  1.65s/it]

Original waveform shape: torch.Size([2, 1165562])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 422880])
Final waveform shape before processor: torch.Size([422880])

 18%|█▊        | 169/950 [04:25<26:56,  2.07s/it]

Original waveform shape: torch.Size([2, 569771])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206720])
Final waveform shape before processor: torch.Size([206720])

 18%|█▊        | 170/950 [04:26<24:28,  1.88s/it]

Original waveform shape: torch.Size([2, 419391])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 152160])
Final waveform shape before processor: torch.Size([152160])

 18%|█▊        | 171/950 [04:28<22:06,  1.70s/it]

Original waveform shape: torch.Size([2, 698544])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 253440])
Final waveform shape before processor: torch.Size([253440])

 18%|█▊        | 172/950 [04:29<21:58,  1.69s/it]

Original waveform shape: torch.Size([2, 579475])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 210241])
Final waveform shape before processor: torch.Size([210241])

 18%|█▊        | 173/950 [04:31<21:39,  1.67s/it]

Original waveform shape: torch.Size([2, 583002])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211520])
Final waveform shape before processor: torch.Size([211520])

 18%|█▊        | 174/950 [04:32<20:37,  1.59s/it]

Original waveform shape: torch.Size([2, 621810])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 225600])
Final waveform shape before processor: torch.Size([225600])

 18%|█▊        | 175/950 [04:34<22:21,  1.73s/it]

Original waveform shape: torch.Size([2, 558306])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 202560])
Final waveform shape before processor: torch.Size([202560])

 19%|█▊        | 176/950 [04:36<22:10,  1.72s/it]

Original waveform shape: torch.Size([2, 707364])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 256640])
Final waveform shape before processor: torch.Size([256640])

 19%|█▊        | 177/950 [04:38<22:26,  1.74s/it]

Original waveform shape: torch.Size([2, 926541])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 336160])
Final waveform shape before processor: torch.Size([336160])

 19%|█▊        | 178/950 [04:40<24:25,  1.90s/it]

Original waveform shape: torch.Size([2, 695016])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 252160])
Final waveform shape before processor: torch.Size([252160])

 19%|█▉        | 179/950 [04:42<24:24,  1.90s/it]

Original waveform shape: torch.Size([2, 890379])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 323040])
Final waveform shape before processor: torch.Size([323040])

 19%|█▉        | 180/950 [04:44<25:55,  2.02s/it]

Original waveform shape: torch.Size([2, 588294])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 213440])
Final waveform shape before processor: torch.Size([213440])

 19%|█▉        | 181/950 [04:47<26:38,  2.08s/it]

Original waveform shape: torch.Size([2, 633275])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229760])
Final waveform shape before processor: torch.Size([229760])

 19%|█▉        | 182/950 [04:48<24:51,  1.94s/it]

Original waveform shape: torch.Size([2, 665910])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241600])
Final waveform shape before processor: torch.Size([241600])

 19%|█▉        | 183/950 [04:49<22:08,  1.73s/it]

Original waveform shape: torch.Size([2, 919926])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 333760])
Final waveform shape before processor: torch.Size([333760])

 19%|█▉        | 184/950 [04:52<23:47,  1.86s/it]

Original waveform shape: torch.Size([2, 415422])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 150720])
Final waveform shape before processor: torch.Size([150720])

 19%|█▉        | 185/950 [04:53<21:28,  1.68s/it]

Original waveform shape: torch.Size([2, 500976])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 181760])
Final waveform shape before processor: torch.Size([181760])

 20%|█▉        | 186/950 [04:54<19:37,  1.54s/it]

Original waveform shape: torch.Size([2, 652680])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236800])
Final waveform shape before processor: torch.Size([236800])

 20%|█▉        | 187/950 [04:56<19:46,  1.55s/it]

Original waveform shape: torch.Size([2, 749700])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 272000])
Final waveform shape before processor: torch.Size([272000])

 20%|█▉        | 188/950 [04:58<21:50,  1.72s/it]

Original waveform shape: torch.Size([2, 819379])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 297281])
Final waveform shape before processor: torch.Size([297281])

 20%|█▉        | 189/950 [05:00<24:20,  1.92s/it]

Original waveform shape: torch.Size([2, 485100])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 176000])
Final waveform shape before processor: torch.Size([176000])

 20%|██        | 190/950 [05:02<22:38,  1.79s/it]

Original waveform shape: torch.Size([2, 859509])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 311840])
Final waveform shape before processor: torch.Size([311840])

 20%|██        | 191/950 [05:04<24:07,  1.91s/it]

Original waveform shape: torch.Size([2, 485100])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 176000])
Final waveform shape before processor: torch.Size([176000])

 20%|██        | 192/950 [05:05<22:19,  1.77s/it]

Original waveform shape: torch.Size([2, 755874])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 274240])
Final waveform shape before processor: torch.Size([274240])

 20%|██        | 193/950 [05:07<23:40,  1.88s/it]

Original waveform shape: torch.Size([2, 20727])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 7520])
Final waveform shape before processor: torch.Size([7520])

 20%|██        | 194/950 [05:08<17:54,  1.42s/it]

Original waveform shape: torch.Size([2, 665029])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241281])
Final waveform shape before processor: torch.Size([241281])

 21%|██        | 195/950 [05:10<19:11,  1.53s/it]

Original waveform shape: torch.Size([2, 651798])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236480])
Final waveform shape before processor: torch.Size([236480])

 21%|██        | 196/950 [05:12<21:53,  1.74s/it]

Original waveform shape: torch.Size([2, 776160])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 281600])
Final waveform shape before processor: torch.Size([281600])

 21%|██        | 197/950 [05:14<22:16,  1.78s/it]

Original waveform shape: torch.Size([2, 391608])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 142080])
Final waveform shape before processor: torch.Size([142080])

 21%|██        | 198/950 [05:15<19:53,  1.59s/it]

Original waveform shape: torch.Size([2, 429534])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 155840])
Final waveform shape before processor: torch.Size([155840])

 21%|██        | 199/950 [05:15<16:02,  1.28s/it]

Original waveform shape: torch.Size([2, 289296])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 104960])
Final waveform shape before processor: torch.Size([104960])

 21%|██        | 200/950 [05:22<36:09,  2.89s/it]

Original waveform shape: torch.Size([2, 607698])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220480])
Final waveform shape before processor: torch.Size([220480])

 21%|██        | 201/950 [05:24<32:31,  2.60s/it]

Original waveform shape: torch.Size([2, 645624])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234240])
Final waveform shape before processor: torch.Size([234240])

 21%|██▏       | 202/950 [05:26<28:39,  2.30s/it]

Original waveform shape: torch.Size([2, 600642])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 217920])
Final waveform shape before processor: torch.Size([217920])

 21%|██▏       | 203/950 [05:27<25:47,  2.07s/it]

Original waveform shape: torch.Size([2, 1162917])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 421920])
Final waveform shape before processor: torch.Size([421920])

 21%|██▏       | 204/950 [05:30<28:22,  2.28s/it]

Original waveform shape: torch.Size([2, 584766])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212160])
Final waveform shape before processor: torch.Size([212160])

 22%|██▏       | 205/950 [05:31<23:58,  1.93s/it]

Original waveform shape: torch.Size([2, 582120])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211200])
Final waveform shape before processor: torch.Size([211200])

 22%|██▏       | 206/950 [05:32<22:05,  1.78s/it]

Original waveform shape: torch.Size([2, 674290])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 244641])
Final waveform shape before processor: torch.Size([244641])

 22%|██▏       | 207/950 [05:34<23:06,  1.87s/it]

Original waveform shape: torch.Size([2, 664146])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240960])
Final waveform shape before processor: torch.Size([240960])

 22%|██▏       | 208/950 [05:36<23:03,  1.86s/it]

Original waveform shape: torch.Size([2, 574182])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208320])
Final waveform shape before processor: torch.Size([208320])

 22%|██▏       | 209/950 [05:38<21:51,  1.77s/it]

Original waveform shape: torch.Size([2, 646506])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234560])
Final waveform shape before processor: torch.Size([234560])

 22%|██▏       | 210/950 [05:40<21:29,  1.74s/it]

Original waveform shape: torch.Size([2, 595350])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216000])
Final waveform shape before processor: torch.Size([216000])

 22%|██▏       | 211/950 [05:41<20:46,  1.69s/it]

Original waveform shape: torch.Size([2, 590941])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 214401])
Final waveform shape before processor: torch.Size([214401])

 22%|██▏       | 212/950 [05:43<19:58,  1.62s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

 22%|██▏       | 213/950 [05:44<20:04,  1.63s/it]

Original waveform shape: torch.Size([2, 623574])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226240])
Final waveform shape before processor: torch.Size([226240])

 23%|██▎       | 214/950 [05:46<20:54,  1.70s/it]

Original waveform shape: torch.Size([2, 435708])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 158080])
Final waveform shape before processor: torch.Size([158080])

 23%|██▎       | 215/950 [05:48<21:05,  1.72s/it]

Original waveform shape: torch.Size([2, 614754])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223040])
Final waveform shape before processor: torch.Size([223040])

 23%|██▎       | 216/950 [05:50<21:20,  1.74s/it]

Original waveform shape: torch.Size([2, 473634])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 171840])
Final waveform shape before processor: torch.Size([171840])

 23%|██▎       | 217/950 [05:51<19:58,  1.63s/it]

Original waveform shape: torch.Size([2, 646506])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234560])
Final waveform shape before processor: torch.Size([234560])

 23%|██▎       | 218/950 [05:53<19:37,  1.61s/it]

Original waveform shape: torch.Size([2, 633277])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229761])
Final waveform shape before processor: torch.Size([229761])

 23%|██▎       | 219/950 [05:54<19:28,  1.60s/it]

Original waveform shape: torch.Size([2, 652680])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236800])
Final waveform shape before processor: torch.Size([236800])

 23%|██▎       | 220/950 [05:56<19:25,  1.60s/it]

Original waveform shape: torch.Size([2, 613872])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222720])
Final waveform shape before processor: torch.Size([222720])

 23%|██▎       | 221/950 [05:57<19:55,  1.64s/it]

Original waveform shape: torch.Size([2, 568890])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206400])
Final waveform shape before processor: torch.Size([206400])

 23%|██▎       | 222/950 [05:58<16:20,  1.35s/it]

Original waveform shape: torch.Size([2, 625338])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226880])
Final waveform shape before processor: torch.Size([226880])

 23%|██▎       | 223/950 [06:00<18:25,  1.52s/it]

Original waveform shape: torch.Size([2, 408365])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 148160])
Final waveform shape before processor: torch.Size([148160])

 24%|██▎       | 224/950 [06:00<14:12,  1.17s/it]

Original waveform shape: torch.Size([2, 621810])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 225600])
Final waveform shape before processor: torch.Size([225600])

 24%|██▎       | 225/950 [06:02<16:22,  1.36s/it]

Original waveform shape: torch.Size([2, 945945])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 343200])
Final waveform shape before processor: torch.Size([343200])

 24%|██▍       | 226/950 [06:05<20:21,  1.69s/it]

Original waveform shape: torch.Size([2, 553896])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 200960])
Final waveform shape before processor: torch.Size([200960])

 24%|██▍       | 227/950 [06:06<18:59,  1.58s/it]

Original waveform shape: torch.Size([2, 644742])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233920])
Final waveform shape before processor: torch.Size([233920])

 24%|██▍       | 228/950 [06:08<19:05,  1.59s/it]

Original waveform shape: torch.Size([2, 511560])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 185600])
Final waveform shape before processor: torch.Size([185600])

 24%|██▍       | 229/950 [06:09<18:42,  1.56s/it]

Original waveform shape: torch.Size([2, 612990])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222400])
Final waveform shape before processor: torch.Size([222400])

 24%|██▍       | 230/950 [06:11<19:05,  1.59s/it]

Original waveform shape: torch.Size([2, 632394])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229440])
Final waveform shape before processor: torch.Size([229440])

 24%|██▍       | 231/950 [06:13<20:44,  1.73s/it]

Original waveform shape: torch.Size([2, 536256])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 194560])
Final waveform shape before processor: torch.Size([194560])

 24%|██▍       | 232/950 [06:14<18:38,  1.56s/it]

Original waveform shape: torch.Size([2, 639450])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232000])
Final waveform shape before processor: torch.Size([232000])

 25%|██▍       | 233/950 [06:15<16:32,  1.38s/it]

Original waveform shape: torch.Size([2, 718830])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 260800])
Final waveform shape before processor: torch.Size([260800])

 25%|██▍       | 234/950 [06:17<17:26,  1.46s/it]

Original waveform shape: torch.Size([2, 500976])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 181760])
Final waveform shape before processor: torch.Size([181760])

 25%|██▍       | 235/950 [06:18<16:49,  1.41s/it]

Original waveform shape: torch.Size([2, 563157])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 204320])
Final waveform shape before processor: torch.Size([204320])

 25%|██▍       | 236/950 [06:20<17:34,  1.48s/it]

Original waveform shape: torch.Size([2, 662382])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240320])
Final waveform shape before processor: torch.Size([240320])

 25%|██▍       | 237/950 [06:21<18:35,  1.56s/it]

Original waveform shape: torch.Size([2, 638568])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231680])
Final waveform shape before processor: torch.Size([231680])

 25%|██▌       | 238/950 [06:23<20:02,  1.69s/it]

Original waveform shape: torch.Size([2, 955206])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 346560])
Final waveform shape before processor: torch.Size([346560])

 25%|██▌       | 239/950 [06:26<23:28,  1.98s/it]

Original waveform shape: torch.Size([2, 656649])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 238240])
Final waveform shape before processor: torch.Size([238240])

 25%|██▌       | 240/950 [06:28<22:58,  1.94s/it]

Original waveform shape: torch.Size([2, 558306])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 202560])
Final waveform shape before processor: torch.Size([202560])

 25%|██▌       | 241/950 [06:29<21:20,  1.81s/it]

Original waveform shape: torch.Size([2, 1910853])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 693280])
Final waveform shape before processor: torch.Size([693280])

 25%|██▌       | 242/950 [06:31<20:24,  1.73s/it]

Original waveform shape: torch.Size([2, 472752])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 171520])
Final waveform shape before processor: torch.Size([171520])

 26%|██▌       | 243/950 [06:32<19:14,  1.63s/it]

Original waveform shape: torch.Size([2, 642097])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232961])
Final waveform shape before processor: torch.Size([232961])

 26%|██▌       | 244/950 [06:34<18:56,  1.61s/it]

Original waveform shape: torch.Size([2, 538902])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 195520])
Final waveform shape before processor: torch.Size([195520])

 26%|██▌       | 245/950 [06:35<19:16,  1.64s/it]

Original waveform shape: torch.Size([2, 526554])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 191040])
Final waveform shape before processor: torch.Size([191040])

 26%|██▌       | 246/950 [06:37<18:03,  1.54s/it]

Original waveform shape: torch.Size([2, 592704])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215040])
Final waveform shape before processor: torch.Size([215040])

 26%|██▌       | 247/950 [06:38<18:03,  1.54s/it]

Original waveform shape: torch.Size([2, 627102])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227520])
Final waveform shape before processor: torch.Size([227520])

 26%|██▌       | 248/950 [06:40<18:17,  1.56s/it]

Original waveform shape: torch.Size([2, 613872])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222720])
Final waveform shape before processor: torch.Size([222720])

 26%|██▌       | 249/950 [06:42<18:44,  1.60s/it]

Original waveform shape: torch.Size([2, 515088])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 186880])
Final waveform shape before processor: torch.Size([186880])

 26%|██▋       | 250/950 [06:43<16:55,  1.45s/it]

Original waveform shape: torch.Size([2, 565362])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 205120])
Final waveform shape before processor: torch.Size([205120])

 26%|██▋       | 251/950 [06:44<17:01,  1.46s/it]

Original waveform shape: torch.Size([2, 696780])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 252800])
Final waveform shape before processor: torch.Size([252800])

 27%|██▋       | 252/950 [06:46<17:47,  1.53s/it]

Original waveform shape: torch.Size([2, 1020915])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 370400])
Final waveform shape before processor: torch.Size([370400])

 27%|██▋       | 253/950 [06:49<22:53,  1.97s/it]

Original waveform shape: torch.Size([2, 664146])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240960])
Final waveform shape before processor: torch.Size([240960])

 27%|██▋       | 254/950 [06:51<22:04,  1.90s/it]

Original waveform shape: torch.Size([2, 583003])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211521])
Final waveform shape before processor: torch.Size([211521])

 27%|██▋       | 255/950 [06:52<21:25,  1.85s/it]

Original waveform shape: torch.Size([2, 665028])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241280])
Final waveform shape before processor: torch.Size([241280])

 27%|██▋       | 256/950 [06:54<19:22,  1.67s/it]

Original waveform shape: torch.Size([2, 662382])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240320])
Final waveform shape before processor: torch.Size([240320])

 27%|██▋       | 257/950 [06:55<19:46,  1.71s/it]

Original waveform shape: torch.Size([2, 637686])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231360])
Final waveform shape before processor: torch.Size([231360])

 27%|██▋       | 258/950 [06:57<19:58,  1.73s/it]

Original waveform shape: torch.Size([2, 853776])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 309760])
Final waveform shape before processor: torch.Size([309760])

 27%|██▋       | 259/950 [07:00<22:06,  1.92s/it]

Original waveform shape: torch.Size([2, 523908])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 190080])
Final waveform shape before processor: torch.Size([190080])

 27%|██▋       | 260/950 [07:01<20:58,  1.82s/it]

Original waveform shape: torch.Size([2, 444969])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 161440])
Final waveform shape before processor: torch.Size([161440])

 27%|██▋       | 261/950 [07:03<19:15,  1.68s/it]

Original waveform shape: torch.Size([2, 445410])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 161600])
Final waveform shape before processor: torch.Size([161600])

 28%|██▊       | 262/950 [07:04<17:29,  1.53s/it]

Original waveform shape: torch.Size([2, 563598])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 204480])
Final waveform shape before processor: torch.Size([204480])

 28%|██▊       | 263/950 [07:05<17:24,  1.52s/it]

Original waveform shape: torch.Size([2, 548605])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 199041])
Final waveform shape before processor: torch.Size([199041])

 28%|██▊       | 264/950 [07:07<17:57,  1.57s/it]

Original waveform shape: torch.Size([2, 748377])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 271520])
Final waveform shape before processor: torch.Size([271520])

 28%|██▊       | 265/950 [07:09<18:41,  1.64s/it]

Original waveform shape: torch.Size([2, 601083])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218080])
Final waveform shape before processor: torch.Size([218080])

 28%|██▊       | 266/950 [07:10<17:27,  1.53s/it]

Original waveform shape: torch.Size([2, 620046])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224960])
Final waveform shape before processor: torch.Size([224960])

 28%|██▊       | 267/950 [07:12<17:49,  1.57s/it]

Original waveform shape: torch.Size([2, 671202])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 243520])
Final waveform shape before processor: torch.Size([243520])

 28%|██▊       | 268/950 [07:14<19:54,  1.75s/it]

Original waveform shape: torch.Size([2, 597996])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216960])
Final waveform shape before processor: torch.Size([216960])

 28%|██▊       | 269/950 [07:15<18:52,  1.66s/it]

Original waveform shape: torch.Size([2, 665910])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241600])
Final waveform shape before processor: torch.Size([241600])

 28%|██▊       | 270/950 [07:16<14:35,  1.29s/it]

Original waveform shape: torch.Size([2, 904050])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 328000])
Final waveform shape before processor: torch.Size([328000])

 29%|██▊       | 271/950 [07:18<17:36,  1.56s/it]

Original waveform shape: torch.Size([2, 631512])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229120])
Final waveform shape before processor: torch.Size([229120])

 29%|██▊       | 272/950 [07:20<17:54,  1.58s/it]

Original waveform shape: torch.Size([2, 537137])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 194880])
Final waveform shape before processor: torch.Size([194880])

 29%|██▊       | 273/950 [07:21<17:46,  1.57s/it]

Original waveform shape: torch.Size([2, 594468])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215680])
Final waveform shape before processor: torch.Size([215680])

 29%|██▉       | 274/950 [07:22<17:01,  1.51s/it]

Original waveform shape: torch.Size([2, 603288])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218880])
Final waveform shape before processor: torch.Size([218880])

 29%|██▉       | 275/950 [07:24<18:29,  1.64s/it]

Original waveform shape: torch.Size([2, 533610])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 193600])
Final waveform shape before processor: torch.Size([193600])

 29%|██▉       | 276/950 [07:25<14:36,  1.30s/it]

Original waveform shape: torch.Size([2, 606816])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220160])
Final waveform shape before processor: torch.Size([220160])

 29%|██▉       | 277/950 [07:27<16:10,  1.44s/it]

Original waveform shape: torch.Size([2, 531846])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 192960])
Final waveform shape before processor: torch.Size([192960])

 29%|██▉       | 278/950 [07:28<15:37,  1.39s/it]

Original waveform shape: torch.Size([2, 575946])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208960])
Final waveform shape before processor: torch.Size([208960])

 29%|██▉       | 279/950 [07:29<15:32,  1.39s/it]

Original waveform shape: torch.Size([2, 835254])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 303040])
Final waveform shape before processor: torch.Size([303040])

 29%|██▉       | 280/950 [07:32<18:17,  1.64s/it]

Original waveform shape: torch.Size([2, 666792])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241920])
Final waveform shape before processor: torch.Size([241920])

 30%|██▉       | 281/950 [07:33<18:21,  1.65s/it]

Original waveform shape: torch.Size([2, 575947])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208961])
Final waveform shape before processor: torch.Size([208961])

 30%|██▉       | 282/950 [07:35<18:19,  1.65s/it]

Original waveform shape: torch.Size([2, 624456])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226560])
Final waveform shape before processor: torch.Size([226560])

 30%|██▉       | 283/950 [07:37<18:55,  1.70s/it]

Original waveform shape: torch.Size([2, 605933])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219840])
Final waveform shape before processor: torch.Size([219840])

 30%|██▉       | 284/950 [07:38<19:03,  1.72s/it]

Original waveform shape: torch.Size([2, 845397])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 306720])
Final waveform shape before processor: torch.Size([306720])

 30%|███       | 285/950 [07:40<20:11,  1.82s/it]

Original waveform shape: torch.Size([2, 638568])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231680])
Final waveform shape before processor: torch.Size([231680])

 30%|███       | 286/950 [07:42<20:06,  1.82s/it]

Original waveform shape: torch.Size([2, 583884])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211840])
Final waveform shape before processor: torch.Size([211840])

 30%|███       | 287/950 [07:44<18:54,  1.71s/it]

Original waveform shape: torch.Size([2, 558306])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 202560])
Final waveform shape before processor: torch.Size([202560])

 30%|███       | 288/950 [07:45<17:36,  1.60s/it]

Original waveform shape: torch.Size([2, 711774])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 258240])
Final waveform shape before processor: torch.Size([258240])

 30%|███       | 289/950 [07:47<18:57,  1.72s/it]

Original waveform shape: torch.Size([2, 739998])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 268480])
Final waveform shape before processor: torch.Size([268480])

 31%|███       | 290/950 [07:49<20:06,  1.83s/it]

Original waveform shape: torch.Size([2, 606815])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220160])
Final waveform shape before processor: torch.Size([220160])

 31%|███       | 291/950 [07:51<19:38,  1.79s/it]

Original waveform shape: torch.Size([2, 606816])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220160])
Final waveform shape before processor: torch.Size([220160])

 31%|███       | 292/950 [07:53<19:23,  1.77s/it]

Original waveform shape: torch.Size([2, 388079])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 140800])
Final waveform shape before processor: torch.Size([140800])

 31%|███       | 293/950 [07:54<17:30,  1.60s/it]

Original waveform shape: torch.Size([2, 649152])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235520])
Final waveform shape before processor: torch.Size([235520])

 31%|███       | 294/950 [07:56<17:56,  1.64s/it]

Original waveform shape: torch.Size([2, 644742])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233920])
Final waveform shape before processor: torch.Size([233920])

 31%|███       | 295/950 [07:57<17:56,  1.64s/it]

Original waveform shape: torch.Size([2, 909342])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 329920])
Final waveform shape before processor: torch.Size([329920])

 31%|███       | 296/950 [07:59<19:08,  1.76s/it]

Original waveform shape: torch.Size([2, 622692])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 225920])
Final waveform shape before processor: torch.Size([225920])

 31%|███▏      | 297/950 [08:01<19:55,  1.83s/it]

Original waveform shape: torch.Size([2, 621810])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 225600])
Final waveform shape before processor: torch.Size([225600])

 31%|███▏      | 298/950 [08:03<19:48,  1.82s/it]

Original waveform shape: torch.Size([2, 612990])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222400])
Final waveform shape before processor: torch.Size([222400])

 31%|███▏      | 299/950 [08:04<18:03,  1.66s/it]

Original waveform shape: torch.Size([2, 537137])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 194880])
Final waveform shape before processor: torch.Size([194880])

 32%|███▏      | 300/950 [08:06<17:15,  1.59s/it]

Original waveform shape: torch.Size([2, 538902])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 195520])
Final waveform shape before processor: torch.Size([195520])

 32%|███▏      | 301/950 [08:07<17:16,  1.60s/it]

Original waveform shape: torch.Size([2, 645624])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234240])
Final waveform shape before processor: torch.Size([234240])

 32%|███▏      | 302/950 [08:09<16:55,  1.57s/it]

Original waveform shape: torch.Size([2, 625338])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226880])
Final waveform shape before processor: torch.Size([226880])

 32%|███▏      | 303/950 [08:10<16:35,  1.54s/it]

Original waveform shape: torch.Size([2, 1050903])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 381280])
Final waveform shape before processor: torch.Size([381280])

 32%|███▏      | 304/950 [08:13<20:19,  1.89s/it]

Original waveform shape: torch.Size([2, 566244])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 205440])
Final waveform shape before processor: torch.Size([205440])

 32%|███▏      | 305/950 [08:15<20:20,  1.89s/it]

Original waveform shape: torch.Size([2, 590940])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 214400])
Final waveform shape before processor: torch.Size([214400])

 32%|███▏      | 306/950 [08:17<19:45,  1.84s/it]

Original waveform shape: torch.Size([2, 573300])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208000])
Final waveform shape before processor: torch.Size([208000])

 32%|███▏      | 307/950 [08:18<17:53,  1.67s/it]

Original waveform shape: torch.Size([2, 850689])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 308640])
Final waveform shape before processor: torch.Size([308640])

 32%|███▏      | 308/950 [08:20<20:01,  1.87s/it]

Original waveform shape: torch.Size([2, 639450])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232000])
Final waveform shape before processor: torch.Size([232000])

 33%|███▎      | 309/950 [08:22<19:49,  1.85s/it]

Original waveform shape: torch.Size([2, 447173])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 162240])
Final waveform shape before processor: torch.Size([162240])

 33%|███▎      | 310/950 [08:23<17:20,  1.63s/it]

Original waveform shape: torch.Size([2, 618282])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224320])
Final waveform shape before processor: torch.Size([224320])

 33%|███▎      | 311/950 [08:25<18:28,  1.73s/it]

Original waveform shape: torch.Size([2, 706482])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 256320])
Final waveform shape before processor: torch.Size([256320])

 33%|███▎      | 312/950 [08:27<19:58,  1.88s/it]

Original waveform shape: torch.Size([2, 461285])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 167360])
Final waveform shape before processor: torch.Size([167360])

 33%|███▎      | 313/950 [08:29<18:21,  1.73s/it]

Original waveform shape: torch.Size([2, 636804])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231040])
Final waveform shape before processor: torch.Size([231040])

 33%|███▎      | 314/950 [08:30<16:53,  1.59s/it]

Original waveform shape: torch.Size([2, 459522])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 166720])
Final waveform shape before processor: torch.Size([166720])

 33%|███▎      | 315/950 [08:31<16:06,  1.52s/it]

Original waveform shape: torch.Size([2, 601524])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218240])
Final waveform shape before processor: torch.Size([218240])

 33%|███▎      | 316/950 [08:33<16:02,  1.52s/it]

Original waveform shape: torch.Size([2, 661500])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240000])
Final waveform shape before processor: torch.Size([240000])

 33%|███▎      | 317/950 [08:35<16:25,  1.56s/it]

Original waveform shape: torch.Size([2, 336042])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 121920])
Final waveform shape before processor: torch.Size([121920])

 33%|███▎      | 318/950 [08:36<14:49,  1.41s/it]

Original waveform shape: torch.Size([2, 573300])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208000])
Final waveform shape before processor: torch.Size([208000])

 34%|███▎      | 319/950 [08:37<15:18,  1.46s/it]

Original waveform shape: torch.Size([2, 642095])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232960])
Final waveform shape before processor: torch.Size([232960])

 34%|███▎      | 320/950 [08:39<16:34,  1.58s/it]

Original waveform shape: torch.Size([2, 381024])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 138240])
Final waveform shape before processor: torch.Size([138240])

 34%|███▍      | 321/950 [08:40<15:11,  1.45s/it]

Original waveform shape: torch.Size([2, 977256])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 354560])
Final waveform shape before processor: torch.Size([354560])

 34%|███▍      | 322/950 [08:43<18:07,  1.73s/it]

Original waveform shape: torch.Size([2, 1683297])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 610720])
Final waveform shape before processor: torch.Size([610720])

 34%|███▍      | 323/950 [08:45<21:35,  2.07s/it]

Original waveform shape: torch.Size([2, 551250])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 200000])
Final waveform shape before processor: torch.Size([200000])

 34%|███▍      | 324/950 [08:47<19:51,  1.90s/it]

Original waveform shape: torch.Size([2, 766017])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 277920])
Final waveform shape before processor: torch.Size([277920])

 34%|███▍      | 325/950 [08:49<20:55,  2.01s/it]

Original waveform shape: torch.Size([2, 864801])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 313760])
Final waveform shape before processor: torch.Size([313760])

 34%|███▍      | 326/950 [08:52<22:45,  2.19s/it]

Original waveform shape: torch.Size([2, 642096])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232960])
Final waveform shape before processor: torch.Size([232960])

 34%|███▍      | 327/950 [08:53<20:30,  1.98s/it]

Original waveform shape: torch.Size([2, 555660])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 201600])
Final waveform shape before processor: torch.Size([201600])

 35%|███▍      | 328/950 [08:55<19:34,  1.89s/it]

Original waveform shape: torch.Size([2, 662382])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240320])
Final waveform shape before processor: torch.Size([240320])

 35%|███▍      | 329/950 [08:56<18:29,  1.79s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

 35%|███▍      | 330/950 [08:58<17:25,  1.69s/it]

Original waveform shape: torch.Size([2, 603288])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218880])
Final waveform shape before processor: torch.Size([218880])

 35%|███▍      | 331/950 [08:59<16:51,  1.63s/it]

Original waveform shape: torch.Size([2, 605052])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219520])
Final waveform shape before processor: torch.Size([219520])

 35%|███▍      | 332/950 [09:01<17:43,  1.72s/it]

Original waveform shape: torch.Size([2, 628866])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 228160])
Final waveform shape before processor: torch.Size([228160])

 35%|███▌      | 333/950 [09:03<18:50,  1.83s/it]

Original waveform shape: torch.Size([2, 527435])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 191360])
Final waveform shape before processor: torch.Size([191360])

 35%|███▌      | 334/950 [09:05<17:25,  1.70s/it]

Original waveform shape: torch.Size([2, 569772])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206720])
Final waveform shape before processor: torch.Size([206720])

 35%|███▌      | 335/950 [09:06<16:06,  1.57s/it]

Original waveform shape: torch.Size([2, 480691])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 174401])
Final waveform shape before processor: torch.Size([174401])

 35%|███▌      | 336/950 [09:08<15:49,  1.55s/it]

Original waveform shape: torch.Size([2, 373968])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 135680])
Final waveform shape before processor: torch.Size([135680])

 35%|███▌      | 337/950 [09:09<14:48,  1.45s/it]

Original waveform shape: torch.Size([2, 653562])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237120])
Final waveform shape before processor: torch.Size([237120])

 36%|███▌      | 338/950 [09:10<15:06,  1.48s/it]

Original waveform shape: torch.Size([2, 603289])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218881])
Final waveform shape before processor: torch.Size([218881])

 36%|███▌      | 339/950 [09:12<15:10,  1.49s/it]

Original waveform shape: torch.Size([2, 874062])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 317120])
Final waveform shape before processor: torch.Size([317120])

 36%|███▌      | 340/950 [09:14<17:54,  1.76s/it]

Original waveform shape: torch.Size([2, 612108])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222080])
Final waveform shape before processor: torch.Size([222080])

 36%|███▌      | 341/950 [09:16<17:33,  1.73s/it]

Original waveform shape: torch.Size([2, 636804])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231040])
Final waveform shape before processor: torch.Size([231040])

 36%|███▌      | 342/950 [09:17<16:42,  1.65s/it]

Original waveform shape: torch.Size([2, 681787])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 247361])
Final waveform shape before processor: torch.Size([247361])

 36%|███▌      | 343/950 [09:19<16:22,  1.62s/it]

Original waveform shape: torch.Size([2, 568890])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206400])
Final waveform shape before processor: torch.Size([206400])

 36%|███▌      | 344/950 [09:21<16:28,  1.63s/it]

Original waveform shape: torch.Size([2, 1167327])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 423520])
Final waveform shape before processor: torch.Size([423520])

 36%|███▋      | 345/950 [09:23<20:09,  2.00s/it]

Original waveform shape: torch.Size([2, 805266])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 292160])
Final waveform shape before processor: torch.Size([292160])

 36%|███▋      | 346/950 [09:25<19:43,  1.96s/it]

Original waveform shape: torch.Size([2, 653562])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237120])
Final waveform shape before processor: torch.Size([237120])

 37%|███▋      | 347/950 [09:28<20:31,  2.04s/it]

Original waveform shape: torch.Size([2, 608580])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220800])
Final waveform shape before processor: torch.Size([220800])

 37%|███▋      | 348/950 [09:29<19:05,  1.90s/it]

Original waveform shape: torch.Size([2, 579474])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 210240])
Final waveform shape before processor: torch.Size([210240])

 37%|███▋      | 349/950 [09:31<18:30,  1.85s/it]

Original waveform shape: torch.Size([2, 514205])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 186560])
Final waveform shape before processor: torch.Size([186560])

 37%|███▋      | 350/950 [09:32<16:48,  1.68s/it]

Original waveform shape: torch.Size([2, 654445])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237441])
Final waveform shape before processor: torch.Size([237441])

 37%|███▋      | 351/950 [09:34<16:44,  1.68s/it]

Original waveform shape: torch.Size([2, 484218])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175680])
Final waveform shape before processor: torch.Size([175680])

 37%|███▋      | 352/950 [09:35<15:08,  1.52s/it]

Original waveform shape: torch.Size([2, 658854])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239040])
Final waveform shape before processor: torch.Size([239040])

 37%|███▋      | 353/950 [09:35<11:44,  1.18s/it]

Original waveform shape: torch.Size([2, 582120])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211200])
Final waveform shape before processor: torch.Size([211200])

 37%|███▋      | 354/950 [09:37<12:09,  1.22s/it]

Original waveform shape: torch.Size([2, 647389])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234881])
Final waveform shape before processor: torch.Size([234881])

 37%|███▋      | 355/950 [09:39<14:31,  1.46s/it]

Original waveform shape: torch.Size([2, 584766])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212160])
Final waveform shape before processor: torch.Size([212160])

 37%|███▋      | 356/950 [09:41<16:04,  1.62s/it]

Original waveform shape: torch.Size([2, 553014])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 200640])
Final waveform shape before processor: torch.Size([200640])

 38%|███▊      | 357/950 [09:42<15:54,  1.61s/it]

Original waveform shape: torch.Size([2, 907137])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 329120])
Final waveform shape before processor: torch.Size([329120])

 38%|███▊      | 358/950 [09:45<18:13,  1.85s/it]

Original waveform shape: torch.Size([2, 534492])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 193920])
Final waveform shape before processor: torch.Size([193920])

 38%|███▊      | 359/950 [09:46<16:44,  1.70s/it]

Original waveform shape: torch.Size([2, 616518])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223680])
Final waveform shape before processor: torch.Size([223680])

 38%|███▊      | 360/950 [09:48<16:33,  1.68s/it]

Original waveform shape: torch.Size([2, 480690])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 174400])
Final waveform shape before processor: torch.Size([174400])

 38%|███▊      | 361/950 [09:49<15:28,  1.58s/it]

Original waveform shape: torch.Size([2, 609462])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 221120])
Final waveform shape before processor: torch.Size([221120])

 38%|███▊      | 362/950 [09:51<16:26,  1.68s/it]

Original waveform shape: torch.Size([2, 659735])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239360])
Final waveform shape before processor: torch.Size([239360])

 38%|███▊      | 363/950 [09:52<15:48,  1.62s/it]

Original waveform shape: torch.Size([2, 633277])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229761])
Final waveform shape before processor: torch.Size([229761])

 38%|███▊      | 364/950 [09:53<13:18,  1.36s/it]

Original waveform shape: torch.Size([2, 617399])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224000])
Final waveform shape before processor: torch.Size([224000])

 38%|███▊      | 365/950 [09:55<13:36,  1.40s/it]

Original waveform shape: torch.Size([2, 608580])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220800])
Final waveform shape before processor: torch.Size([220800])

 39%|███▊      | 366/950 [09:56<14:34,  1.50s/it]

Original waveform shape: torch.Size([2, 480690])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 174400])
Final waveform shape before processor: torch.Size([174400])

 39%|███▊      | 367/950 [09:58<13:45,  1.42s/it]

Original waveform shape: torch.Size([2, 664146])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240960])
Final waveform shape before processor: torch.Size([240960])

 39%|███▊      | 368/950 [09:59<14:10,  1.46s/it]

Original waveform shape: torch.Size([2, 934921])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 339201])
Final waveform shape before processor: torch.Size([339201])

 39%|███▉      | 369/950 [10:01<16:10,  1.67s/it]

Original waveform shape: torch.Size([2, 702072])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 254720])
Final waveform shape before processor: torch.Size([254720])

 39%|███▉      | 370/950 [10:03<17:18,  1.79s/it]

Original waveform shape: torch.Size([2, 1080450])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 392000])
Final waveform shape before processor: torch.Size([392000])

 39%|███▉      | 371/950 [10:06<20:22,  2.11s/it]

Original waveform shape: torch.Size([2, 595350])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216000])
Final waveform shape before processor: torch.Size([216000])

 39%|███▉      | 372/950 [10:08<18:15,  1.90s/it]

Original waveform shape: torch.Size([2, 448057])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 162561])
Final waveform shape before processor: torch.Size([162561])

 39%|███▉      | 373/950 [10:09<16:23,  1.70s/it]

Original waveform shape: torch.Size([2, 575064])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208640])
Final waveform shape before processor: torch.Size([208640])

 39%|███▉      | 374/950 [10:10<15:26,  1.61s/it]

Original waveform shape: torch.Size([2, 652680])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236800])
Final waveform shape before processor: torch.Size([236800])

 39%|███▉      | 375/950 [10:12<15:10,  1.58s/it]

Original waveform shape: torch.Size([2, 437472])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 158720])
Final waveform shape before processor: torch.Size([158720])

 40%|███▉      | 376/950 [10:13<14:07,  1.48s/it]

Original waveform shape: torch.Size([2, 770868])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 279680])
Final waveform shape before processor: torch.Size([279680])

 40%|███▉      | 377/950 [10:15<15:38,  1.64s/it]

Original waveform shape: torch.Size([2, 569771])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206720])
Final waveform shape before processor: torch.Size([206720])

 40%|███▉      | 378/950 [10:17<16:35,  1.74s/it]

Original waveform shape: torch.Size([2, 636804])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231040])
Final waveform shape before processor: torch.Size([231040])

 40%|███▉      | 379/950 [10:19<15:39,  1.64s/it]

Original waveform shape: torch.Size([2, 505386])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 183360])
Final waveform shape before processor: torch.Size([183360])

 40%|████      | 380/950 [10:20<14:55,  1.57s/it]

Original waveform shape: torch.Size([2, 1982295])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 719200])
Final waveform shape before processor: torch.Size([719200])

 40%|████      | 381/950 [10:20<11:56,  1.26s/it]

Original waveform shape: torch.Size([2, 707364])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 256640])
Final waveform shape before processor: torch.Size([256640])

 40%|████      | 382/950 [10:21<11:08,  1.18s/it]

Original waveform shape: torch.Size([2, 485100])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 176000])
Final waveform shape before processor: torch.Size([176000])

 40%|████      | 383/950 [10:23<11:11,  1.18s/it]

Original waveform shape: torch.Size([2, 634158])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 230080])
Final waveform shape before processor: torch.Size([230080])

 40%|████      | 384/950 [10:24<12:46,  1.35s/it]

Original waveform shape: torch.Size([2, 1231713])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 446880])
Final waveform shape before processor: torch.Size([446880])

 41%|████      | 385/950 [10:28<17:46,  1.89s/it]

Original waveform shape: torch.Size([2, 540667])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 196161])
Final waveform shape before processor: torch.Size([196161])

 41%|████      | 386/950 [10:29<17:36,  1.87s/it]

Original waveform shape: torch.Size([2, 530082])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 192320])
Final waveform shape before processor: torch.Size([192320])

 41%|████      | 387/950 [10:31<15:48,  1.68s/it]

Original waveform shape: torch.Size([2, 612991])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222401])
Final waveform shape before processor: torch.Size([222401])

 41%|████      | 388/950 [10:32<15:48,  1.69s/it]

Original waveform shape: torch.Size([2, 939330])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 340800])
Final waveform shape before processor: torch.Size([340800])

 41%|████      | 389/950 [10:34<17:10,  1.84s/it]

Original waveform shape: torch.Size([2, 630630])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 228800])
Final waveform shape before processor: torch.Size([228800])

 41%|████      | 390/950 [10:36<15:37,  1.67s/it]

Original waveform shape: torch.Size([2, 383670])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 139200])
Final waveform shape before processor: torch.Size([139200])

 41%|████      | 391/950 [10:37<13:58,  1.50s/it]

Original waveform shape: torch.Size([2, 563598])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 204480])
Final waveform shape before processor: torch.Size([204480])

 41%|████▏     | 392/950 [10:38<14:13,  1.53s/it]

Original waveform shape: torch.Size([2, 659736])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239360])
Final waveform shape before processor: torch.Size([239360])

 41%|████▏     | 393/950 [10:40<15:04,  1.62s/it]

Original waveform shape: torch.Size([2, 635040])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 230400])
Final waveform shape before processor: torch.Size([230400])

 41%|████▏     | 394/950 [10:42<16:05,  1.74s/it]

Original waveform shape: torch.Size([2, 507150])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 184000])
Final waveform shape before processor: torch.Size([184000])

 42%|████▏     | 395/950 [10:44<14:57,  1.62s/it]

Original waveform shape: torch.Size([2, 605934])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219840])
Final waveform shape before processor: torch.Size([219840])

 42%|████▏     | 396/950 [10:45<14:41,  1.59s/it]

Original waveform shape: torch.Size([2, 605052])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219520])
Final waveform shape before processor: torch.Size([219520])

 42%|████▏     | 397/950 [10:47<14:30,  1.57s/it]

Original waveform shape: torch.Size([2, 540666])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 196160])
Final waveform shape before processor: torch.Size([196160])

 42%|████▏     | 398/950 [10:48<14:21,  1.56s/it]

Original waveform shape: torch.Size([2, 645624])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234240])
Final waveform shape before processor: torch.Size([234240])

 42%|████▏     | 399/950 [10:50<14:04,  1.53s/it]

Original waveform shape: torch.Size([2, 591822])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 214720])
Final waveform shape before processor: torch.Size([214720])

 42%|████▏     | 400/950 [10:51<14:40,  1.60s/it]

Original waveform shape: torch.Size([2, 415863])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 150880])
Final waveform shape before processor: torch.Size([150880])

 42%|████▏     | 401/950 [10:53<15:02,  1.64s/it]

Original waveform shape: torch.Size([2, 582121])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211201])
Final waveform shape before processor: torch.Size([211201])

 42%|████▏     | 402/950 [10:55<14:42,  1.61s/it]

Original waveform shape: torch.Size([2, 576828])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209280])
Final waveform shape before processor: torch.Size([209280])

 42%|████▏     | 403/950 [10:56<14:32,  1.60s/it]

Original waveform shape: torch.Size([2, 911107])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 330561])
Final waveform shape before processor: torch.Size([330561])

 43%|████▎     | 404/950 [10:59<16:16,  1.79s/it]

Original waveform shape: torch.Size([2, 580356])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 210560])
Final waveform shape before processor: torch.Size([210560])

 43%|████▎     | 405/950 [11:00<14:40,  1.62s/it]

Original waveform shape: torch.Size([2, 432180])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 156800])
Final waveform shape before processor: torch.Size([156800])

 43%|████▎     | 406/950 [11:01<13:59,  1.54s/it]

Original waveform shape: torch.Size([2, 667674])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 242240])
Final waveform shape before processor: torch.Size([242240])

 43%|████▎     | 407/950 [11:03<14:49,  1.64s/it]

Original waveform shape: torch.Size([2, 508914])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 184640])
Final waveform shape before processor: torch.Size([184640])

 43%|████▎     | 408/950 [11:05<15:23,  1.70s/it]

Original waveform shape: torch.Size([2, 651797])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236480])
Final waveform shape before processor: torch.Size([236480])

 43%|████▎     | 409/950 [11:07<16:04,  1.78s/it]

Original waveform shape: torch.Size([2, 637686])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231360])
Final waveform shape before processor: torch.Size([231360])

 43%|████▎     | 410/950 [11:08<15:39,  1.74s/it]

Original waveform shape: torch.Size([2, 620046])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224960])
Final waveform shape before processor: torch.Size([224960])

 43%|████▎     | 411/950 [11:10<15:14,  1.70s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

 43%|████▎     | 412/950 [11:12<15:20,  1.71s/it]

Original waveform shape: torch.Size([2, 620046])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224960])
Final waveform shape before processor: torch.Size([224960])

 43%|████▎     | 413/950 [11:14<15:30,  1.73s/it]

Original waveform shape: torch.Size([2, 677376])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 245760])
Final waveform shape before processor: torch.Size([245760])

 44%|████▎     | 414/950 [11:15<15:23,  1.72s/it]

Original waveform shape: torch.Size([2, 433944])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 157440])
Final waveform shape before processor: torch.Size([157440])

 44%|████▎     | 415/950 [11:17<15:16,  1.71s/it]

Original waveform shape: torch.Size([2, 654444])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237440])
Final waveform shape before processor: torch.Size([237440])

 44%|████▍     | 416/950 [11:19<15:17,  1.72s/it]

Original waveform shape: torch.Size([2, 517734])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 187840])
Final waveform shape before processor: torch.Size([187840])

 44%|████▍     | 417/950 [11:20<14:33,  1.64s/it]

Original waveform shape: torch.Size([2, 684431])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 248320])
Final waveform shape before processor: torch.Size([248320])

 44%|████▍     | 418/950 [11:22<15:43,  1.77s/it]

Original waveform shape: torch.Size([2, 568008])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206080])
Final waveform shape before processor: torch.Size([206080])

 44%|████▍     | 419/950 [11:24<15:17,  1.73s/it]

Original waveform shape: torch.Size([2, 645624])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234240])
Final waveform shape before processor: torch.Size([234240])

 44%|████▍     | 420/950 [11:26<15:15,  1.73s/it]

Original waveform shape: torch.Size([2, 749700])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 272000])
Final waveform shape before processor: torch.Size([272000])

 44%|████▍     | 421/950 [11:28<16:10,  1.83s/it]

Original waveform shape: torch.Size([2, 723240])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 262400])
Final waveform shape before processor: torch.Size([262400])

 44%|████▍     | 422/950 [11:30<17:41,  2.01s/it]

Original waveform shape: torch.Size([2, 577710])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209600])
Final waveform shape before processor: torch.Size([209600])

 45%|████▍     | 423/950 [11:32<16:20,  1.86s/it]

Original waveform shape: torch.Size([2, 471869])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 171200])
Final waveform shape before processor: torch.Size([171200])

 45%|████▍     | 424/950 [11:33<15:01,  1.71s/it]

Original waveform shape: torch.Size([2, 755874])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 274240])
Final waveform shape before processor: torch.Size([274240])

 45%|████▍     | 425/950 [11:35<15:24,  1.76s/it]

Original waveform shape: torch.Size([2, 657090])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 238400])
Final waveform shape before processor: torch.Size([238400])

 45%|████▍     | 426/950 [11:36<14:58,  1.72s/it]

Original waveform shape: torch.Size([2, 666791])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241920])
Final waveform shape before processor: torch.Size([241920])

 45%|████▍     | 427/950 [11:38<15:03,  1.73s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

 45%|████▌     | 428/950 [11:40<15:13,  1.75s/it]

Original waveform shape: torch.Size([2, 563598])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 204480])
Final waveform shape before processor: torch.Size([204480])

 45%|████▌     | 429/950 [11:42<15:25,  1.78s/it]

Original waveform shape: torch.Size([2, 635922])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 230720])
Final waveform shape before processor: torch.Size([230720])

 45%|████▌     | 430/950 [11:44<15:11,  1.75s/it]

Original waveform shape: torch.Size([2, 602406])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218560])
Final waveform shape before processor: torch.Size([218560])

 45%|████▌     | 431/950 [11:50<27:01,  3.12s/it]

Original waveform shape: torch.Size([2, 942858])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 342080])
Final waveform shape before processor: torch.Size([342080])

 45%|████▌     | 432/950 [11:52<25:19,  2.93s/it]

Original waveform shape: torch.Size([2, 650916])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236160])
Final waveform shape before processor: torch.Size([236160])

 46%|████▌     | 433/950 [11:54<23:03,  2.68s/it]

Original waveform shape: torch.Size([2, 627102])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227520])
Final waveform shape before processor: torch.Size([227520])

 46%|████▌     | 434/950 [11:56<20:16,  2.36s/it]

Original waveform shape: torch.Size([2, 654574])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237488])
Final waveform shape before processor: torch.Size([237488])

 46%|████▌     | 435/950 [11:58<18:23,  2.14s/it]

Original waveform shape: torch.Size([2, 629748])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 228480])
Final waveform shape before processor: torch.Size([228480])

 46%|████▌     | 436/950 [11:59<16:50,  1.97s/it]

Original waveform shape: torch.Size([2, 616518])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223680])
Final waveform shape before processor: torch.Size([223680])

 46%|████▌     | 437/950 [12:01<15:36,  1.83s/it]

Original waveform shape: torch.Size([2, 653562])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237120])
Final waveform shape before processor: torch.Size([237120])

 46%|████▌     | 438/950 [12:02<15:04,  1.77s/it]

Original waveform shape: torch.Size([2, 627984])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227840])
Final waveform shape before processor: torch.Size([227840])

 46%|████▌     | 439/950 [12:04<14:47,  1.74s/it]

Original waveform shape: torch.Size([2, 410175])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 148817])
Final waveform shape before processor: torch.Size([148817])

 46%|████▋     | 440/950 [12:06<14:21,  1.69s/it]

Original waveform shape: torch.Size([2, 644742])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233920])
Final waveform shape before processor: torch.Size([233920])

 46%|████▋     | 441/950 [12:07<14:29,  1.71s/it]

Original waveform shape: torch.Size([2, 727650])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 264000])
Final waveform shape before processor: torch.Size([264000])

 47%|████▋     | 442/950 [12:09<14:04,  1.66s/it]

Original waveform shape: torch.Size([2, 784098])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 284480])
Final waveform shape before processor: torch.Size([284480])

 47%|████▋     | 443/950 [12:11<15:08,  1.79s/it]

Original waveform shape: torch.Size([2, 612108])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222080])
Final waveform shape before processor: torch.Size([222080])

 47%|████▋     | 444/950 [12:13<14:27,  1.71s/it]

Original waveform shape: torch.Size([2, 466578])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 169280])
Final waveform shape before processor: torch.Size([169280])

 47%|████▋     | 445/950 [12:14<13:27,  1.60s/it]

Original waveform shape: torch.Size([2, 601524])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218240])
Final waveform shape before processor: torch.Size([218240])

 47%|████▋     | 446/950 [12:16<13:42,  1.63s/it]

Original waveform shape: torch.Size([2, 637686])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231360])
Final waveform shape before processor: torch.Size([231360])

 47%|████▋     | 447/950 [12:18<14:24,  1.72s/it]

Original waveform shape: torch.Size([2, 771309])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 279840])
Final waveform shape before processor: torch.Size([279840])

 47%|████▋     | 448/950 [12:20<16:15,  1.94s/it]

Original waveform shape: torch.Size([2, 634157])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 230080])
Final waveform shape before processor: torch.Size([230080])

 47%|████▋     | 449/950 [12:22<15:40,  1.88s/it]

Original waveform shape: torch.Size([2, 661500])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240000])
Final waveform shape before processor: torch.Size([240000])

 47%|████▋     | 450/950 [12:23<15:18,  1.84s/it]

Original waveform shape: torch.Size([2, 583884])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211840])
Final waveform shape before processor: torch.Size([211840])

 47%|████▋     | 451/950 [12:25<14:09,  1.70s/it]

Original waveform shape: torch.Size([2, 510677])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 185280])
Final waveform shape before processor: torch.Size([185280])

 48%|████▊     | 452/950 [12:26<13:14,  1.60s/it]

Original waveform shape: torch.Size([2, 472752])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 171520])
Final waveform shape before processor: torch.Size([171520])

 48%|████▊     | 453/950 [12:27<12:06,  1.46s/it]

Original waveform shape: torch.Size([2, 537138])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 194880])
Final waveform shape before processor: torch.Size([194880])

 48%|████▊     | 454/950 [12:29<11:49,  1.43s/it]

Original waveform shape: torch.Size([2, 631512])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229120])
Final waveform shape before processor: torch.Size([229120])

 48%|████▊     | 455/950 [12:31<13:00,  1.58s/it]

Original waveform shape: torch.Size([2, 613873])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222721])
Final waveform shape before processor: torch.Size([222721])

 48%|████▊     | 456/950 [12:32<13:31,  1.64s/it]

Original waveform shape: torch.Size([2, 492156])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 178560])
Final waveform shape before processor: torch.Size([178560])

 48%|████▊     | 457/950 [12:34<12:59,  1.58s/it]

Original waveform shape: torch.Size([2, 445410])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 161600])
Final waveform shape before processor: torch.Size([161600])

 48%|████▊     | 458/950 [12:35<12:13,  1.49s/it]

Original waveform shape: torch.Size([2, 705600])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 256000])
Final waveform shape before processor: torch.Size([256000])

 48%|████▊     | 459/950 [12:37<13:18,  1.63s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

 48%|████▊     | 460/950 [12:39<13:12,  1.62s/it]

Original waveform shape: torch.Size([2, 929628])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 337280])
Final waveform shape before processor: torch.Size([337280])

 49%|████▊     | 461/950 [12:41<15:08,  1.86s/it]

Original waveform shape: torch.Size([2, 611225])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 221760])
Final waveform shape before processor: torch.Size([221760])

 49%|████▊     | 462/950 [12:43<14:55,  1.83s/it]

Original waveform shape: torch.Size([2, 630630])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 228800])
Final waveform shape before processor: torch.Size([228800])

 49%|████▊     | 463/950 [12:45<14:41,  1.81s/it]

Original waveform shape: torch.Size([2, 561834])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 203840])
Final waveform shape before processor: torch.Size([203840])

 49%|████▉     | 464/950 [12:46<13:40,  1.69s/it]

Original waveform shape: torch.Size([2, 595350])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216000])
Final waveform shape before processor: torch.Size([216000])

 49%|████▉     | 465/950 [12:47<13:10,  1.63s/it]

Original waveform shape: torch.Size([2, 1700582])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 616992])
Final waveform shape before processor: torch.Size([616992])

 49%|████▉     | 466/950 [12:48<10:24,  1.29s/it]

Original waveform shape: torch.Size([2, 505386])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 183360])
Final waveform shape before processor: torch.Size([183360])

 49%|████▉     | 467/950 [12:49<10:42,  1.33s/it]

Original waveform shape: torch.Size([2, 582120])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211200])
Final waveform shape before processor: torch.Size([211200])

 49%|████▉     | 468/950 [12:51<10:46,  1.34s/it]

Original waveform shape: torch.Size([2, 511560])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 185600])
Final waveform shape before processor: torch.Size([185600])

 49%|████▉     | 469/950 [12:52<09:27,  1.18s/it]

Original waveform shape: torch.Size([2, 690606])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 250560])
Final waveform shape before processor: torch.Size([250560])

 49%|████▉     | 470/950 [12:53<10:30,  1.31s/it]

Original waveform shape: torch.Size([2, 573300])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208000])
Final waveform shape before processor: torch.Size([208000])

 50%|████▉     | 471/950 [12:55<11:45,  1.47s/it]

Original waveform shape: torch.Size([2, 581238])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 210880])
Final waveform shape before processor: torch.Size([210880])

 50%|████▉     | 472/950 [12:57<11:52,  1.49s/it]

Original waveform shape: torch.Size([2, 605933])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219840])
Final waveform shape before processor: torch.Size([219840])

 50%|████▉     | 473/950 [12:58<11:46,  1.48s/it]

Original waveform shape: torch.Size([2, 616518])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223680])
Final waveform shape before processor: torch.Size([223680])

 50%|████▉     | 474/950 [12:59<11:30,  1.45s/it]

Original waveform shape: torch.Size([2, 647388])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234880])
Final waveform shape before processor: torch.Size([234880])

 50%|█████     | 475/950 [13:01<12:03,  1.52s/it]

Original waveform shape: torch.Size([2, 620047])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224961])
Final waveform shape before processor: torch.Size([224961])

 50%|█████     | 476/950 [13:03<12:17,  1.56s/it]

Original waveform shape: torch.Size([2, 605052])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219520])
Final waveform shape before processor: torch.Size([219520])

 50%|█████     | 477/950 [13:04<12:11,  1.55s/it]

Original waveform shape: torch.Size([2, 662382])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240320])
Final waveform shape before processor: torch.Size([240320])

 50%|█████     | 478/950 [13:06<11:37,  1.48s/it]

Original waveform shape: torch.Size([2, 826875])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 300000])
Final waveform shape before processor: torch.Size([300000])

 50%|█████     | 479/950 [13:08<14:04,  1.79s/it]

Original waveform shape: torch.Size([2, 1128960])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 409600])
Final waveform shape before processor: torch.Size([409600])

 51%|█████     | 480/950 [13:11<15:51,  2.02s/it]

Original waveform shape: torch.Size([2, 604171])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219201])
Final waveform shape before processor: torch.Size([219201])

 51%|█████     | 481/950 [13:12<15:05,  1.93s/it]

Original waveform shape: torch.Size([2, 620046])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224960])
Final waveform shape before processor: torch.Size([224960])

 51%|█████     | 482/950 [13:14<14:35,  1.87s/it]

Original waveform shape: torch.Size([2, 577269])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209440])
Final waveform shape before processor: torch.Size([209440])

 51%|█████     | 483/950 [13:15<13:19,  1.71s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

 51%|█████     | 484/950 [13:17<13:20,  1.72s/it]

Original waveform shape: torch.Size([2, 530082])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 192320])
Final waveform shape before processor: torch.Size([192320])

 51%|█████     | 485/950 [13:19<13:21,  1.72s/it]

Original waveform shape: torch.Size([2, 806589])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 292640])
Final waveform shape before processor: torch.Size([292640])

 51%|█████     | 486/950 [13:21<14:27,  1.87s/it]

Original waveform shape: torch.Size([2, 521420])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 189178])
Final waveform shape before processor: torch.Size([189178])

 51%|█████▏    | 487/950 [13:23<13:14,  1.72s/it]

Original waveform shape: torch.Size([2, 732942])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 265920])
Final waveform shape before processor: torch.Size([265920])

 51%|█████▏    | 488/950 [13:24<13:29,  1.75s/it]

Original waveform shape: torch.Size([2, 633276])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229760])
Final waveform shape before processor: torch.Size([229760])

 51%|█████▏    | 489/950 [13:26<12:36,  1.64s/it]

Original waveform shape: torch.Size([2, 979902])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 355520])
Final waveform shape before processor: torch.Size([355520])

 52%|█████▏    | 490/950 [13:28<13:59,  1.83s/it]

Original waveform shape: torch.Size([2, 565362])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 205120])
Final waveform shape before processor: torch.Size([205120])

 52%|█████▏    | 491/950 [13:29<12:54,  1.69s/it]

Original waveform shape: torch.Size([2, 655326])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237760])
Final waveform shape before processor: torch.Size([237760])

 52%|█████▏    | 492/950 [13:31<12:46,  1.67s/it]

Original waveform shape: torch.Size([2, 484659])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175840])
Final waveform shape before processor: torch.Size([175840])

 52%|█████▏    | 493/950 [13:33<13:01,  1.71s/it]

Original waveform shape: torch.Size([2, 633276])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229760])
Final waveform shape before processor: torch.Size([229760])

 52%|█████▏    | 494/950 [13:35<13:18,  1.75s/it]

Original waveform shape: torch.Size([2, 593586])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215360])
Final waveform shape before processor: torch.Size([215360])

 52%|█████▏    | 495/950 [13:36<11:42,  1.54s/it]

Original waveform shape: torch.Size([2, 546840])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 198400])
Final waveform shape before processor: torch.Size([198400])

 52%|█████▏    | 496/950 [13:37<11:25,  1.51s/it]

Original waveform shape: torch.Size([2, 792918])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 287680])
Final waveform shape before processor: torch.Size([287680])

 52%|█████▏    | 497/950 [13:39<12:52,  1.70s/it]

Original waveform shape: torch.Size([2, 617400])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224000])
Final waveform shape before processor: torch.Size([224000])

 52%|█████▏    | 498/950 [13:41<12:33,  1.67s/it]

Original waveform shape: torch.Size([2, 470988])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 170880])
Final waveform shape before processor: torch.Size([170880])

 53%|█████▎    | 499/950 [13:41<09:46,  1.30s/it]

Original waveform shape: torch.Size([2, 580356])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 210560])
Final waveform shape before processor: torch.Size([210560])

 53%|█████▎    | 500/950 [13:43<11:00,  1.47s/it]

Original waveform shape: torch.Size([2, 627985])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227841])
Final waveform shape before processor: torch.Size([227841])

 53%|█████▎    | 501/950 [13:45<11:47,  1.58s/it]

Original waveform shape: torch.Size([2, 620046])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224960])
Final waveform shape before processor: torch.Size([224960])

 53%|█████▎    | 502/950 [13:47<11:56,  1.60s/it]

Original waveform shape: torch.Size([2, 485100])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 176000])
Final waveform shape before processor: torch.Size([176000])

 53%|█████▎    | 503/950 [13:48<11:11,  1.50s/it]

Original waveform shape: torch.Size([2, 575946])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208960])
Final waveform shape before processor: torch.Size([208960])

 53%|█████▎    | 504/950 [13:49<10:48,  1.45s/it]

Original waveform shape: torch.Size([2, 620046])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224960])
Final waveform shape before processor: torch.Size([224960])

 53%|█████▎    | 505/950 [13:51<11:24,  1.54s/it]

Original waveform shape: torch.Size([2, 536256])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 194560])
Final waveform shape before processor: torch.Size([194560])

 53%|█████▎    | 506/950 [13:52<10:18,  1.39s/it]

Original waveform shape: torch.Size([2, 526554])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 191040])
Final waveform shape before processor: torch.Size([191040])

 53%|█████▎    | 507/950 [13:53<10:09,  1.37s/it]

Original waveform shape: torch.Size([2, 647388])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234880])
Final waveform shape before processor: torch.Size([234880])

 53%|█████▎    | 508/950 [13:55<11:13,  1.52s/it]

Original waveform shape: torch.Size([2, 604170])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219200])
Final waveform shape before processor: torch.Size([219200])

 54%|█████▎    | 509/950 [13:57<11:52,  1.61s/it]

Original waveform shape: torch.Size([2, 1347255])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 488800])
Final waveform shape before processor: torch.Size([488800])

 54%|█████▎    | 510/950 [14:00<15:17,  2.09s/it]

Original waveform shape: torch.Size([2, 419782])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 152302])
Final waveform shape before processor: torch.Size([152302])

 54%|█████▍    | 511/950 [14:01<13:13,  1.81s/it]

Original waveform shape: torch.Size([2, 600642])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 217920])
Final waveform shape before processor: torch.Size([217920])

 54%|█████▍    | 512/950 [14:03<12:25,  1.70s/it]

Original waveform shape: torch.Size([2, 430416])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 156160])
Final waveform shape before processor: torch.Size([156160])

 54%|█████▍    | 513/950 [14:03<09:32,  1.31s/it]

Original waveform shape: torch.Size([2, 926101])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 336001])
Final waveform shape before processor: torch.Size([336001])

 54%|█████▍    | 514/950 [14:05<11:14,  1.55s/it]

Original waveform shape: torch.Size([2, 869211])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 315360])
Final waveform shape before processor: torch.Size([315360])

 54%|█████▍    | 515/950 [14:08<13:24,  1.85s/it]

Original waveform shape: torch.Size([2, 549486])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 199360])
Final waveform shape before processor: torch.Size([199360])

 54%|█████▍    | 516/950 [14:10<13:04,  1.81s/it]

Original waveform shape: torch.Size([2, 558306])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 202560])
Final waveform shape before processor: torch.Size([202560])

 54%|█████▍    | 517/950 [14:11<12:16,  1.70s/it]

Original waveform shape: torch.Size([2, 647388])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234880])
Final waveform shape before processor: torch.Size([234880])

 55%|█████▍    | 518/950 [14:13<12:13,  1.70s/it]

Original waveform shape: torch.Size([2, 549486])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 199360])
Final waveform shape before processor: torch.Size([199360])

 55%|█████▍    | 519/950 [14:14<11:37,  1.62s/it]

Original waveform shape: torch.Size([2, 525672])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 190720])
Final waveform shape before processor: torch.Size([190720])

 55%|█████▍    | 520/950 [14:15<10:37,  1.48s/it]

Original waveform shape: torch.Size([2, 639450])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232000])
Final waveform shape before processor: torch.Size([232000])

 55%|█████▍    | 521/950 [14:17<11:31,  1.61s/it]

Original waveform shape: torch.Size([2, 632395])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229441])
Final waveform shape before processor: torch.Size([229441])

 55%|█████▍    | 522/950 [14:19<11:39,  1.63s/it]

Original waveform shape: torch.Size([2, 598878])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 217280])
Final waveform shape before processor: torch.Size([217280])

 55%|█████▌    | 523/950 [14:21<12:41,  1.78s/it]

Original waveform shape: torch.Size([2, 485100])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 176000])
Final waveform shape before processor: torch.Size([176000])

 55%|█████▌    | 524/950 [14:23<12:03,  1.70s/it]

Original waveform shape: torch.Size([2, 563598])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 204480])
Final waveform shape before processor: torch.Size([204480])

 55%|█████▌    | 525/950 [14:24<11:19,  1.60s/it]

Original waveform shape: torch.Size([2, 1643794])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 596388])
Final waveform shape before processor: torch.Size([596388])

 55%|█████▌    | 526/950 [14:27<14:27,  2.05s/it]

Original waveform shape: torch.Size([2, 611227])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 221761])
Final waveform shape before processor: torch.Size([221761])

 55%|█████▌    | 527/950 [14:29<13:40,  1.94s/it]

Original waveform shape: torch.Size([2, 522143])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 189440])
Final waveform shape before processor: torch.Size([189440])

 56%|█████▌    | 528/950 [14:30<12:33,  1.79s/it]

Original waveform shape: torch.Size([2, 577710])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209600])
Final waveform shape before processor: torch.Size([209600])

 56%|█████▌    | 529/950 [14:32<12:10,  1.74s/it]

Original waveform shape: torch.Size([2, 569772])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206720])
Final waveform shape before processor: torch.Size([206720])

 56%|█████▌    | 530/950 [14:34<12:20,  1.76s/it]

Original waveform shape: torch.Size([2, 546840])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 198400])
Final waveform shape before processor: torch.Size([198400])

 56%|█████▌    | 531/950 [14:35<11:56,  1.71s/it]

Original waveform shape: torch.Size([2, 617400])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224000])
Final waveform shape before processor: torch.Size([224000])

 56%|█████▌    | 532/950 [14:42<21:40,  3.11s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

 56%|█████▌    | 533/950 [14:43<18:38,  2.68s/it]

Original waveform shape: torch.Size([2, 663264])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240640])
Final waveform shape before processor: torch.Size([240640])

 56%|█████▌    | 534/950 [14:45<17:35,  2.54s/it]

Original waveform shape: torch.Size([2, 482454])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175040])
Final waveform shape before processor: torch.Size([175040])

 56%|█████▋    | 535/950 [14:47<15:18,  2.21s/it]

Original waveform shape: torch.Size([2, 506268])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 183680])
Final waveform shape before processor: torch.Size([183680])

 56%|█████▋    | 536/950 [14:48<13:23,  1.94s/it]

Original waveform shape: torch.Size([2, 438354])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 159040])
Final waveform shape before processor: torch.Size([159040])

 57%|█████▋    | 537/950 [14:49<11:48,  1.72s/it]

Original waveform shape: torch.Size([2, 1040760])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 377600])
Final waveform shape before processor: torch.Size([377600])

 57%|█████▋    | 538/950 [14:52<12:32,  1.83s/it]

Original waveform shape: torch.Size([2, 597997])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216961])
Final waveform shape before processor: torch.Size([216961])

 57%|█████▋    | 539/950 [14:53<11:20,  1.66s/it]

Original waveform shape: torch.Size([2, 490392])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 177920])
Final waveform shape before processor: torch.Size([177920])

 57%|█████▋    | 540/950 [14:54<10:41,  1.57s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

 57%|█████▋    | 541/950 [14:55<09:49,  1.44s/it]

Original waveform shape: torch.Size([2, 424242])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 153920])
Final waveform shape before processor: torch.Size([153920])

 57%|█████▋    | 542/950 [14:57<10:25,  1.53s/it]

Original waveform shape: torch.Size([2, 370440])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 134400])
Final waveform shape before processor: torch.Size([134400])

 57%|█████▋    | 543/950 [14:58<10:15,  1.51s/it]

Original waveform shape: torch.Size([2, 742644])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 269440])
Final waveform shape before processor: torch.Size([269440])

 57%|█████▋    | 544/950 [15:00<10:51,  1.60s/it]

Original waveform shape: torch.Size([2, 588294])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 213440])
Final waveform shape before processor: torch.Size([213440])

 57%|█████▋    | 545/950 [15:02<10:21,  1.53s/it]

Original waveform shape: torch.Size([2, 497889])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 180640])
Final waveform shape before processor: torch.Size([180640])

 57%|█████▋    | 546/950 [15:03<09:58,  1.48s/it]

Original waveform shape: torch.Size([2, 647388])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234880])
Final waveform shape before processor: torch.Size([234880])

 58%|█████▊    | 547/950 [15:05<10:19,  1.54s/it]

Original waveform shape: torch.Size([2, 695015])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 252160])
Final waveform shape before processor: torch.Size([252160])

 58%|█████▊    | 548/950 [15:07<11:09,  1.67s/it]

Original waveform shape: torch.Size([2, 652680])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236800])
Final waveform shape before processor: torch.Size([236800])

 58%|█████▊    | 549/950 [15:09<11:50,  1.77s/it]

Original waveform shape: torch.Size([2, 516852])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 187520])
Final waveform shape before processor: torch.Size([187520])

 58%|█████▊    | 550/950 [15:11<11:59,  1.80s/it]

Original waveform shape: torch.Size([2, 415422])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 150720])
Final waveform shape before processor: torch.Size([150720])

 58%|█████▊    | 551/950 [15:12<10:46,  1.62s/it]

Original waveform shape: torch.Size([2, 629748])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 228480])
Final waveform shape before processor: torch.Size([228480])

 58%|█████▊    | 552/950 [15:13<10:46,  1.62s/it]

Original waveform shape: torch.Size([2, 644301])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233760])
Final waveform shape before processor: torch.Size([233760])

 58%|█████▊    | 553/950 [15:15<11:00,  1.66s/it]

Original waveform shape: torch.Size([2, 614754])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223040])
Final waveform shape before processor: torch.Size([223040])

 58%|█████▊    | 554/950 [15:17<10:56,  1.66s/it]

Original waveform shape: torch.Size([2, 590940])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 214400])
Final waveform shape before processor: torch.Size([214400])

 58%|█████▊    | 555/950 [15:18<10:47,  1.64s/it]

Original waveform shape: torch.Size([2, 788949])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 286240])
Final waveform shape before processor: torch.Size([286240])

 59%|█████▊    | 556/950 [15:21<11:58,  1.82s/it]

Original waveform shape: torch.Size([2, 601524])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218240])
Final waveform shape before processor: torch.Size([218240])

 59%|█████▊    | 557/950 [15:22<11:48,  1.80s/it]

Original waveform shape: torch.Size([2, 637686])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231360])
Final waveform shape before processor: torch.Size([231360])

 59%|█████▊    | 558/950 [15:24<11:31,  1.76s/it]

Original waveform shape: torch.Size([2, 639450])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232000])
Final waveform shape before processor: torch.Size([232000])

 59%|█████▉    | 559/950 [15:26<11:10,  1.71s/it]

Original waveform shape: torch.Size([2, 478926])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 173760])
Final waveform shape before processor: torch.Size([173760])

 59%|█████▉    | 560/950 [15:27<10:07,  1.56s/it]

Original waveform shape: torch.Size([2, 614753])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223040])
Final waveform shape before processor: torch.Size([223040])

 59%|█████▉    | 561/950 [15:28<09:35,  1.48s/it]

Original waveform shape: torch.Size([2, 648270])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235200])
Final waveform shape before processor: torch.Size([235200])

 59%|█████▉    | 562/950 [15:30<09:36,  1.49s/it]

Original waveform shape: torch.Size([2, 657090])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 238400])
Final waveform shape before processor: torch.Size([238400])

 59%|█████▉    | 563/950 [15:31<10:15,  1.59s/it]

Original waveform shape: torch.Size([2, 665909])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241600])
Final waveform shape before processor: torch.Size([241600])

 59%|█████▉    | 564/950 [15:33<10:58,  1.71s/it]

Original waveform shape: torch.Size([2, 658854])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239040])
Final waveform shape before processor: torch.Size([239040])

 59%|█████▉    | 565/950 [15:35<11:13,  1.75s/it]

Original waveform shape: torch.Size([2, 703395])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 255200])
Final waveform shape before processor: torch.Size([255200])

 60%|█████▉    | 566/950 [15:37<11:11,  1.75s/it]

Original waveform shape: torch.Size([2, 578592])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209920])
Final waveform shape before processor: torch.Size([209920])

 60%|█████▉    | 567/950 [15:39<10:35,  1.66s/it]

Original waveform shape: torch.Size([2, 640332])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232320])
Final waveform shape before processor: torch.Size([232320])

 60%|█████▉    | 568/950 [15:40<10:41,  1.68s/it]

Original waveform shape: torch.Size([2, 544194])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 197440])
Final waveform shape before processor: torch.Size([197440])

 60%|█████▉    | 569/950 [15:42<10:16,  1.62s/it]

Original waveform shape: torch.Size([2, 468342])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 169920])
Final waveform shape before processor: torch.Size([169920])

 60%|██████    | 570/950 [15:43<09:20,  1.48s/it]

Original waveform shape: torch.Size([2, 585648])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212480])
Final waveform shape before processor: torch.Size([212480])

 60%|██████    | 571/950 [15:44<09:36,  1.52s/it]

Original waveform shape: torch.Size([2, 625338])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226880])
Final waveform shape before processor: torch.Size([226880])

 60%|██████    | 572/950 [15:47<10:37,  1.69s/it]

Original waveform shape: torch.Size([2, 349272])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 126720])
Final waveform shape before processor: torch.Size([126720])

 60%|██████    | 573/950 [15:48<09:32,  1.52s/it]

Original waveform shape: torch.Size([2, 637685])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231360])
Final waveform shape before processor: torch.Size([231360])

 60%|██████    | 574/950 [15:49<09:27,  1.51s/it]

Original waveform shape: torch.Size([2, 455994])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 165440])
Final waveform shape before processor: torch.Size([165440])

 61%|██████    | 575/950 [15:50<08:56,  1.43s/it]

Original waveform shape: torch.Size([2, 575064])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208640])
Final waveform shape before processor: torch.Size([208640])

 61%|██████    | 576/950 [15:52<08:46,  1.41s/it]

Original waveform shape: torch.Size([2, 491274])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 178240])
Final waveform shape before processor: torch.Size([178240])

 61%|██████    | 577/950 [15:53<08:57,  1.44s/it]

Original waveform shape: torch.Size([2, 497448])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 180480])
Final waveform shape before processor: torch.Size([180480])

 61%|██████    | 578/950 [15:55<09:08,  1.47s/it]

Original waveform shape: torch.Size([2, 553895])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 200960])
Final waveform shape before processor: torch.Size([200960])

 61%|██████    | 579/950 [15:56<09:13,  1.49s/it]

Original waveform shape: torch.Size([2, 654444])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237440])
Final waveform shape before processor: torch.Size([237440])

 61%|██████    | 580/950 [15:58<10:15,  1.66s/it]

Original waveform shape: torch.Size([2, 548603])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 199040])
Final waveform shape before processor: torch.Size([199040])

 61%|██████    | 581/950 [15:59<08:13,  1.34s/it]

Original waveform shape: torch.Size([2, 567126])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 205760])
Final waveform shape before processor: torch.Size([205760])

 61%|██████▏   | 582/950 [16:00<08:20,  1.36s/it]

Original waveform shape: torch.Size([2, 597996])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216960])
Final waveform shape before processor: torch.Size([216960])

 61%|██████▏   | 583/950 [16:02<08:41,  1.42s/it]

Original waveform shape: torch.Size([2, 500976])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 181760])
Final waveform shape before processor: torch.Size([181760])

 61%|██████▏   | 584/950 [16:03<08:28,  1.39s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

 62%|██████▏   | 585/950 [16:05<08:45,  1.44s/it]

Original waveform shape: torch.Size([2, 769986])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 279360])
Final waveform shape before processor: torch.Size([279360])

 62%|██████▏   | 586/950 [16:07<09:26,  1.56s/it]

Original waveform shape: torch.Size([2, 567126])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 205760])
Final waveform shape before processor: torch.Size([205760])

 62%|██████▏   | 587/950 [16:08<09:07,  1.51s/it]

Original waveform shape: torch.Size([2, 625338])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226880])
Final waveform shape before processor: torch.Size([226880])

 62%|██████▏   | 588/950 [16:10<10:01,  1.66s/it]

Original waveform shape: torch.Size([2, 638568])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231680])
Final waveform shape before processor: torch.Size([231680])

 62%|██████▏   | 589/950 [16:12<10:09,  1.69s/it]

Original waveform shape: torch.Size([2, 1007244])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 365440])
Final waveform shape before processor: torch.Size([365440])

 62%|██████▏   | 590/950 [16:14<11:36,  1.94s/it]

Original waveform shape: torch.Size([2, 56624])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 20544])
Final waveform shape before processor: torch.Size([20544])

 62%|██████▏   | 591/950 [16:15<08:53,  1.49s/it]

Original waveform shape: torch.Size([2, 523026])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 189760])
Final waveform shape before processor: torch.Size([189760])

 62%|██████▏   | 592/950 [16:16<08:47,  1.47s/it]

Original waveform shape: torch.Size([2, 553014])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 200640])
Final waveform shape before processor: torch.Size([200640])

 62%|██████▏   | 593/950 [16:18<08:23,  1.41s/it]

Original waveform shape: torch.Size([2, 786303])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 285280])
Final waveform shape before processor: torch.Size([285280])

 63%|██████▎   | 594/950 [16:19<09:15,  1.56s/it]

Original waveform shape: torch.Size([2, 633277])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229761])
Final waveform shape before processor: torch.Size([229761])

 63%|██████▎   | 595/950 [16:21<09:21,  1.58s/it]

Original waveform shape: torch.Size([2, 295470])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 107200])
Final waveform shape before processor: torch.Size([107200])

 63%|██████▎   | 596/950 [16:22<08:14,  1.40s/it]

Original waveform shape: torch.Size([2, 588294])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 213440])
Final waveform shape before processor: torch.Size([213440])

 63%|██████▎   | 597/950 [16:24<08:57,  1.52s/it]

Original waveform shape: torch.Size([2, 675612])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 245120])
Final waveform shape before processor: torch.Size([245120])

 63%|██████▎   | 598/950 [16:26<09:19,  1.59s/it]

Original waveform shape: torch.Size([2, 431298])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 156480])
Final waveform shape before processor: torch.Size([156480])

 63%|██████▎   | 599/950 [16:27<08:35,  1.47s/it]

Original waveform shape: torch.Size([2, 937566])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 340160])
Final waveform shape before processor: torch.Size([340160])

 63%|██████▎   | 600/950 [16:29<09:44,  1.67s/it]

Original waveform shape: torch.Size([2, 655326])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237760])
Final waveform shape before processor: torch.Size([237760])

 63%|██████▎   | 601/950 [16:31<09:55,  1.71s/it]

Original waveform shape: torch.Size([2, 856863])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 310880])
Final waveform shape before processor: torch.Size([310880])

 63%|██████▎   | 602/950 [16:33<10:32,  1.82s/it]

Original waveform shape: torch.Size([2, 493038])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 178880])
Final waveform shape before processor: torch.Size([178880])

 63%|██████▎   | 603/950 [16:35<10:22,  1.79s/it]

Original waveform shape: torch.Size([2, 648270])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235200])
Final waveform shape before processor: torch.Size([235200])

 64%|██████▎   | 604/950 [16:36<10:09,  1.76s/it]

Original waveform shape: torch.Size([2, 665910])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241600])
Final waveform shape before processor: torch.Size([241600])

 64%|██████▎   | 605/950 [16:38<09:56,  1.73s/it]

Original waveform shape: torch.Size([2, 634157])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 230080])
Final waveform shape before processor: torch.Size([230080])

 64%|██████▍   | 606/950 [16:39<09:19,  1.63s/it]

Original waveform shape: torch.Size([2, 800856])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 290560])
Final waveform shape before processor: torch.Size([290560])

 64%|██████▍   | 607/950 [16:41<09:52,  1.73s/it]

Original waveform shape: torch.Size([2, 407484])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 147840])
Final waveform shape before processor: torch.Size([147840])

 64%|██████▍   | 608/950 [16:43<09:08,  1.60s/it]

Original waveform shape: torch.Size([2, 748377])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 271520])
Final waveform shape before processor: torch.Size([271520])

 64%|██████▍   | 609/950 [16:44<09:14,  1.63s/it]

Original waveform shape: torch.Size([2, 560952])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 203520])
Final waveform shape before processor: torch.Size([203520])

 64%|██████▍   | 610/950 [16:46<09:02,  1.60s/it]

Original waveform shape: torch.Size([2, 655326])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237760])
Final waveform shape before processor: torch.Size([237760])

 64%|██████▍   | 611/950 [16:48<10:11,  1.80s/it]

Original waveform shape: torch.Size([2, 535374])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 194240])
Final waveform shape before processor: torch.Size([194240])

 64%|██████▍   | 612/950 [16:50<09:37,  1.71s/it]

Original waveform shape: torch.Size([2, 608580])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220800])
Final waveform shape before processor: torch.Size([220800])

 65%|██████▍   | 613/950 [16:51<08:50,  1.57s/it]

Original waveform shape: torch.Size([2, 589177])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 213761])
Final waveform shape before processor: torch.Size([213761])

 65%|██████▍   | 614/950 [16:52<08:48,  1.57s/it]

Original waveform shape: torch.Size([2, 789389])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 286400])
Final waveform shape before processor: torch.Size([286400])

 65%|██████▍   | 615/950 [16:54<09:14,  1.66s/it]

Original waveform shape: torch.Size([2, 641214])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

 65%|██████▍   | 616/950 [16:56<09:05,  1.63s/it]

Original waveform shape: torch.Size([2, 597114])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216640])
Final waveform shape before processor: torch.Size([216640])

 65%|██████▍   | 617/950 [16:57<08:52,  1.60s/it]

Original waveform shape: torch.Size([2, 824670])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 299200])
Final waveform shape before processor: torch.Size([299200])

 65%|██████▌   | 618/950 [17:00<10:38,  1.92s/it]

Original waveform shape: torch.Size([2, 602406])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218560])
Final waveform shape before processor: torch.Size([218560])

 65%|██████▌   | 619/950 [17:01<09:56,  1.80s/it]

Original waveform shape: torch.Size([2, 599760])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 217600])
Final waveform shape before processor: torch.Size([217600])

 65%|██████▌   | 620/950 [17:02<08:21,  1.52s/it]

Original waveform shape: torch.Size([2, 648270])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235200])
Final waveform shape before processor: torch.Size([235200])

 65%|██████▌   | 621/950 [17:04<08:43,  1.59s/it]

Original waveform shape: torch.Size([2, 464814])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 168640])
Final waveform shape before processor: torch.Size([168640])

 65%|██████▌   | 622/950 [17:05<08:10,  1.50s/it]

Original waveform shape: torch.Size([2, 623573])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226240])
Final waveform shape before processor: torch.Size([226240])

 66%|██████▌   | 623/950 [17:07<08:02,  1.48s/it]

Original waveform shape: torch.Size([2, 635040])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 230400])
Final waveform shape before processor: torch.Size([230400])

 66%|██████▌   | 624/950 [17:08<08:16,  1.52s/it]

Original waveform shape: torch.Size([2, 559188])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 202880])
Final waveform shape before processor: torch.Size([202880])

 66%|██████▌   | 625/950 [17:10<08:27,  1.56s/it]

Original waveform shape: torch.Size([2, 567126])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 205760])
Final waveform shape before processor: torch.Size([205760])

 66%|██████▌   | 626/950 [17:12<09:18,  1.72s/it]

Original waveform shape: torch.Size([2, 456876])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 165760])
Final waveform shape before processor: torch.Size([165760])

 66%|██████▌   | 627/950 [17:14<08:40,  1.61s/it]

Original waveform shape: torch.Size([2, 630630])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 228800])
Final waveform shape before processor: torch.Size([228800])

 66%|██████▌   | 628/950 [17:15<08:36,  1.60s/it]

Original waveform shape: torch.Size([2, 468288])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 169901])
Final waveform shape before processor: torch.Size([169901])

 66%|██████▌   | 629/950 [17:17<08:18,  1.55s/it]

Original waveform shape: torch.Size([2, 573301])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208001])
Final waveform shape before processor: torch.Size([208001])

 66%|██████▋   | 630/950 [17:18<07:39,  1.44s/it]

Original waveform shape: torch.Size([2, 572418])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 207680])
Final waveform shape before processor: torch.Size([207680])

 66%|██████▋   | 631/950 [17:19<07:55,  1.49s/it]

Original waveform shape: torch.Size([2, 643860])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233600])
Final waveform shape before processor: torch.Size([233600])

 67%|██████▋   | 632/950 [17:20<07:18,  1.38s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

 67%|██████▋   | 633/950 [17:21<06:06,  1.16s/it]

Original waveform shape: torch.Size([2, 602406])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218560])
Final waveform shape before processor: torch.Size([218560])

 67%|██████▋   | 634/950 [17:23<06:42,  1.27s/it]

Original waveform shape: torch.Size([2, 475398])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 172480])
Final waveform shape before processor: torch.Size([172480])

 67%|██████▋   | 635/950 [17:24<07:12,  1.37s/it]

Original waveform shape: torch.Size([2, 774396])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 280960])
Final waveform shape before processor: torch.Size([280960])

 67%|██████▋   | 636/950 [17:26<07:27,  1.43s/it]

Original waveform shape: torch.Size([2, 616518])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223680])
Final waveform shape before processor: torch.Size([223680])

 67%|██████▋   | 637/950 [17:28<07:52,  1.51s/it]

Original waveform shape: torch.Size([2, 641214])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

 67%|██████▋   | 638/950 [17:29<07:51,  1.51s/it]

Original waveform shape: torch.Size([2, 596233])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216321])
Final waveform shape before processor: torch.Size([216321])

 67%|██████▋   | 639/950 [17:31<07:51,  1.52s/it]

Original waveform shape: torch.Size([2, 854658])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 310080])
Final waveform shape before processor: torch.Size([310080])

 67%|██████▋   | 640/950 [17:33<08:33,  1.66s/it]

Original waveform shape: torch.Size([2, 614754])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223040])
Final waveform shape before processor: torch.Size([223040])

 67%|██████▋   | 641/950 [17:34<08:20,  1.62s/it]

Original waveform shape: torch.Size([2, 654444])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237440])
Final waveform shape before processor: torch.Size([237440])

 68%|██████▊   | 642/950 [17:36<08:56,  1.74s/it]

Original waveform shape: torch.Size([2, 536256])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 194560])
Final waveform shape before processor: torch.Size([194560])

 68%|██████▊   | 643/950 [17:38<08:26,  1.65s/it]

Original waveform shape: torch.Size([2, 577710])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209600])
Final waveform shape before processor: torch.Size([209600])

 68%|██████▊   | 644/950 [17:39<08:06,  1.59s/it]

Original waveform shape: torch.Size([2, 507150])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 184000])
Final waveform shape before processor: torch.Size([184000])

 68%|██████▊   | 645/950 [17:40<07:49,  1.54s/it]

Original waveform shape: torch.Size([2, 665910])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241600])
Final waveform shape before processor: torch.Size([241600])

 68%|██████▊   | 646/950 [17:42<07:48,  1.54s/it]

Original waveform shape: torch.Size([2, 580356])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 210560])
Final waveform shape before processor: torch.Size([210560])

 68%|██████▊   | 647/950 [17:43<07:29,  1.48s/it]

Original waveform shape: torch.Size([2, 679140])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 246400])
Final waveform shape before processor: torch.Size([246400])

 68%|██████▊   | 648/950 [17:45<07:54,  1.57s/it]

Original waveform shape: torch.Size([2, 324576])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 117760])
Final waveform shape before processor: torch.Size([117760])

 68%|██████▊   | 649/950 [17:46<07:01,  1.40s/it]

Original waveform shape: torch.Size([2, 587412])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 213120])
Final waveform shape before processor: torch.Size([213120])

 68%|██████▊   | 650/950 [17:48<07:20,  1.47s/it]

Original waveform shape: torch.Size([2, 520380])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 188800])
Final waveform shape before processor: torch.Size([188800])

 69%|██████▊   | 651/950 [17:49<07:48,  1.57s/it]

Original waveform shape: torch.Size([2, 572417])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 207680])
Final waveform shape before processor: torch.Size([207680])

 69%|██████▊   | 652/950 [17:51<07:32,  1.52s/it]

Original waveform shape: torch.Size([2, 331632])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 120320])
Final waveform shape before processor: torch.Size([120320])

 69%|██████▊   | 653/950 [17:52<06:58,  1.41s/it]

Original waveform shape: torch.Size([2, 597996])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216960])
Final waveform shape before processor: torch.Size([216960])

 69%|██████▉   | 654/950 [17:53<07:00,  1.42s/it]

Original waveform shape: torch.Size([2, 613872])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222720])
Final waveform shape before processor: torch.Size([222720])

 69%|██████▉   | 655/950 [17:55<06:57,  1.42s/it]

Original waveform shape: torch.Size([2, 586530])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212800])
Final waveform shape before processor: torch.Size([212800])

 69%|██████▉   | 656/950 [17:56<06:33,  1.34s/it]

Original waveform shape: torch.Size([2, 508032])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 184320])
Final waveform shape before processor: torch.Size([184320])

 69%|██████▉   | 657/950 [17:58<06:59,  1.43s/it]

Original waveform shape: torch.Size([2, 482453])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175040])
Final waveform shape before processor: torch.Size([175040])

 69%|██████▉   | 658/950 [17:59<06:32,  1.35s/it]

Original waveform shape: torch.Size([2, 670319])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 243200])
Final waveform shape before processor: torch.Size([243200])

 69%|██████▉   | 659/950 [18:01<07:15,  1.50s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

 69%|██████▉   | 660/950 [18:02<07:15,  1.50s/it]

Original waveform shape: torch.Size([2, 484218])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175680])
Final waveform shape before processor: torch.Size([175680])

 70%|██████▉   | 661/950 [18:04<06:55,  1.44s/it]

Original waveform shape: torch.Size([2, 660618])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239680])
Final waveform shape before processor: torch.Size([239680])

 70%|██████▉   | 662/950 [18:05<07:06,  1.48s/it]

Original waveform shape: torch.Size([2, 650034])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235840])
Final waveform shape before processor: torch.Size([235840])

 70%|██████▉   | 663/950 [18:07<07:23,  1.55s/it]

Original waveform shape: torch.Size([2, 645624])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234240])
Final waveform shape before processor: torch.Size([234240])

 70%|██████▉   | 664/950 [18:08<07:30,  1.58s/it]

Original waveform shape: torch.Size([2, 578592])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209920])
Final waveform shape before processor: torch.Size([209920])

 70%|███████   | 665/950 [18:10<07:28,  1.57s/it]

Original waveform shape: torch.Size([2, 590058])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 214080])
Final waveform shape before processor: torch.Size([214080])

 70%|███████   | 666/950 [18:12<07:38,  1.62s/it]

Original waveform shape: torch.Size([2, 677376])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 245760])
Final waveform shape before processor: torch.Size([245760])

 70%|███████   | 667/950 [18:14<08:16,  1.75s/it]

Original waveform shape: torch.Size([2, 545076])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 197760])
Final waveform shape before processor: torch.Size([197760])

 70%|███████   | 668/950 [18:15<07:48,  1.66s/it]

Original waveform shape: torch.Size([2, 600642])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 217920])
Final waveform shape before processor: torch.Size([217920])

 70%|███████   | 669/950 [18:17<07:27,  1.59s/it]

Original waveform shape: torch.Size([2, 483336])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175360])
Final waveform shape before processor: torch.Size([175360])

 71%|███████   | 670/950 [18:18<07:02,  1.51s/it]

Original waveform shape: torch.Size([2, 597996])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216960])
Final waveform shape before processor: torch.Size([216960])

 71%|███████   | 671/950 [18:19<07:01,  1.51s/it]

Original waveform shape: torch.Size([2, 404839])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 146881])
Final waveform shape before processor: torch.Size([146881])

 71%|███████   | 672/950 [18:21<06:43,  1.45s/it]

Original waveform shape: torch.Size([2, 597996])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216960])
Final waveform shape before processor: torch.Size([216960])

 71%|███████   | 673/950 [18:22<06:41,  1.45s/it]

Original waveform shape: torch.Size([2, 644741])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233920])
Final waveform shape before processor: torch.Size([233920])

 71%|███████   | 674/950 [18:24<07:20,  1.60s/it]

Original waveform shape: torch.Size([2, 589176])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 213760])
Final waveform shape before processor: torch.Size([213760])

 71%|███████   | 675/950 [18:26<07:07,  1.55s/it]

Original waveform shape: torch.Size([2, 593586])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215360])
Final waveform shape before processor: torch.Size([215360])

 71%|███████   | 676/950 [18:27<07:16,  1.59s/it]

Original waveform shape: torch.Size([2, 750582])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 272320])
Final waveform shape before processor: torch.Size([272320])

 71%|███████▏  | 677/950 [18:29<07:58,  1.75s/it]

Original waveform shape: torch.Size([2, 650034])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235840])
Final waveform shape before processor: torch.Size([235840])

 71%|███████▏  | 678/950 [18:31<07:15,  1.60s/it]

Original waveform shape: torch.Size([2, 473634])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 171840])
Final waveform shape before processor: torch.Size([171840])

 71%|███████▏  | 679/950 [18:32<07:02,  1.56s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

 72%|███████▏  | 680/950 [18:34<07:10,  1.59s/it]

Original waveform shape: torch.Size([2, 655326])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237760])
Final waveform shape before processor: torch.Size([237760])

 72%|███████▏  | 681/950 [18:35<07:12,  1.61s/it]

Original waveform shape: torch.Size([2, 387198])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 140480])
Final waveform shape before processor: torch.Size([140480])

 72%|███████▏  | 682/950 [18:36<05:47,  1.30s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

 72%|███████▏  | 683/950 [18:38<06:43,  1.51s/it]

Original waveform shape: torch.Size([2, 396900])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 144000])
Final waveform shape before processor: torch.Size([144000])

 72%|███████▏  | 684/950 [18:39<06:28,  1.46s/it]

Original waveform shape: torch.Size([2, 612990])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222400])
Final waveform shape before processor: torch.Size([222400])

 72%|███████▏  | 685/950 [18:41<06:58,  1.58s/it]

Original waveform shape: torch.Size([2, 682668])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 247680])
Final waveform shape before processor: torch.Size([247680])

 72%|███████▏  | 686/950 [18:43<07:18,  1.66s/it]

Original waveform shape: torch.Size([2, 735588])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 266880])
Final waveform shape before processor: torch.Size([266880])

 72%|███████▏  | 687/950 [18:45<07:44,  1.77s/it]

Original waveform shape: torch.Size([2, 525672])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 190720])
Final waveform shape before processor: torch.Size([190720])

 72%|███████▏  | 688/950 [18:46<07:10,  1.64s/it]

Original waveform shape: torch.Size([2, 448938])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 162880])
Final waveform shape before processor: torch.Size([162880])

 73%|███████▎  | 689/950 [18:48<06:51,  1.58s/it]

Original waveform shape: torch.Size([2, 508032])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 184320])
Final waveform shape before processor: torch.Size([184320])

 73%|███████▎  | 690/950 [18:50<07:06,  1.64s/it]

Original waveform shape: torch.Size([2, 688842])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 249920])
Final waveform shape before processor: torch.Size([249920])

 73%|███████▎  | 691/950 [18:51<07:12,  1.67s/it]

Original waveform shape: torch.Size([2, 555660])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 201600])
Final waveform shape before processor: torch.Size([201600])

 73%|███████▎  | 692/950 [18:53<06:59,  1.63s/it]

Original waveform shape: torch.Size([2, 576828])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209280])
Final waveform shape before processor: torch.Size([209280])

 73%|███████▎  | 693/950 [18:54<06:47,  1.59s/it]

Original waveform shape: torch.Size([2, 449379])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 163040])
Final waveform shape before processor: torch.Size([163040])

 73%|███████▎  | 694/950 [18:56<06:16,  1.47s/it]

Original waveform shape: torch.Size([2, 461286])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 167360])
Final waveform shape before processor: torch.Size([167360])

 73%|███████▎  | 695/950 [18:57<05:44,  1.35s/it]

Original waveform shape: torch.Size([2, 496567])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 180161])
Final waveform shape before processor: torch.Size([180161])

 73%|███████▎  | 696/950 [18:58<05:17,  1.25s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

 73%|███████▎  | 697/950 [18:59<04:57,  1.18s/it]

Original waveform shape: torch.Size([2, 623574])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226240])
Final waveform shape before processor: torch.Size([226240])

 73%|███████▎  | 698/950 [19:01<06:00,  1.43s/it]

Original waveform shape: torch.Size([2, 631512])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229120])
Final waveform shape before processor: torch.Size([229120])

 74%|███████▎  | 699/950 [19:03<07:05,  1.70s/it]

Original waveform shape: torch.Size([2, 659736])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239360])
Final waveform shape before processor: torch.Size([239360])

 74%|███████▎  | 700/950 [19:07<09:48,  2.35s/it]

Original waveform shape: torch.Size([2, 540666])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 196160])
Final waveform shape before processor: torch.Size([196160])

 74%|███████▍  | 701/950 [19:10<10:15,  2.47s/it]

Original waveform shape: torch.Size([2, 660618])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239680])
Final waveform shape before processor: torch.Size([239680])

 74%|███████▍  | 702/950 [19:13<11:32,  2.79s/it]

Original waveform shape: torch.Size([2, 643860])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233600])
Final waveform shape before processor: torch.Size([233600])

 74%|███████▍  | 703/950 [19:16<12:00,  2.92s/it]

Original waveform shape: torch.Size([2, 588294])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 213440])
Final waveform shape before processor: torch.Size([213440])

 74%|███████▍  | 704/950 [19:19<11:43,  2.86s/it]

Original waveform shape: torch.Size([2, 619165])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224641])
Final waveform shape before processor: torch.Size([224641])

 74%|███████▍  | 705/950 [19:22<11:26,  2.80s/it]

Original waveform shape: torch.Size([2, 698544])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 253440])
Final waveform shape before processor: torch.Size([253440])

 74%|███████▍  | 706/950 [19:26<12:26,  3.06s/it]

Original waveform shape: torch.Size([2, 529200])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 192000])
Final waveform shape before processor: torch.Size([192000])

 74%|███████▍  | 707/950 [19:30<13:32,  3.35s/it]

Original waveform shape: torch.Size([2, 602406])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218560])
Final waveform shape before processor: torch.Size([218560])

 75%|███████▍  | 708/950 [19:32<12:22,  3.07s/it]

Original waveform shape: torch.Size([2, 828198])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 300480])
Final waveform shape before processor: torch.Size([300480])

 75%|███████▍  | 709/950 [19:34<11:20,  2.82s/it]

Original waveform shape: torch.Size([2, 660618])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239680])
Final waveform shape before processor: torch.Size([239680])

 75%|███████▍  | 710/950 [19:36<10:04,  2.52s/it]

Original waveform shape: torch.Size([2, 605052])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219520])
Final waveform shape before processor: torch.Size([219520])

 75%|███████▍  | 711/950 [19:38<08:53,  2.23s/it]

Original waveform shape: torch.Size([2, 806149])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 292481])
Final waveform shape before processor: torch.Size([292481])

 75%|███████▍  | 712/950 [19:40<09:25,  2.38s/it]

Original waveform shape: torch.Size([2, 500976])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 181760])
Final waveform shape before processor: torch.Size([181760])

 75%|███████▌  | 713/950 [19:42<08:15,  2.09s/it]

Original waveform shape: torch.Size([2, 384552])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 139520])
Final waveform shape before processor: torch.Size([139520])

 75%|███████▌  | 714/950 [19:43<07:12,  1.83s/it]

Original waveform shape: torch.Size([2, 604170])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219200])
Final waveform shape before processor: torch.Size([219200])

 75%|███████▌  | 715/950 [19:44<06:50,  1.75s/it]

Original waveform shape: torch.Size([2, 535374])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 194240])
Final waveform shape before processor: torch.Size([194240])

 75%|███████▌  | 716/950 [19:46<06:34,  1.69s/it]

Original waveform shape: torch.Size([2, 925218])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 335680])
Final waveform shape before processor: torch.Size([335680])

 75%|███████▌  | 717/950 [19:48<07:10,  1.85s/it]

Original waveform shape: torch.Size([2, 595350])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216000])
Final waveform shape before processor: torch.Size([216000])

 76%|███████▌  | 718/950 [19:49<06:26,  1.67s/it]

Original waveform shape: torch.Size([2, 583002])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211520])
Final waveform shape before processor: torch.Size([211520])

 76%|███████▌  | 719/950 [19:52<06:57,  1.81s/it]

Original waveform shape: torch.Size([2, 418950])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 152000])
Final waveform shape before processor: torch.Size([152000])

 76%|███████▌  | 720/950 [19:53<06:33,  1.71s/it]

Original waveform shape: torch.Size([2, 600642])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 217920])
Final waveform shape before processor: torch.Size([217920])

 76%|███████▌  | 721/950 [19:54<05:55,  1.55s/it]

Original waveform shape: torch.Size([2, 530964])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 192640])
Final waveform shape before processor: torch.Size([192640])

 76%|███████▌  | 722/950 [19:56<05:40,  1.49s/it]

Original waveform shape: torch.Size([2, 646505])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234560])
Final waveform shape before processor: torch.Size([234560])

 76%|███████▌  | 723/950 [19:57<05:46,  1.53s/it]

Original waveform shape: torch.Size([2, 508914])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 184640])
Final waveform shape before processor: torch.Size([184640])

 76%|███████▌  | 724/950 [19:59<05:40,  1.51s/it]

Original waveform shape: torch.Size([2, 918602])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 333280])
Final waveform shape before processor: torch.Size([333280])

 76%|███████▋  | 725/950 [20:01<06:34,  1.75s/it]

Original waveform shape: torch.Size([2, 825552])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 299520])
Final waveform shape before processor: torch.Size([299520])

 76%|███████▋  | 726/950 [20:03<06:57,  1.86s/it]

Original waveform shape: torch.Size([2, 663264])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240640])
Final waveform shape before processor: torch.Size([240640])

 77%|███████▋  | 727/950 [20:05<07:16,  1.96s/it]

Original waveform shape: torch.Size([2, 986958])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 358080])
Final waveform shape before processor: torch.Size([358080])

 77%|███████▋  | 728/950 [20:08<07:35,  2.05s/it]

Original waveform shape: torch.Size([2, 452466])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 164160])
Final waveform shape before processor: torch.Size([164160])

 77%|███████▋  | 729/950 [20:09<06:34,  1.78s/it]

Original waveform shape: torch.Size([2, 640332])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232320])
Final waveform shape before processor: torch.Size([232320])

 77%|███████▋  | 730/950 [20:11<06:29,  1.77s/it]

Original waveform shape: torch.Size([2, 609462])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 221120])
Final waveform shape before processor: torch.Size([221120])

 77%|███████▋  | 731/950 [20:12<06:28,  1.78s/it]

Original waveform shape: torch.Size([2, 584766])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212160])
Final waveform shape before processor: torch.Size([212160])

 77%|███████▋  | 732/950 [20:14<05:58,  1.65s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

 77%|███████▋  | 733/950 [20:15<06:06,  1.69s/it]

Original waveform shape: torch.Size([2, 504063])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 182880])
Final waveform shape before processor: torch.Size([182880])

 77%|███████▋  | 734/950 [20:17<06:01,  1.67s/it]

Original waveform shape: torch.Size([2, 617401])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224001])
Final waveform shape before processor: torch.Size([224001])

 77%|███████▋  | 735/950 [20:19<05:48,  1.62s/it]

Original waveform shape: torch.Size([2, 2006991])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 728160])
Final waveform shape before processor: torch.Size([728160])

 77%|███████▋  | 736/950 [20:19<04:30,  1.27s/it]

Original waveform shape: torch.Size([2, 794184])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 288140])
Final waveform shape before processor: torch.Size([288140])

 78%|███████▊  | 737/950 [20:21<05:19,  1.50s/it]

Original waveform shape: torch.Size([2, 582120])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 211200])
Final waveform shape before processor: torch.Size([211200])

 78%|███████▊  | 738/950 [20:23<05:25,  1.54s/it]

Original waveform shape: torch.Size([2, 641214])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

 78%|███████▊  | 739/950 [20:24<05:36,  1.60s/it]

Original waveform shape: torch.Size([2, 773514])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 280640])
Final waveform shape before processor: torch.Size([280640])

 78%|███████▊  | 740/950 [20:27<06:13,  1.78s/it]

Original waveform shape: torch.Size([2, 539784])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 195840])
Final waveform shape before processor: torch.Size([195840])

 78%|███████▊  | 741/950 [20:28<06:14,  1.79s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

 78%|███████▊  | 742/950 [20:30<06:06,  1.76s/it]

Original waveform shape: torch.Size([2, 438354])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 159040])
Final waveform shape before processor: torch.Size([159040])

 78%|███████▊  | 743/950 [20:31<05:36,  1.62s/it]

Original waveform shape: torch.Size([2, 421596])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 152960])
Final waveform shape before processor: torch.Size([152960])

 78%|███████▊  | 744/950 [20:33<05:19,  1.55s/it]

Original waveform shape: torch.Size([2, 493920])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 179200])
Final waveform shape before processor: torch.Size([179200])

 78%|███████▊  | 745/950 [20:33<04:10,  1.22s/it]

Original waveform shape: torch.Size([2, 632394])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229440])
Final waveform shape before processor: torch.Size([229440])

 79%|███████▊  | 746/950 [20:35<04:37,  1.36s/it]

Original waveform shape: torch.Size([2, 654444])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237440])
Final waveform shape before processor: torch.Size([237440])

 79%|███████▊  | 747/950 [20:37<05:19,  1.57s/it]

Original waveform shape: torch.Size([2, 481572])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 174720])
Final waveform shape before processor: torch.Size([174720])

 79%|███████▊  | 748/950 [20:43<09:27,  2.81s/it]

Original waveform shape: torch.Size([2, 662382])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240320])
Final waveform shape before processor: torch.Size([240320])

 79%|███████▉  | 749/950 [20:46<09:48,  2.93s/it]

Original waveform shape: torch.Size([2, 527436])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 191360])
Final waveform shape before processor: torch.Size([191360])

 79%|███████▉  | 750/950 [20:48<08:26,  2.53s/it]

Original waveform shape: torch.Size([2, 584766])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212160])
Final waveform shape before processor: torch.Size([212160])

 79%|███████▉  | 751/950 [20:48<06:44,  2.03s/it]

Original waveform shape: torch.Size([2, 507150])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 184000])
Final waveform shape before processor: torch.Size([184000])

 79%|███████▉  | 752/950 [20:50<06:12,  1.88s/it]

Original waveform shape: torch.Size([2, 601524])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218240])
Final waveform shape before processor: torch.Size([218240])

 79%|███████▉  | 753/950 [20:52<05:54,  1.80s/it]

Original waveform shape: torch.Size([2, 608579])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220800])
Final waveform shape before processor: torch.Size([220800])

 79%|███████▉  | 754/950 [20:53<05:54,  1.81s/it]

Original waveform shape: torch.Size([2, 614753])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223040])
Final waveform shape before processor: torch.Size([223040])

 79%|███████▉  | 755/950 [20:55<05:47,  1.78s/it]

Original waveform shape: torch.Size([2, 657090])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 238400])
Final waveform shape before processor: torch.Size([238400])

 80%|███████▉  | 756/950 [20:57<05:40,  1.76s/it]

Original waveform shape: torch.Size([2, 554778])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 201280])
Final waveform shape before processor: torch.Size([201280])

 80%|███████▉  | 757/950 [20:57<04:33,  1.42s/it]

Original waveform shape: torch.Size([2, 563598])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 204480])
Final waveform shape before processor: torch.Size([204480])

 80%|███████▉  | 758/950 [20:59<04:43,  1.48s/it]

Original waveform shape: torch.Size([2, 665910])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241600])
Final waveform shape before processor: torch.Size([241600])

 80%|███████▉  | 759/950 [21:00<04:21,  1.37s/it]

Original waveform shape: torch.Size([2, 567126])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 205760])
Final waveform shape before processor: torch.Size([205760])

 80%|████████  | 760/950 [21:02<04:31,  1.43s/it]

Original waveform shape: torch.Size([2, 644742])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233920])
Final waveform shape before processor: torch.Size([233920])

 80%|████████  | 761/950 [21:04<04:55,  1.56s/it]

Original waveform shape: torch.Size([2, 552132])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 200320])
Final waveform shape before processor: torch.Size([200320])

 80%|████████  | 762/950 [21:05<05:09,  1.65s/it]

Original waveform shape: torch.Size([2, 660618])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239680])
Final waveform shape before processor: torch.Size([239680])

 80%|████████  | 763/950 [21:07<05:21,  1.72s/it]

Original waveform shape: torch.Size([2, 453348])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 164480])
Final waveform shape before processor: torch.Size([164480])

 80%|████████  | 764/950 [21:09<04:52,  1.57s/it]

Original waveform shape: torch.Size([2, 521262])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 189120])
Final waveform shape before processor: torch.Size([189120])

 81%|████████  | 765/950 [21:10<04:45,  1.55s/it]

Original waveform shape: torch.Size([2, 704719])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 255681])
Final waveform shape before processor: torch.Size([255681])

 81%|████████  | 766/950 [21:12<04:59,  1.63s/it]

Original waveform shape: torch.Size([2, 606816])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220160])
Final waveform shape before processor: torch.Size([220160])

 81%|████████  | 767/950 [21:13<04:53,  1.60s/it]

Original waveform shape: torch.Size([2, 593586])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215360])
Final waveform shape before processor: torch.Size([215360])

 81%|████████  | 768/950 [21:15<04:46,  1.57s/it]

Original waveform shape: torch.Size([2, 723240])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 262400])
Final waveform shape before processor: torch.Size([262400])

 81%|████████  | 769/950 [21:17<05:16,  1.75s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

 81%|████████  | 770/950 [21:19<05:38,  1.88s/it]

Original waveform shape: torch.Size([2, 694134])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 251840])
Final waveform shape before processor: torch.Size([251840])

 81%|████████  | 771/950 [21:21<05:30,  1.85s/it]

Original waveform shape: torch.Size([2, 663264])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240640])
Final waveform shape before processor: torch.Size([240640])

 81%|████████▏ | 772/950 [21:23<05:30,  1.86s/it]

Original waveform shape: torch.Size([2, 585648])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212480])
Final waveform shape before processor: torch.Size([212480])

 81%|████████▏ | 773/950 [21:25<05:15,  1.78s/it]

Original waveform shape: torch.Size([2, 641214])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

 81%|████████▏ | 774/950 [21:26<04:55,  1.68s/it]

Original waveform shape: torch.Size([2, 676494])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 245440])
Final waveform shape before processor: torch.Size([245440])

 82%|████████▏ | 775/950 [21:28<04:49,  1.65s/it]

Original waveform shape: torch.Size([2, 530082])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 192320])
Final waveform shape before processor: torch.Size([192320])

 82%|████████▏ | 776/950 [21:29<04:49,  1.66s/it]

Original waveform shape: torch.Size([2, 666792])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241920])
Final waveform shape before processor: torch.Size([241920])

 82%|████████▏ | 777/950 [21:31<05:11,  1.80s/it]

Original waveform shape: torch.Size([2, 621810])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 225600])
Final waveform shape before processor: torch.Size([225600])

 82%|████████▏ | 778/950 [21:33<04:56,  1.73s/it]

Original waveform shape: torch.Size([2, 628866])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 228160])
Final waveform shape before processor: torch.Size([228160])

 82%|████████▏ | 779/950 [21:34<04:44,  1.67s/it]

Original waveform shape: torch.Size([2, 690606])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 250560])
Final waveform shape before processor: torch.Size([250560])

 82%|████████▏ | 780/950 [21:36<04:54,  1.73s/it]

Original waveform shape: torch.Size([2, 554778])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 201280])
Final waveform shape before processor: torch.Size([201280])

 82%|████████▏ | 781/950 [21:38<04:45,  1.69s/it]

Original waveform shape: torch.Size([2, 607257])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220320])
Final waveform shape before processor: torch.Size([220320])

 82%|████████▏ | 782/950 [21:39<04:23,  1.57s/it]

Original waveform shape: torch.Size([2, 657973])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 238721])
Final waveform shape before processor: torch.Size([238721])

 82%|████████▏ | 783/950 [21:41<04:28,  1.61s/it]

Original waveform shape: torch.Size([2, 629748])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 228480])
Final waveform shape before processor: torch.Size([228480])

 83%|████████▎ | 784/950 [21:42<04:20,  1.57s/it]

Original waveform shape: torch.Size([2, 438354])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 159040])
Final waveform shape before processor: torch.Size([159040])

 83%|████████▎ | 785/950 [21:44<04:18,  1.57s/it]

Original waveform shape: torch.Size([2, 641214])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

 83%|████████▎ | 786/950 [21:45<04:16,  1.56s/it]

Original waveform shape: torch.Size([2, 601524])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218240])
Final waveform shape before processor: torch.Size([218240])

 83%|████████▎ | 787/950 [21:47<04:19,  1.59s/it]

Original waveform shape: torch.Size([2, 574182])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208320])
Final waveform shape before processor: torch.Size([208320])

 83%|████████▎ | 788/950 [21:49<04:18,  1.60s/it]

Original waveform shape: torch.Size([2, 534492])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 193920])
Final waveform shape before processor: torch.Size([193920])

 83%|████████▎ | 789/950 [21:50<03:56,  1.47s/it]

Original waveform shape: torch.Size([2, 980343])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 355680])
Final waveform shape before processor: torch.Size([355680])

 83%|████████▎ | 790/950 [21:52<04:37,  1.74s/it]

Original waveform shape: torch.Size([2, 650033])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235840])
Final waveform shape before processor: torch.Size([235840])

 83%|████████▎ | 791/950 [21:54<04:41,  1.77s/it]

Original waveform shape: torch.Size([2, 440118])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 159680])
Final waveform shape before processor: torch.Size([159680])

 83%|████████▎ | 792/950 [21:56<04:34,  1.74s/it]

Original waveform shape: torch.Size([2, 960497])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 348480])
Final waveform shape before processor: torch.Size([348480])

 83%|████████▎ | 793/950 [21:58<04:38,  1.78s/it]

Original waveform shape: torch.Size([2, 675612])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 245120])
Final waveform shape before processor: torch.Size([245120])

 84%|████████▎ | 794/950 [21:59<04:37,  1.78s/it]

Original waveform shape: torch.Size([2, 556542])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 201920])
Final waveform shape before processor: torch.Size([201920])

 84%|████████▎ | 795/950 [22:00<03:46,  1.46s/it]

Original waveform shape: torch.Size([2, 643860])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233600])
Final waveform shape before processor: torch.Size([233600])

 84%|████████▍ | 796/950 [22:02<03:45,  1.46s/it]

Original waveform shape: torch.Size([2, 627984])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227840])
Final waveform shape before processor: torch.Size([227840])

 84%|████████▍ | 797/950 [22:03<03:39,  1.44s/it]

Original waveform shape: torch.Size([2, 625337])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226880])
Final waveform shape before processor: torch.Size([226880])

 84%|████████▍ | 798/950 [22:05<03:47,  1.49s/it]

Original waveform shape: torch.Size([2, 653562])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237120])
Final waveform shape before processor: torch.Size([237120])

 84%|████████▍ | 799/950 [22:07<04:14,  1.69s/it]

Original waveform shape: torch.Size([2, 687960])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 249600])
Final waveform shape before processor: torch.Size([249600])

 84%|████████▍ | 800/950 [22:09<04:29,  1.80s/it]

Original waveform shape: torch.Size([2, 619164])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224640])
Final waveform shape before processor: torch.Size([224640])

 84%|████████▍ | 801/950 [22:11<04:24,  1.77s/it]

Original waveform shape: torch.Size([2, 487746])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 176960])
Final waveform shape before processor: torch.Size([176960])

 84%|████████▍ | 802/950 [22:12<03:55,  1.59s/it]

Original waveform shape: torch.Size([2, 662382])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240320])
Final waveform shape before processor: torch.Size([240320])

 85%|████████▍ | 803/950 [22:14<04:04,  1.66s/it]

Original waveform shape: torch.Size([2, 1028853])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 373280])
Final waveform shape before processor: torch.Size([373280])

 85%|████████▍ | 804/950 [22:16<04:44,  1.95s/it]

Original waveform shape: torch.Size([2, 592704])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215040])
Final waveform shape before processor: torch.Size([215040])

 85%|████████▍ | 805/950 [22:18<04:34,  1.89s/it]

Original waveform shape: torch.Size([2, 641214])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

 85%|████████▍ | 806/950 [22:20<04:36,  1.92s/it]

Original waveform shape: torch.Size([2, 760284])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 275840])
Final waveform shape before processor: torch.Size([275840])

 85%|████████▍ | 807/950 [22:26<07:50,  3.29s/it]

Original waveform shape: torch.Size([2, 920367])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 333920])
Final waveform shape before processor: torch.Size([333920])

 85%|████████▌ | 808/950 [22:29<07:02,  2.97s/it]

Original waveform shape: torch.Size([2, 588294])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 213440])
Final waveform shape before processor: torch.Size([213440])

 85%|████████▌ | 809/950 [22:31<06:18,  2.68s/it]

Original waveform shape: torch.Size([2, 437472])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 158720])
Final waveform shape before processor: torch.Size([158720])

 85%|████████▌ | 810/950 [22:32<05:04,  2.18s/it]

Original waveform shape: torch.Size([2, 640332])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232320])
Final waveform shape before processor: torch.Size([232320])

 85%|████████▌ | 811/950 [22:33<04:45,  2.05s/it]

Original waveform shape: torch.Size([2, 558305])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 202560])
Final waveform shape before processor: torch.Size([202560])

 85%|████████▌ | 812/950 [22:35<04:22,  1.90s/it]

Original waveform shape: torch.Size([2, 610344])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 221440])
Final waveform shape before processor: torch.Size([221440])

 86%|████████▌ | 813/950 [22:36<04:05,  1.79s/it]

Original waveform shape: torch.Size([2, 573300])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208000])
Final waveform shape before processor: torch.Size([208000])

 86%|████████▌ | 814/950 [22:38<03:41,  1.63s/it]

Original waveform shape: torch.Size([2, 649152])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235520])
Final waveform shape before processor: torch.Size([235520])

 86%|████████▌ | 815/950 [22:39<03:36,  1.61s/it]

Original waveform shape: torch.Size([2, 661500])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240000])
Final waveform shape before processor: torch.Size([240000])

 86%|████████▌ | 816/950 [22:41<03:46,  1.69s/it]

Original waveform shape: torch.Size([2, 971523])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 352480])
Final waveform shape before processor: torch.Size([352480])

 86%|████████▌ | 817/950 [22:44<04:28,  2.02s/it]

Original waveform shape: torch.Size([2, 473634])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 171840])
Final waveform shape before processor: torch.Size([171840])

 86%|████████▌ | 818/950 [22:45<04:03,  1.84s/it]

Original waveform shape: torch.Size([2, 594468])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215680])
Final waveform shape before processor: torch.Size([215680])

 86%|████████▌ | 819/950 [22:46<03:06,  1.43s/it]

Original waveform shape: torch.Size([2, 867888])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 314880])
Final waveform shape before processor: torch.Size([314880])

 86%|████████▋ | 820/950 [22:47<03:14,  1.50s/it]

Original waveform shape: torch.Size([2, 623573])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226240])
Final waveform shape before processor: torch.Size([226240])

 86%|████████▋ | 821/950 [22:49<03:19,  1.55s/it]

Original waveform shape: torch.Size([2, 461286])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 167360])
Final waveform shape before processor: torch.Size([167360])

 87%|████████▋ | 822/950 [22:51<03:15,  1.53s/it]

Original waveform shape: torch.Size([2, 562716])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 204160])
Final waveform shape before processor: torch.Size([204160])

 87%|████████▋ | 823/950 [22:52<03:17,  1.56s/it]

Original waveform shape: torch.Size([2, 660618])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 239680])
Final waveform shape before processor: torch.Size([239680])

 87%|████████▋ | 824/950 [22:54<03:14,  1.54s/it]

Original waveform shape: torch.Size([2, 680904])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 247040])
Final waveform shape before processor: torch.Size([247040])

 87%|████████▋ | 825/950 [22:56<03:41,  1.77s/it]

Original waveform shape: torch.Size([2, 640332])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232320])
Final waveform shape before processor: torch.Size([232320])

 87%|████████▋ | 826/950 [22:58<03:45,  1.82s/it]

Original waveform shape: torch.Size([2, 642096])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232960])
Final waveform shape before processor: torch.Size([232960])

 87%|████████▋ | 827/950 [23:00<03:35,  1.75s/it]

Original waveform shape: torch.Size([2, 597114])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 216640])
Final waveform shape before processor: torch.Size([216640])

 87%|████████▋ | 828/950 [23:01<03:30,  1.72s/it]

Original waveform shape: torch.Size([2, 448056])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 162560])
Final waveform shape before processor: torch.Size([162560])

 87%|████████▋ | 829/950 [23:02<03:06,  1.54s/it]

Original waveform shape: torch.Size([2, 585648])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212480])
Final waveform shape before processor: torch.Size([212480])

 87%|████████▋ | 830/950 [23:04<03:03,  1.53s/it]

Original waveform shape: torch.Size([2, 605052])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219520])
Final waveform shape before processor: torch.Size([219520])

 87%|████████▋ | 831/950 [23:05<02:56,  1.48s/it]

Original waveform shape: torch.Size([2, 603288])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218880])
Final waveform shape before processor: torch.Size([218880])

 88%|████████▊ | 832/950 [23:07<03:12,  1.63s/it]

Original waveform shape: torch.Size([2, 915956])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 332320])
Final waveform shape before processor: torch.Size([332320])

 88%|████████▊ | 833/950 [23:10<03:50,  1.97s/it]

Original waveform shape: torch.Size([2, 645624])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 234240])
Final waveform shape before processor: torch.Size([234240])

 88%|████████▊ | 834/950 [23:12<03:40,  1.90s/it]

Original waveform shape: torch.Size([2, 509796])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 184960])
Final waveform shape before processor: torch.Size([184960])

 88%|████████▊ | 835/950 [23:13<03:19,  1.73s/it]

Original waveform shape: torch.Size([2, 972405])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 352800])
Final waveform shape before processor: torch.Size([352800])

 88%|████████▊ | 836/950 [23:15<03:40,  1.94s/it]

Original waveform shape: torch.Size([2, 498330])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 180800])
Final waveform shape before processor: torch.Size([180800])

 88%|████████▊ | 837/950 [23:17<03:16,  1.74s/it]

Original waveform shape: torch.Size([2, 649152])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235520])
Final waveform shape before processor: torch.Size([235520])

 88%|████████▊ | 838/950 [23:19<03:18,  1.77s/it]

Original waveform shape: torch.Size([2, 477162])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 173120])
Final waveform shape before processor: torch.Size([173120])

 88%|████████▊ | 839/950 [23:19<02:45,  1.49s/it]

Original waveform shape: torch.Size([2, 664146])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240960])
Final waveform shape before processor: torch.Size([240960])

 88%|████████▊ | 840/950 [23:21<02:36,  1.42s/it]

Original waveform shape: torch.Size([2, 618282])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224320])
Final waveform shape before processor: torch.Size([224320])

 89%|████████▊ | 841/950 [23:22<02:41,  1.48s/it]

Original waveform shape: torch.Size([2, 483336])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 175360])
Final waveform shape before processor: torch.Size([175360])

 89%|████████▊ | 842/950 [23:24<02:36,  1.44s/it]

Original waveform shape: torch.Size([2, 652680])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236800])
Final waveform shape before processor: torch.Size([236800])

 89%|████████▊ | 843/950 [23:26<02:51,  1.61s/it]

Original waveform shape: torch.Size([2, 665910])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241600])
Final waveform shape before processor: torch.Size([241600])

 89%|████████▉ | 844/950 [23:27<02:53,  1.64s/it]

Original waveform shape: torch.Size([2, 553895])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 200960])
Final waveform shape before processor: torch.Size([200960])

 89%|████████▉ | 845/950 [23:29<02:50,  1.62s/it]

Original waveform shape: torch.Size([2, 638568])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231680])
Final waveform shape before processor: torch.Size([231680])

 89%|████████▉ | 846/950 [23:31<02:49,  1.63s/it]

Original waveform shape: torch.Size([2, 594468])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215680])
Final waveform shape before processor: torch.Size([215680])

 89%|████████▉ | 847/950 [23:32<02:56,  1.71s/it]

Original waveform shape: torch.Size([2, 574183])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 208321])
Final waveform shape before processor: torch.Size([208321])

 89%|████████▉ | 848/950 [23:34<02:57,  1.74s/it]

Original waveform shape: torch.Size([2, 590940])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 214400])
Final waveform shape before processor: torch.Size([214400])

 89%|████████▉ | 849/950 [23:36<02:54,  1.73s/it]

Original waveform shape: torch.Size([2, 665910])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 241600])
Final waveform shape before processor: torch.Size([241600])

 89%|████████▉ | 850/950 [23:38<02:56,  1.77s/it]

Original waveform shape: torch.Size([2, 404838])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 146880])
Final waveform shape before processor: torch.Size([146880])

 90%|████████▉ | 851/950 [23:39<02:38,  1.60s/it]

Original waveform shape: torch.Size([2, 429535])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 155841])
Final waveform shape before processor: torch.Size([155841])

 90%|████████▉ | 852/950 [23:40<02:24,  1.47s/it]

Original waveform shape: torch.Size([2, 614754])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223040])
Final waveform shape before processor: torch.Size([223040])

 90%|████████▉ | 853/950 [23:42<02:22,  1.47s/it]

Original waveform shape: torch.Size([2, 650917])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 236161])
Final waveform shape before processor: torch.Size([236161])

 90%|████████▉ | 854/950 [23:43<02:25,  1.52s/it]

Original waveform shape: torch.Size([2, 548604])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 199040])
Final waveform shape before processor: torch.Size([199040])

 90%|█████████ | 855/950 [23:45<02:41,  1.70s/it]

Original waveform shape: torch.Size([2, 885528])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 321280])
Final waveform shape before processor: torch.Size([321280])

 90%|█████████ | 856/950 [23:48<02:59,  1.91s/it]

Original waveform shape: torch.Size([2, 397782])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 144320])
Final waveform shape before processor: torch.Size([144320])

 90%|█████████ | 857/950 [23:49<02:41,  1.73s/it]

Original waveform shape: torch.Size([2, 380142])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 137920])
Final waveform shape before processor: torch.Size([137920])

 90%|█████████ | 858/950 [23:50<02:19,  1.51s/it]

Original waveform shape: torch.Size([2, 473635])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 171841])
Final waveform shape before processor: torch.Size([171841])

 90%|█████████ | 859/950 [23:51<02:11,  1.44s/it]

Original waveform shape: torch.Size([2, 663264])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 240640])
Final waveform shape before processor: torch.Size([240640])

 91%|█████████ | 860/950 [23:52<01:54,  1.27s/it]

Original waveform shape: torch.Size([2, 614754])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 223040])
Final waveform shape before processor: torch.Size([223040])

 91%|█████████ | 861/950 [23:54<02:04,  1.40s/it]

Original waveform shape: torch.Size([2, 427770])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 155200])
Final waveform shape before processor: torch.Size([155200])

 91%|█████████ | 862/950 [23:55<01:56,  1.32s/it]

Original waveform shape: torch.Size([2, 634158])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 230080])
Final waveform shape before processor: torch.Size([230080])

 91%|█████████ | 863/950 [23:57<02:02,  1.41s/it]

Original waveform shape: torch.Size([2, 475398])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 172480])
Final waveform shape before processor: torch.Size([172480])

 91%|█████████ | 864/950 [23:58<02:06,  1.47s/it]

Original waveform shape: torch.Size([2, 457758])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 166080])
Final waveform shape before processor: torch.Size([166080])

 91%|█████████ | 865/950 [24:00<02:04,  1.47s/it]

Original waveform shape: torch.Size([2, 657090])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 238400])
Final waveform shape before processor: torch.Size([238400])

 91%|█████████ | 866/950 [24:01<02:00,  1.43s/it]

Original waveform shape: torch.Size([2, 531846])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 192960])
Final waveform shape before processor: torch.Size([192960])

 91%|█████████▏| 867/950 [24:02<01:40,  1.21s/it]

Original waveform shape: torch.Size([2, 624456])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226560])
Final waveform shape before processor: torch.Size([226560])

 91%|█████████▏| 868/950 [24:04<01:51,  1.36s/it]

Original waveform shape: torch.Size([2, 486863])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 176640])
Final waveform shape before processor: torch.Size([176640])

 91%|█████████▏| 869/950 [24:05<01:52,  1.39s/it]

Original waveform shape: torch.Size([2, 545958])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 198080])
Final waveform shape before processor: torch.Size([198080])

 92%|█████████▏| 870/950 [24:07<01:51,  1.40s/it]

Original waveform shape: torch.Size([2, 458640])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 166400])
Final waveform shape before processor: torch.Size([166400])

 92%|█████████▏| 871/950 [24:08<01:43,  1.31s/it]

Original waveform shape: torch.Size([2, 641214])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

 92%|█████████▏| 872/950 [24:10<01:57,  1.51s/it]

Original waveform shape: torch.Size([2, 534492])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 193920])
Final waveform shape before processor: torch.Size([193920])

 92%|█████████▏| 873/950 [24:11<01:58,  1.53s/it]

Original waveform shape: torch.Size([2, 648269])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235200])
Final waveform shape before processor: torch.Size([235200])

 92%|█████████▏| 874/950 [24:13<01:53,  1.49s/it]

Original waveform shape: torch.Size([2, 734706])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 266560])
Final waveform shape before processor: torch.Size([266560])

 92%|█████████▏| 875/950 [24:15<02:08,  1.72s/it]

Original waveform shape: torch.Size([2, 609461])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 221120])
Final waveform shape before processor: torch.Size([221120])

 92%|█████████▏| 876/950 [24:17<02:07,  1.72s/it]

Original waveform shape: torch.Size([2, 724122])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 262720])
Final waveform shape before processor: torch.Size([262720])

 92%|█████████▏| 877/950 [24:18<02:09,  1.77s/it]

Original waveform shape: torch.Size([2, 655326])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 237760])
Final waveform shape before processor: torch.Size([237760])

 92%|█████████▏| 878/950 [24:20<02:01,  1.69s/it]

Original waveform shape: torch.Size([2, 627102])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227520])
Final waveform shape before processor: torch.Size([227520])

 93%|█████████▎| 879/950 [24:22<02:06,  1.79s/it]

Original waveform shape: torch.Size([2, 527877])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 191520])
Final waveform shape before processor: torch.Size([191520])

 93%|█████████▎| 880/950 [24:24<02:02,  1.75s/it]

Original waveform shape: torch.Size([2, 545076])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 197760])
Final waveform shape before processor: torch.Size([197760])

 93%|█████████▎| 881/950 [24:25<01:55,  1.67s/it]

Original waveform shape: torch.Size([2, 624456])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226560])
Final waveform shape before processor: torch.Size([226560])

 93%|█████████▎| 882/950 [24:27<01:53,  1.66s/it]

Original waveform shape: torch.Size([2, 644742])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 233920])
Final waveform shape before processor: torch.Size([233920])

 93%|█████████▎| 883/950 [24:28<01:52,  1.68s/it]

Original waveform shape: torch.Size([2, 553014])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 200640])
Final waveform shape before processor: torch.Size([200640])

 93%|█████████▎| 884/950 [24:30<01:48,  1.65s/it]

Original waveform shape: torch.Size([2, 464814])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 168640])
Final waveform shape before processor: torch.Size([168640])

 93%|█████████▎| 885/950 [24:32<01:44,  1.60s/it]

Original waveform shape: torch.Size([2, 598437])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 217120])
Final waveform shape before processor: torch.Size([217120])

 93%|█████████▎| 886/950 [24:34<01:51,  1.75s/it]

Original waveform shape: torch.Size([2, 554778])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 201280])
Final waveform shape before processor: torch.Size([201280])

 93%|█████████▎| 887/950 [24:35<01:46,  1.69s/it]

Original waveform shape: torch.Size([2, 617400])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224000])
Final waveform shape before processor: torch.Size([224000])

 93%|█████████▎| 888/950 [24:37<01:40,  1.61s/it]

Original waveform shape: torch.Size([2, 921249])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 334240])
Final waveform shape before processor: torch.Size([334240])

 94%|█████████▎| 889/950 [24:39<01:51,  1.82s/it]

Original waveform shape: torch.Size([2, 568890])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206400])
Final waveform shape before processor: torch.Size([206400])

 94%|█████████▎| 890/950 [24:40<01:32,  1.54s/it]

Original waveform shape: torch.Size([2, 592704])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215040])
Final waveform shape before processor: torch.Size([215040])

 94%|█████████▍| 891/950 [24:41<01:29,  1.51s/it]

Original waveform shape: torch.Size([2, 680903])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 247040])
Final waveform shape before processor: torch.Size([247040])

 94%|█████████▍| 892/950 [24:43<01:30,  1.56s/it]

Original waveform shape: torch.Size([2, 586530])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 212800])
Final waveform shape before processor: torch.Size([212800])

 94%|█████████▍| 893/950 [24:45<01:30,  1.58s/it]

Original waveform shape: torch.Size([2, 688401])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 249760])
Final waveform shape before processor: torch.Size([249760])

 94%|█████████▍| 894/950 [24:47<01:41,  1.81s/it]

Original waveform shape: torch.Size([2, 922572])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 334720])
Final waveform shape before processor: torch.Size([334720])

 94%|█████████▍| 895/950 [24:49<01:47,  1.95s/it]

Original waveform shape: torch.Size([2, 593586])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 215360])
Final waveform shape before processor: torch.Size([215360])

 94%|█████████▍| 896/950 [24:51<01:37,  1.80s/it]

Original waveform shape: torch.Size([2, 633276])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 229760])
Final waveform shape before processor: torch.Size([229760])

 94%|█████████▍| 897/950 [24:52<01:31,  1.73s/it]

Original waveform shape: torch.Size([2, 613873])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 222721])
Final waveform shape before processor: torch.Size([222721])

 95%|█████████▍| 898/950 [24:54<01:29,  1.72s/it]

Original waveform shape: torch.Size([2, 842310])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 305600])
Final waveform shape before processor: torch.Size([305600])

 95%|█████████▍| 899/950 [24:56<01:34,  1.85s/it]

Original waveform shape: torch.Size([2, 650034])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235840])
Final waveform shape before processor: torch.Size([235840])

 95%|█████████▍| 900/950 [24:58<01:33,  1.88s/it]

Original waveform shape: torch.Size([2, 501857])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 182080])
Final waveform shape before processor: torch.Size([182080])

 95%|█████████▍| 901/950 [25:00<01:29,  1.83s/it]

Original waveform shape: torch.Size([2, 853776])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 309760])
Final waveform shape before processor: torch.Size([309760])

 95%|█████████▍| 902/950 [25:02<01:36,  2.00s/it]

Original waveform shape: torch.Size([2, 492156])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 178560])
Final waveform shape before processor: torch.Size([178560])

 95%|█████████▌| 903/950 [25:04<01:28,  1.89s/it]

Original waveform shape: torch.Size([2, 538020])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 195200])
Final waveform shape before processor: torch.Size([195200])

 95%|█████████▌| 904/950 [25:05<01:23,  1.80s/it]

Original waveform shape: torch.Size([2, 608580])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220800])
Final waveform shape before processor: torch.Size([220800])

 95%|█████████▌| 905/950 [25:07<01:18,  1.74s/it]

Original waveform shape: torch.Size([2, 577710])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209600])
Final waveform shape before processor: torch.Size([209600])

 95%|█████████▌| 906/950 [25:09<01:14,  1.70s/it]

Original waveform shape: torch.Size([2, 623574])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 226240])
Final waveform shape before processor: torch.Size([226240])

 95%|█████████▌| 907/950 [25:11<01:17,  1.81s/it]

Original waveform shape: torch.Size([2, 618282])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 224320])
Final waveform shape before processor: torch.Size([224320])

 96%|█████████▌| 908/950 [25:12<01:11,  1.70s/it]

Original waveform shape: torch.Size([2, 677375])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 245760])
Final waveform shape before processor: torch.Size([245760])

 96%|█████████▌| 909/950 [25:14<01:09,  1.69s/it]

Original waveform shape: torch.Size([2, 837018])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 303680])
Final waveform shape before processor: torch.Size([303680])

 96%|█████████▌| 910/950 [25:16<01:12,  1.81s/it]

Original waveform shape: torch.Size([2, 576828])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 209280])
Final waveform shape before processor: torch.Size([209280])

 96%|█████████▌| 911/950 [25:17<01:08,  1.75s/it]

Original waveform shape: torch.Size([2, 1224657])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 444320])
Final waveform shape before processor: torch.Size([444320])

 96%|█████████▌| 912/950 [25:20<01:17,  2.04s/it]

Original waveform shape: torch.Size([2, 254898])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 92480])
Final waveform shape before processor: torch.Size([92480])

 96%|█████████▌| 913/950 [25:21<01:01,  1.67s/it]

Original waveform shape: torch.Size([2, 608580])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220800])
Final waveform shape before processor: torch.Size([220800])

 96%|█████████▌| 914/950 [25:23<00:59,  1.67s/it]

Original waveform shape: torch.Size([2, 568008])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 206080])
Final waveform shape before processor: torch.Size([206080])

 96%|█████████▋| 915/950 [25:24<00:57,  1.63s/it]

Original waveform shape: torch.Size([2, 600642])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 217920])
Final waveform shape before processor: torch.Size([217920])

 96%|█████████▋| 916/950 [25:26<00:56,  1.66s/it]

Original waveform shape: torch.Size([2, 1005480])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 364800])
Final waveform shape before processor: torch.Size([364800])

 97%|█████████▋| 917/950 [25:28<01:02,  1.90s/it]

Original waveform shape: torch.Size([2, 778806])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 282560])
Final waveform shape before processor: torch.Size([282560])

 97%|█████████▋| 918/950 [25:31<01:03,  1.99s/it]

Original waveform shape: torch.Size([2, 763812])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 277120])
Final waveform shape before processor: torch.Size([277120])

 97%|█████████▋| 919/950 [25:32<01:00,  1.95s/it]

Original waveform shape: torch.Size([2, 683550])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 248000])
Final waveform shape before processor: torch.Size([248000])

 97%|█████████▋| 920/950 [25:34<00:57,  1.92s/it]

Original waveform shape: torch.Size([2, 760285])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 275841])
Final waveform shape before processor: torch.Size([275841])

 97%|█████████▋| 921/950 [25:36<00:58,  2.01s/it]

Original waveform shape: torch.Size([2, 603288])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218880])
Final waveform shape before processor: torch.Size([218880])

 97%|█████████▋| 922/950 [25:38<00:51,  1.83s/it]

Original waveform shape: torch.Size([2, 608581])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 220801])
Final waveform shape before processor: torch.Size([220801])

 97%|█████████▋| 923/950 [25:39<00:47,  1.76s/it]

Original waveform shape: torch.Size([2, 502740])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 182400])
Final waveform shape before processor: torch.Size([182400])

 97%|█████████▋| 924/950 [25:41<00:43,  1.68s/it]

Original waveform shape: torch.Size([2, 657972])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 238720])
Final waveform shape before processor: torch.Size([238720])

 97%|█████████▋| 925/950 [25:43<00:41,  1.66s/it]

Original waveform shape: torch.Size([2, 952118])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 345440])
Final waveform shape before processor: torch.Size([345440])

 97%|█████████▋| 926/950 [25:45<00:46,  1.93s/it]

Original waveform shape: torch.Size([2, 601523])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218240])
Final waveform shape before processor: torch.Size([218240])

 98%|█████████▊| 927/950 [25:47<00:45,  1.97s/it]

Original waveform shape: torch.Size([2, 2410064])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 874400])
Final waveform shape before processor: torch.Size([874400])

 98%|█████████▊| 928/950 [25:48<00:33,  1.54s/it]

Original waveform shape: torch.Size([2, 674730])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 244800])
Final waveform shape before processor: torch.Size([244800])

 98%|█████████▊| 929/950 [25:49<00:33,  1.62s/it]

Original waveform shape: torch.Size([2, 427770])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 155200])
Final waveform shape before processor: torch.Size([155200])

 98%|█████████▊| 930/950 [25:51<00:30,  1.54s/it]

Original waveform shape: torch.Size([2, 815850])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 296000])
Final waveform shape before processor: torch.Size([296000])

 98%|█████████▊| 931/950 [25:53<00:31,  1.64s/it]

Original waveform shape: torch.Size([2, 366912])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 133120])
Final waveform shape before processor: torch.Size([133120])

 98%|█████████▊| 932/950 [25:54<00:26,  1.48s/it]

Original waveform shape: torch.Size([2, 760284])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 275840])
Final waveform shape before processor: torch.Size([275840])

 98%|█████████▊| 933/950 [25:56<00:27,  1.61s/it]

Original waveform shape: torch.Size([2, 601524])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 218240])
Final waveform shape before processor: torch.Size([218240])

 98%|█████████▊| 934/950 [25:57<00:25,  1.61s/it]

Original waveform shape: torch.Size([2, 893466])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 324160])
Final waveform shape before processor: torch.Size([324160])

 98%|█████████▊| 935/950 [26:00<00:29,  1.97s/it]

Original waveform shape: torch.Size([2, 537139])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 194881])
Final waveform shape before processor: torch.Size([194881])

 99%|█████████▊| 936/950 [26:02<00:24,  1.78s/it]

Original waveform shape: torch.Size([2, 562716])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 204160])
Final waveform shape before processor: torch.Size([204160])

 99%|█████████▊| 937/950 [26:03<00:22,  1.73s/it]

Original waveform shape: torch.Size([2, 641214])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 232640])
Final waveform shape before processor: torch.Size([232640])

 99%|█████████▊| 938/950 [26:05<00:19,  1.65s/it]

Original waveform shape: torch.Size([2, 382788])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 138880])
Final waveform shape before processor: torch.Size([138880])

 99%|█████████▉| 939/950 [26:06<00:16,  1.47s/it]

Original waveform shape: torch.Size([2, 1355193])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 491680])
Final waveform shape before processor: torch.Size([491680])

 99%|█████████▉| 940/950 [26:08<00:16,  1.69s/it]

Original waveform shape: torch.Size([2, 605052])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 219520])
Final waveform shape before processor: torch.Size([219520])

 99%|█████████▉| 941/950 [26:10<00:15,  1.70s/it]

Original waveform shape: torch.Size([2, 526555])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 191041])
Final waveform shape before processor: torch.Size([191041])

 99%|█████████▉| 942/950 [26:11<00:13,  1.67s/it]

Original waveform shape: torch.Size([2, 648270])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235200])
Final waveform shape before processor: torch.Size([235200])

 99%|█████████▉| 943/950 [26:13<00:12,  1.75s/it]

Original waveform shape: torch.Size([2, 384552])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 139520])
Final waveform shape before processor: torch.Size([139520])

 99%|█████████▉| 944/950 [26:14<00:09,  1.55s/it]

Original waveform shape: torch.Size([2, 1132929])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 411040])
Final waveform shape before processor: torch.Size([411040])

 99%|█████████▉| 945/950 [26:17<00:09,  1.95s/it]

Original waveform shape: torch.Size([2, 591381])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 214560])
Final waveform shape before processor: torch.Size([214560])

100%|█████████▉| 946/950 [26:19<00:07,  1.81s/it]

Original waveform shape: torch.Size([2, 636804])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 231040])
Final waveform shape before processor: torch.Size([231040])

100%|█████████▉| 947/950 [26:20<00:05,  1.79s/it]

Original waveform shape: torch.Size([2, 649152])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 235520])
Final waveform shape before processor: torch.Size([235520])

100%|█████████▉| 948/950 [26:22<00:03,  1.81s/it]

Original waveform shape: torch.Size([2, 626220])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 227200])
Final waveform shape before processor: torch.Size([227200])

100%|█████████▉| 949/950 [26:24<00:01,  1.84s/it]

Original waveform shape: torch.Size([2, 459522])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 166720])
Final waveform shape before processor: torch.Size([166720])

100%|██████████| 950/950 [26:25<00:00,  1.65s/it]

Original waveform shape: torch.Size([2, 622692])
Resampling from 44100 Hz to 16kHz
Converting multi-channel audio to mono by averaging channels. Original shape: torch.Size([2, 225920])
Final waveform shape before processor: torch.Size([225920])

100%|██████████| 950/950 [26:27<00:00,  1.67s/it]

Transcriptions saved to /content/asr_eval_finetuned_transcriptions.csv

In [ ]:
# Normalize both reference and ASR transcription for Fine-tuned model
#eval_df['ref_norm'] = eval_df['text'].apply(normalize_arabic)
eval_df['asr_norm_finetuned'] = eval_df['asr_transcription_finetuned'].apply(normalize_arabic)

In [ ]:
# Compute WER and CER for Fine-tuned model
eval_df['wer_finetuned'] = eval_df.apply(lambda row: wer(row['ref_norm'], row['asr_norm_finetuned']), axis=1)
eval_df['cer_finetuned'] = eval_df.apply(lambda row: cer(row['ref_norm'], row['asr_norm_finetuned']), axis=1)

# Print average WER and CER for Fine-tuned model
print(f"Fine-Tuned Model - WER: {eval_df['wer_finetuned'].mean()}")
print(f"Fine-Tuned Model - CER: {eval_df['cer_finetuned'].mean()}")

Fine-Tuned Model - WER: 0.37214257883552326
Fine-Tuned Model - CER: 0.15727691188171475

In [ ]:
# Compare results
results = {
    "Base Model WER": eval_df['wer_base'].mean(),
    "Base Model CER": eval_df['cer_base'].mean(),

    "Fine-Tuned WER": eval_df['wer_finetuned'].mean(),
    "Fine-Tuned CER": eval_df['cer_finetuned'].mean(),
}

for model, score in results.items():
    print(f"{model}: {score}")

Base Model WER: 0.5363087785012708
Base Model CER: 0.17257424279652153
Fine-Tuned WER: 0.37214257883552326
Fine-Tuned CER: 0.15727691188171475